### ISSUE TITLE
Groups & Attackers

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#105]
groups are apparently _not_ informed about the attacker, is that intentional?

**Comment by Mjnstag** [comment]
imo it is logical that they should be told who is attacking

**Comment by Shepherdwhen** [comment]
I have seen it happen when the host remembers to say

**Comment by McTsts** [comment]
It is currently explicitly _not_ said.

See this:
https://github.com/McTsts/Werewolves-Roles/blob/0690bd99d059bc310a7a0b2cccbf1c4d71b3620b/_rules/attacks/2%20groups#L2

I suggest we change it so that the group is informed who does the attack.

**Comment by Shepherdwhen** [comment]
It should be told because of macho, sleepless ect

**Comment by Shepherdwhen** [comment]
because if sleepless wolf attacks reaper and dies and the wolves don't know that the sleepless wolf attacked they could think devil + TK or Macho + TK or Fpa onto wolf, well fpa they wouldn't know if enchanted wolf did the attack or not
