### ISSUE TITLE
Redirecting Attacks

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#106]
What is the feedback for a redirected attack?
I'm guessing it should be "attack failed"?

**Comment by venomousbirds** [comment]
listening a reason why would be weird and it'd benefit the attacked. "attack failed" makes sense and is the default anyway

**Comment by McTsts** [comment]
> listening a reason why would be weird and it'd benefit the attacked. "attack failed" makes sense and is the default anyway

I agree. We should probably clarify that though.
