### ISSUE TITLE
Mayor >15

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#107]
is this power actually useful?

**Comment by cryptidjayden** [comment]
honestly, probably not, wolves usually overtake the vote, so town never uses it and wolves never use it to avoid looking like wolves, etc. etc. would suggest changing it to "can choose whether there are one or two lynch polls" or w/e

**Comment by McTsts** [comment]
Yeah, I was also thinking that seems more useful, on the other hand, that may be _too much_, but I'm not sure.

**Comment by venomousbirds** [comment]
I don't think we've actually seen it been used enough to say if it's useful or not, mostly because people really push on not choosing 2 while 2 lynches could definitely be helpful. Two lynch polls would likely have the same effect as top 2

**Comment by McTsts** [comment]
> I don't think we've actually seen it been used enough to say if it's useful or not, mostly because people really push on not choosing 2 while 2 lynches could definitely be helpful. Two lynch polls would likely have the same effect as top 2

I feel like the fact that we haven't really seen it enough to determine if it's useful just proves that it is not actually very useful.

**Comment by McTsts** [comment]
How about just 3 votes instead for >15? It's kinda lame, but it would make sense considering this part of Mayor is intended to balance it for more players so it won't be too weak.

**Comment by MrTurtleJr** [comment]
> Two lynch polls would likely have the same effect as top 2
Two lynch polls would make it harder to snipe for wolves, because, at least to my understanding, with 16 players alive, the poll would have to be split into 8-8 votes, as opposed to having 16 votes on both polls. And the reason for it rarely being used is often because it favors wolves, which two lynch polls would eliminate to a degree.

On the other hand, if there is no interest in that, we may as well just give the Mayor three votes as Ts suggested.

**Comment by McTsts** [comment]
Two lynches is just too much IMO because then it isn't really any harder to get the desired result on them than it is with 1 lynch

**Comment by Shepherdwhen** [comment]
It's hardly ever used, similar to a >12 guardian, I haven't seen that used before, possibly a solution to both is the mayor being able to decide which election takes place first, it does sound dumb but it may also be a nice secondary power to the >15 mayor

**Comment by MrTurtleJr** [comment]
Okay, I'm fine with deleting that power from the Mayor. The only time I've seen it in use was by newer players (once by me, once by someone else) thinking this is in the Townfolk's interest and it backfiring on them.

> he mayor being able to decide which election takes place first

This could work.

**Comment by McTsts** [comment]
> It's hardly ever used, similar to a >12 guardian, I haven't seen that used before, possibly a solution to both is the mayor being able to decide which election takes place first, it does sound dumb but it may also be a nice secondary power to the >15 mayor

Seems like an interesting idea, thought with this they should probably keep the double vote even with >15 players
