### ISSUE TITLE
FP Balance Change

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#109]
I suggest that a single flute player can enchant Round(n/10) players and several flute players can each enchant Round(n/20) players

**Comment by MrTurtleJr** [comment]
I think (1/10) and (1/20) sounds feasible. The usual games are around 20 players and that corresponds with the two enchants/night or one enchants/night with multiple FPs.

**Comment by Mjnstag** [comment]
> If there is more than one player in the Flute Player channel, at the start of the night, each Flute Player will be able to enchant one player. 
so this also applies when there is a flute apprentice?

**Comment by McTsts** [comment]
> > If there is more than one player in the Flute Player channel, at the start of the night, each Flute Player will be able to enchant one player.
> 
> so this also applies when there is a flute apprentice?

nope, that's unintentional

**Comment by McTsts** [comment]
though I think that's probably more of a channel management issue, maybe?
