### ISSUE TITLE
Warlock description is bad

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#11]

**Comment by venomousbirds** [comment]
Why?

**Comment by McTsts** [comment]
![image](https://user-images.githubusercontent.com/24660095/114476238-292ee300-9bfa-11eb-963f-a5ea0ad08a4e.png)

**Comment by venomousbirds** [comment]
Yeah it's pretty bad, but could easily be changed by taking away the fortune teller comparison and the overuse of the word Warlock
