### ISSUE TITLE
Powdered Hooker

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#111]
if a powdered hooker is at another players location (who isnt powdered) and then the Pyros ignite, who dies?

- Nobody (because the Hooker's house is powdered but they're not there)
- The Hooker (because they're powdered)
- The Hooker and the other player (because the Hooker is ignited killing both the Hooker and the other player)

**Comment by Shepherdwhen** [comment]
I'd say the second one because it is individual players who are powdered and not the house, but not the 3rd one because the second player isn't powdered

**Comment by McTsts** [comment]
yeah that makes sense logically, but technically the Hooker avoids any attacks directed at them so this is a bit of a weird situation

**Comment by McTsts** [comment]
Actually, if we do 2) then what happens when the player the Hooker is with is powdered? for consistency the Hooker should then live.

**Comment by cryptidjayden** [comment]
i've said before that it should fit scenario 1. think of it as gunpowder being placed in someone's basement.

**Comment by McTsts** [comment]
> i've said before that it should fit scenario 1. think of it as gunpowder being placed in someone's basement.

That'd also be what the current roles imply. Not sure if that's clear enough though.

**Comment by MrTurtleJr** [comment]
I'd definitely say 1.

> They will not be killed by attacks

> Since the Hooker is at the other player’s house and not at home, any attacks in the night will fail;

About the phrasing, maybe you could add a sentence about "all attacks (it's not abilities, it's only attacks, right?) on the Hooker automatically target their house/home" to clarify, although I think the current phrasing is pretty clear, to me at least (see the quotes).

**Comment by McTsts** [comment]
The issue is more in the pyro description than in the Hooker description I think. We should clarify there that igniting just executes a standard attack on all powdered players or something like that

**Comment by Shepherdwhen** [comment]
Yeah that works, I guess it makes sense that it's powdered players not powdered houses so the pyros should ignite a hooker who is powdered

**Comment by McTsts** [comment]
> Yeah that works, I guess it makes sense that it's powdered players not powdered houses so the pyros should ignite a hooker who is powdered

I think @MrTurtleJr, @cryptidjayden, and I want to go with 1) not 2).

**Comment by Shepherdwhen** [comment]
I think the issue with pyros is their attack isn't direct but indirect upon multiple people, it could be that a hooker who isn't at home can't be powdered but if they visit Someone else they're both powdered if the person they visit is powdered then indirectly both are killed when the ignite happens

**Comment by MrTurtleJr** [comment]
> I think the issue with pyros is their attack isn't direct but indirect upon multiple people, it could be that a hooker who isn't at home can't be powdered but if they visit Someone else they're both powdered if the person they visit is powdered then indirectly both are killed when the ignite happens

Yeah, but a powdered Hooker that visits an un-powdered player or stays home on the night of an ignite survives.

**Comment by McTsts** [comment]
> I think the issue with pyros is their attack isn't direct but indirect upon multiple people, it could be that a hooker who isn't at home can't be powdered but if they visit Someone else they're both powdered if the person they visit is powdered then indirectly both are killed when the ignite happens

My solution to this issue is to just clarify that Pyro ignites are in fact just normal attacks. 

>  We should clarify there that igniting just executes a standard attack on all powdered players or something like that

This means a powdered Hooker survives if they aren't home, but an unpowdered Hooker visiting a powdered player dies.
