### ISSUE TITLE
Suggestion: Fakeable TC

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#118]
Town Crier might be more interesting if they only receive their info when N1 begins

**Comment by cryptidjayden** [comment]
yeah cool. also should clarify about infected wolf making it unreliable?

**Comment by McTsts** [comment]
well with that change they'd get info N1 start, at which point it would still be reliable, however some clarification that that person can be betray would make sense

**Comment by venomousbirds** [comment]
I think keeping it at d0 makes it all the more interesting, because not many roles have d0 abilities

**Comment by McTsts** [comment]
The idea was that theoretically it'd be possible to fake claim TC

**Comment by McTsts** [comment]
anyone have an opinion on this?

**Comment by MrTurtleJr** [comment]
Why isn't TC fake-claimable currently?

**Comment by McTsts** [comment]
Well, it is claimable with two people, but not with one.
