### ISSUE TITLE
first day/night => D1/N1

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#131]
did we want to change all occurrences of first day/night to Day 1 and Night 1 so it's more clear?

**Comment by venomousbirds** [comment]
that'd be more clear, because most people, especially newer players, think of d0 when you say "first day"

**Comment by Mjnstag** [comment]
yea, probably a good idea

**Comment by McTsts** [comment]
oh I fixed this

**Comment by McTsts** [comment]
Fixed by #132 
must've forgotten to link
