### ISSUE TITLE
Stalker + Angel + Others

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#135]
If an Angel is lynched via Stalker votes, but also other votes, can the Stalker be killed?

**Comment by venomousbirds** [comment]
no, stalker didn't actually vote for angel, just assigned lynch votes.

**Comment by McTsts** [comment]
Yes, but an Angel can kill a Stalker if _only_ the Stalker votes voted for them

**Comment by venomousbirds** [comment]
that seems incorrect, because the stalker didn't actually vote (name doesn't show up)

**Comment by McTsts** [comment]
> If the Angel is lynched by unusual means (e.g. by the invisible Stalker votes or the Executioner selecting them) the player responsible for this will die with the Angel.

**Comment by McTsts** [comment]
It's an explicitly listed edge case

**Comment by venomousbirds** [comment]
oh my bad i didnt read role descriptions
in that case stalker can get killed
