### ISSUE TITLE
FPA Promotion

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#149]
So should the FPA become FP if the FP dies? In that case the ability to join the #enchanted channel should probably be moved to another role or removed entirely. 
If we do further FPA changes they should be added to PR #108

**Comment by MrTurtleJr** [comment]
I like the idea, especially because the name "apprentice" implies that.

**Comment by Shepherdwhen** [comment]
I agree with turtle the name works for that idea for the role, but we do also need a role that can enter the enchanted channel, I have been sitting on the name "Piper/pied Piper" looking for a use for it

**Comment by McTsts** [comment]
> I agree with turtle the name works for that idea for the role, but we do also need a role that can enter the enchanted channel, I have been sitting on the name "Piper/pied Piper" looking for a use for it

That role would probably just have the same problem where's it too weak? I mean originally FPA's only power was to join the enchanted channel after all.

**Comment by Shepherdwhen** [comment]
> > I agree with turtle the name works for that idea for the role, but we do also need a role that can enter the enchanted channel, I have been sitting on the name "Piper/pied Piper" looking for a use for it
> 
> That role would probably just have the same problem where's it too weak? I mean originally FPA's only power was to join the enchanted channel after all.

Ok so only problem is FPA can't become FP if it's already in the enchanted channel

**Comment by McTsts** [comment]
> > > I agree with turtle the name works for that idea for the role, but we do also need a role that can enter the enchanted channel, I have been sitting on the name "Piper/pied Piper" looking for a use for it
> > 
> > 
> > That role would probably just have the same problem where's it too weak? I mean originally FPA's only power was to join the enchanted channel after all.
> 
> Ok so only problem is FPA can't become FP if it's already in the enchanted channel

Which is why my suggestion is to remove the #enchanted channel thing in favor of becoming FP.

**Comment by Shepherdwhen** [comment]
Ok yeah I approve of removing the power completely if that is what you meant, I thought you were advocating it having both

**Comment by McTsts** [comment]
That must've been a misunderstanding. I made a rewritten version of FPA over on #108 ([this](https://github.com/McTsts/Werewolves-Roles/blob/0035f4b4a02d8b2395689f822bfb59e34b457fdd/other/flute/flute%20apprentice))
