### ISSUE TITLE
Are the following methods of medium "abuse" allowed

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#154]
- the wolves ask their dead allies a question in #wolfpack and then they try to get the medium to reveal the full results so they can get the answer to their question

this is kinda ridiculous but I really like the idea of that lol

- the medium asks "did player X asks you to vote yes?" and player X asks the dead participants to vote yes/no in a channel the medium can't access
- "were you a TM role?"

both of those are "simple yes/no" questions

**Comment by Shepherdwhen** [comment]
Depends how game breaking it is, also for the second one it's going to basically act like reporter you can just post a role and people answer yes or no, meaning you can check if reporter lies, so yes but also a weaker reporter before mayor seems broken

**Comment by McTsts** [comment]
the second one is supposed to confirm the Medium (the answer wouldnt mean anything to the medium, but it would mean something to another confirmed person that told the dead participants what to vote)

**Comment by Shepherdwhen** [comment]
I guess my point was a totally different form of abuse to guessing dead players roles/entire reporter lists plus with the added accuracy of guessing changed roles as long as there is more active town dead than active wolves/solo

**Comment by McTsts** [comment]
I'm not sure what you mean

**Comment by MrTurtleJr** [comment]
Point 1 shouldn't be allowed, I don't understand point 2 and point 3 is fine, in my opinion, as non-town can fake-claim.

**Comment by McTsts** [comment]
> Point 1 shouldn't be allowed, I don't understand point 2 and point 3 is fine, in my opinion, as non-town can fake-claim.

why should 1) be forbidden?

2):
- a confirmed role like the Bakers want to confirm the medium. In #bakers they say "@Dead Participant vote no"
- the Bakers tell the Medium to ask "Did the Bakers tell you to vote yes?"
- The Medium later tells the Bakers the result of that 
- The Bakers have now confirmed the Medium (sort of)

**Comment by Shepherdwhen** [comment]
I think we should judge it against the abuse of a similar role.

Is it more or less abuse than the bartender encryption key method

**Comment by MrTurtleJr** [comment]
> 
> 
> > Point 1 shouldn't be allowed, I don't understand point 2 and point 3 is fine, in my opinion, as non-town can fake-claim.
> 
> why should 1) be forbidden?
> 
> 2):
> 
>     * a confirmed role like the Bakers want to confirm the medium. In #bakers they say "@dead Participant vote no"
> 
>     * the Bakers tell the Medium to ask "Did the Bakers tell you to vote yes?"
> 
>     * The Medium later tells the Bakers the result of that
> 
>     * The Bakers have now confirmed the Medium (sort of)

Isn't 1) essentially the same situation as asking a question in #wolfpack and adding reactions to it, so your teammates can answer? The difference being that you aren't an actual Medium, but I'm not sure that the #wolfpack should make double-sided answers possible, if that's what you're referring to.

As for 2) I'd also say tentatively forbidden.

I just think that allowing players to interact with dead people in any other channels than #medium-question isn't the point of the role and it creates very many gray areas (two of which are in the OP here).

**Comment by McTsts** [comment]
IMO:
1) is allowed - It's not the Medium abusing their powers, it's the wolves trying to use it to their own advantage which I don't see a problem with.
2) is forbidden - The Medium is required to ask a simple yes/no question, in this situation it's basically the Bakers asking the question though.
3) I'm unsure - It's a yes/no question, but I'm not sure if the questions are supposed to be personal.

**Comment by McTsts** [comment]
> > > Point 1 shouldn't be allowed, I don't understand point 2 and point 3 is fine, in my opinion, as non-town can fake-claim.
> > 
> > 
> > why should 1) be forbidden?
> > 2):
> > ```
> > * a confirmed role like the Bakers want to confirm the medium. In #bakers they say "@dead Participant vote no"
> > 
> > * the Bakers tell the Medium to ask "Did the Bakers tell you to vote yes?"
> > 
> > * The Medium later tells the Bakers the result of that
> > 
> > * The Bakers have now confirmed the Medium (sort of)
> > ```
> 
> Isn't 1) essentially the same situation as asking a question in #wolfpack and adding reactions to it, so your teammates can answer? The difference being that you aren't an actual Medium, but I'm not sure that the #wolfpack should make double-sided answers possible, if that's what you're referring to.
> 
> As for 2) I'd also say tentatively forbidden.
> 
> I just think that allowing players to interact with dead people in any other channels than #medium-question isn't the point of the role and it creates very many gray areas (two of which are in the OP here).

For 1) - the questions could be predetermined, requiring no further interaction with the dead people.

**Comment by MrTurtleJr** [comment]
> 
> 
> IMO:
> 
>     1. is allowed - It's not the Medium abusing their powers, it's the wolves trying to use it to their own advantage which I don't see a problem with.
> 
>     2. is forbidden - The Medium is required to ask a simple yes/no question, in this situation it's basically the Bakers asking the question though.
> 
>     3. I'm unsure - It's a yes/no question, but I'm not sure if the questions are supposed to be personal.

Re: 3., isn't player X, who answers a poll titled "Is player X town?", also answering a personal question? I can see the reservations, though.

**Comment by McTsts** [comment]
> > IMO:
> > ```
> > 1. is allowed - It's not the Medium abusing their powers, it's the wolves trying to use it to their own advantage which I don't see a problem with.
> > 
> > 2. is forbidden - The Medium is required to ask a simple yes/no question, in this situation it's basically the Bakers asking the question though.
> > 
> > 3. I'm unsure - It's a yes/no question, but I'm not sure if the questions are supposed to be personal.
> > ```
> 
> Re: 3., isn't player X, who answers a poll titled "Is player X town?", also answering a personal question? I can see the reservations, though.

That's not really a personal question. It has one answer which is the same for everyone, though scum may try to answer incorrectly.
My example has a different answer for every player.

**Comment by MrTurtleJr** [comment]
> 
> 
> > > > Point 1 shouldn't be allowed, I don't understand point 2 and point 3 is fine, in my opinion, as non-town can fake-claim.
> > > 
> > > 
> > > why should 1) be forbidden?
> > > 2):
> > > ```
> > > * a confirmed role like the Bakers want to confirm the medium. In #bakers they say "@dead Participant vote no"
> > > 
> > > * the Bakers tell the Medium to ask "Did the Bakers tell you to vote yes?"
> > > 
> > > * The Medium later tells the Bakers the result of that
> > > 
> > > * The Bakers have now confirmed the Medium (sort of)
> > > ```
> > 
> > 
> > Isn't 1) essentially the same situation as asking a question in #wolfpack and adding reactions to it, so your teammates can answer? The difference being that you aren't an actual Medium, but I'm not sure that the #wolfpack should make double-sided answers possible, if that's what you're referring to.
> > As for 2) I'd also say tentatively forbidden.
> > I just think that allowing players to interact with dead people in any other channels than #medium-question isn't the point of the role and it creates very many gray areas (two of which are in the OP here).
> 
> For 1) - the questions could be predetermined, requiring no further interaction with the dead people.

I guess in the case of pre-determined questions it would be possible, but isn't that an edge case? The wolves would have to know the medium questions and have determined questions on the assumption that they are dying. But yeah, I can agree in that case.

**Comment by MrTurtleJr** [comment]
> 
> 
> > > IMO:
> > > ```
> > > 1. is allowed - It's not the Medium abusing their powers, it's the wolves trying to use it to their own advantage which I don't see a problem with.
> > > 
> > > 2. is forbidden - The Medium is required to ask a simple yes/no question, in this situation it's basically the Bakers asking the question though.
> > > 
> > > 3. I'm unsure - It's a yes/no question, but I'm not sure if the questions are supposed to be personal.
> > > ```
> > 
> > 
> > Re: 3., isn't player X, who answers a poll titled "Is player X town?", also answering a personal question? I can see the reservations, though.
> 
> That's not really a personal question. It has one answer which is the same for everyone, though scum may try to answer incorrectly.
> My example has a different answer for every player.

You're right. I'm still leaning for on that one, simply because it's easy to bluff that you are TM.

**Comment by McTsts** [comment]
> > > > > Point 1 shouldn't be allowed, I don't understand point 2 and point 3 is fine, in my opinion, as non-town can fake-claim.
> > > > 
> > > > 
> > > > why should 1) be forbidden?
> > > > 2):
> > > > ```
> > > > * a confirmed role like the Bakers want to confirm the medium. In #bakers they say "@dead Participant vote no"
> > > > 
> > > > * the Bakers tell the Medium to ask "Did the Bakers tell you to vote yes?"
> > > > 
> > > > * The Medium later tells the Bakers the result of that
> > > > 
> > > > * The Bakers have now confirmed the Medium (sort of)
> > > > ```
> > > 
> > > 
> > > Isn't 1) essentially the same situation as asking a question in #wolfpack and adding reactions to it, so your teammates can answer? The difference being that you aren't an actual Medium, but I'm not sure that the #wolfpack should make double-sided answers possible, if that's what you're referring to.
> > > As for 2) I'd also say tentatively forbidden.
> > > I just think that allowing players to interact with dead people in any other channels than #medium-question isn't the point of the role and it creates very many gray areas (two of which are in the OP here).
> > 
> > 
> > For 1) - the questions could be predetermined, requiring no further interaction with the dead people.
> 
> I guess in the case of pre-determined questions it would be possible, but isn't that an edge case? The wolves would have to know the medium questions and have determined questions on the assumption that they are dying. But yeah, I can agree in that case.

They don't have to know the medium questions. They can just say something like "if one of us dies, vote if it's safe to kill mayor" - all of those ofc requires convincing the medium to reveal who voted what.

**Comment by MrTurtleJr** [comment]
Oh okay, I understand. I'd say that's fine, but what isn't fine is pinging dead participants and asking them a question to vote on the Medium poll.

**Comment by Shepherdwhen** [comment]
I think the best way to prevent them all is if the medium doesn't know who answers what in the poll since there is dead non towns who will be answering the opposite of town to make the medium not confirmed, if the medium has 2 no and 3 yes but can't say who voted then bakers or other town roles can't prove the medium, the medium won't be able to answer the wolves question and will only know the amount of dead TM along with wolves who voted

**Comment by McTsts** [comment]
> I think the best way to prevent them all is if the medium doesn't know who answers what in the poll since there is dead non towns who will be answering the opposite of town to make the medium not confirmed, if the medium has 2 no and 3 yes but can't say who voted then bakers or other town roles can't prove the medium, the medium won't be able to answer the wolves question and will only know the amount of dead TM along with wolves who voted

actually, that's an interesting idea. It would also allow wolves to manipulate medium results more easily, which I think is probably good.

**Comment by Shepherdwhen** [comment]
> > I think the best way to prevent them all is if the medium doesn't know who answers what in the poll since there is dead non towns who will be answering the opposite of town to make the medium not confirmed, if the medium has 2 no and 3 yes but can't say who voted then bakers or other town roles can't prove the medium, the medium won't be able to answer the wolves question and will only know the amount of dead TM along with wolves who voted
> 
> actually, that's an interesting idea. It would also allow wolves to manipulate medium results more easily, which I think is probably good.

Oh yeah that's right currently when the medium knows who is town it can ignore the wolves answer

**Comment by MrTurtleJr** [comment]
I wouldn't be opposed to Medium not knowing who reacted. A somewhat trusted Medium and a town Reporter can be very strong.

**Comment by McTsts** [comment]
There's technically nothing that says that who votes what is revealed, so I guess I'll just close this.
