### ISSUE TITLE
Fox Suggestion

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#155]
Maybe we should make Fox abilities end-day abilities so that they aren't immediate and so that they can switch to joining the pack instead?

**Comment by Shepherdwhen** [comment]
What if the CF can ask for it to be immediate of EoD each time because an immediate is more useful D0 but if the CF gets later into the game if it's not found the pack it's more likely to die so may choose an EoD check

**Comment by MrTurtleJr** [comment]
> 
> 
> What if the CF can ask for it to be immediate of EoD each time because an immediate is more useful D0 but if the CF gets later into the game if it's not found the pack it's more likely to die so may choose an EoD check
Doesn't that over-complicate things? As far as I'm concerned, no other roles can do this, so why the exception? I'd be in support of an end-day ability.

**Comment by McTsts** [comment]
Yeah I agree, that seems a bit too over-complicated

**Comment by Shepherdwhen** [comment]
> > What if the CF can ask for it to be immediate of EoD each time because an immediate is more useful D0 but if the CF gets later into the game if it's not found the pack it's more likely to die so may choose an EoD check
> 
> Doesn't that over-complicate things? As far as I'm concerned, no other roles can do this, so why the exception? I'd be in support of an end-day ability.

Maybe, just feels like the D0 check is more useful being immediate as you're either gonna find a wolf and not die or find a good kill target for wolves, after that an End of Day check is much better

**Comment by MrTurtleJr** [comment]
Yeah, but I don't know if we should cater to D0 for the ability, as the ability will more often than not be used on a non-D0 day. I also just think that consistency would make already complicated roles easier to understand (re: new(er) players).

**Comment by McTsts** [comment]
> > > What if the CF can ask for it to be immediate of EoD each time because an immediate is more useful D0 but if the CF gets later into the game if it's not found the pack it's more likely to die so may choose an EoD check
> > 
> > 
> > Doesn't that over-complicate things? As far as I'm concerned, no other roles can do this, so why the exception? I'd be in support of an end-day ability.
> 
> Maybe, just feels like the D0 check is more useful being immediate as you're either gonna find a wolf and not die or find a good kill target for wolves, after that an End of Day check is much better

the wolves only get the info EoD anyway, but I was actually considering suggestion that DF joins the pack if they find a wolf

**Comment by Shepherdwhen** [comment]
> > > > What if the CF can ask for it to be immediate of EoD each time because an immediate is more useful D0 but if the CF gets later into the game if it's not found the pack it's more likely to die so may choose an EoD check
> > > 
> > > 
> > > Doesn't that over-complicate things? As far as I'm concerned, no other roles can do this, so why the exception? I'd be in support of an end-day ability.
> > 
> > 
> > Maybe, just feels like the D0 check is more useful being immediate as you're either gonna find a wolf and not die or find a good kill target for wolves, after that an End of Day check is much better
> 
> the wolves only get the info EoD anyway, but I was actually considering suggestion that DF joins the pack if they find a wolf

Oh I do like that idea but it makes it much weaker than the warlock or lone warlock since it's now basically that but once it finds a wolf the pack lose their WI

**Comment by McTsts** [comment]
> > > > > What if the CF can ask for it to be immediate of EoD each time because an immediate is more useful D0 but if the CF gets later into the game if it's not found the pack it's more likely to die so may choose an EoD check
> > > > 
> > > > 
> > > > Doesn't that over-complicate things? As far as I'm concerned, no other roles can do this, so why the exception? I'd be in support of an end-day ability.
> > > 
> > > 
> > > Maybe, just feels like the D0 check is more useful being immediate as you're either gonna find a wolf and not die or find a good kill target for wolves, after that an End of Day check is much better
> > 
> > 
> > the wolves only get the info EoD anyway, but I was actually considering suggestion that DF joins the pack if they find a wolf
> 
> Oh I do like that idea but it makes it much weaker than the warlock or lone warlock since it's now basically that but once it finds a wolf the pack lose their WI

My alternative idea was that the pack only learns the checked player and not the role 
![hepi](https://user-images.githubusercontent.com/24660095/115383665-6b49bd00-a1d6-11eb-80c0-331c26915b40.png)

Right now it just seems like the DF's power is a bit too strong resulting in it basically never joining the pack.

**Comment by MrTurtleJr** [comment]
> > > > What if the CF can ask for it to be immediate of EoD each time because an immediate is more useful D0 but if the CF gets later into the game if it's not found the pack it's more likely to die so may choose an EoD check
> > > Doesn't that over-complicate things? As far as I'm concerned, no other roles can do this, so why the exception? I'd be in support of an end-day ability.
> > Maybe, just feels like the D0 check is more useful being immediate as you're either gonna find a wolf and not die or find a good kill target for wolves, after that an End of Day check is much better
> the wolves only get the info EoD anyway, but I was actually considering suggestion that DF joins the pack if they find a wolf
Do you mean CF? I don't know how the DF finds a wolf.

**Comment by Shepherdwhen** [comment]
Maybe it can reveal the role to the pack but not the player, it's useful for pack to know what roles are still alive in open and know what roles exist in partials.

**Comment by MrTurtleJr** [comment]
> > > > What if the CF can ask for it to be immediate of EoD each time because an immediate is more useful D0 but if the CF gets later into the game if it's not found the pack it's more likely to die so may choose an EoD check
> > >
> > > Doesn't that over-complicate things? As far as I'm concerned, no other roles can do this, so why the exception? I'd be in support of an end-day ability.
> >
> > Maybe, just feels like the D0 check is more useful being immediate as you're either gonna find a wolf and not die or find a good kill target for wolves, after that an End of Day check is much better
>
> the wolves only get the info EoD anyway, but I was actually considering suggestion that DF joins the pack if they find a wolf

Do you mean CF? I don't know how the DF finds a wolf.

**Comment by McTsts** [comment]
> > > > > What if the CF can ask for it to be immediate of EoD each time because an immediate is more useful D0 but if the CF gets later into the game if it's not found the pack it's more likely to die so may choose an EoD check
> > > > 
> > > > 
> > > > Doesn't that over-complicate things? As far as I'm concerned, no other roles can do this, so why the exception? I'd be in support of an end-day ability.
> > > 
> > > 
> > > Maybe, just feels like the D0 check is more useful being immediate as you're either gonna find a wolf and not die or find a good kill target for wolves, after that an End of Day check is much better
> > 
> > 
> > the wolves only get the info EoD anyway, but I was actually considering suggestion that DF joins the pack if they find a wolf
> 
> Do you mean CF? I don't know how the DF finds a wolf.

Yeah, I meant CF.

**Comment by MrTurtleJr** [comment]
> Maybe it can reveal the role to the pack but not the player, it's useful for pack to know what roles are still alive in open and know what roles exist in partials.

This idea isn't too bad, I can get behind it.

**Comment by McTsts** [comment]
> Maybe it can reveal the role to the pack but not the player, it's useful for pack to know what roles are still alive in open and know what roles exist in partials.

Seems like then the CF still has no incentive to join the pack and will just be alone forever?

**Comment by Shepherdwhen** [comment]
> > Maybe it can reveal the role to the pack but not the player, it's useful for pack to know what roles are still alive in open and know what roles exist in partials.
> 
> Seems like then the CF still has no incentive to join the pack and will just be alone forever?

The incentive to join is to tell them who is what role, also this way the Pack can't slowly narrow down who is CF, the other way the pack will just end up killing that player who was checked because they know they're not CF

**Comment by McTsts** [comment]
> > > Maybe it can reveal the role to the pack but not the player, it's useful for pack to know what roles are still alive in open and know what roles exist in partials.
> > 
> > 
> > Seems like then the CF still has no incentive to join the pack and will just be alone forever?
> 
> The incentive to join is to tell them who is what role, also this way the Pack can't slowly narrow down who is CF, the other way the pack will just end up killing that player who was checked because they know they're not CF

Oh, I misunderstood. So the pack gets the role (but not the player) and the CF just knows the player (since they selected them).

**Comment by MrTurtleJr** [comment]
Oh, so it's a whole "CF and Wolfpack info is useless until CF joins the pack"-kind of thing? I guess that makes sense, although if we make the ability end-day, it weakens the CF, as they wouldn't be able to immediately join the Wolfpack and share info if they are chosen as the lynch.

**Comment by Shepherdwhen** [comment]
> > > > Maybe it can reveal the role to the pack but not the player, it's useful for pack to know what roles are still alive in open and know what roles exist in partials.
> > > 
> > > 
> > > Seems like then the CF still has no incentive to join the pack and will just be alone forever?
> > 
> > 
> > The incentive to join is to tell them who is what role, also this way the Pack can't slowly narrow down who is CF, the other way the pack will just end up killing that player who was checked because they know they're not CF
> 
> Oh, I misunderstood. So the pack gets the role (but not the player) and the CF just knows the player (since they selected them).

Yeah :p makes sense as it means the Wolfpack can still risk killing the CF at night if it doesn't find them, otherwise they just kill who the CF checked as they're not CF

**Comment by McTsts** [comment]
> Oh, so it's a whole "CF and Wolfpack info is useless until CF joins the pack"-kind of thing? I guess that makes sense, although if we make the ability end-day, it weakens the CF, as they wouldn't be able to immediately join the Wolfpack and share info if they are chosen as the lynch.

What I mean is that the check is EoD but joining is immediate.

**Comment by Shepherdwhen** [comment]
I think the problems with CF currently are

If the CF check is immediate then it can't then switch to a pack wolf if necessary

If the wolf knows who the CF checked then they know they're not CF so could blindly kill them, especially current version which gives WP the role too

Once CF finds a wolf there is no reason for it to join the pack until every other wolf dies

**Comment by McTsts** [comment]
> I think the problems with CF currently are
> 
> If the CF check is immediate then it can't then switch to a pack wolf if necessary
> 
> If the wolf knows who the CF checked then they know they're not CF so could blindly kill them, especially current version which gives WP the role too
> 
> Once CF finds a wolf there is no reason for it to join the pack until every other wolf dies

So this should solve it, right?

- The CF doesn't learn the role, only the wolfpack does
- Investigating is an EoD effect (it kinda would become one by default now anyway)
- Joining the pack stays an immediate effect

**Comment by Shepherdwhen** [comment]
> > I think the problems with CF currently are
> > If the CF check is immediate then it can't then switch to a pack wolf if necessary
> > If the wolf knows who the CF checked then they know they're not CF so could blindly kill them, especially current version which gives WP the role too
> > Once CF finds a wolf there is no reason for it to join the pack until every other wolf dies
> 
> So this should solve it, right?
> 
> * The CF doesn't learn the role, only the wolfpack does
> * Investigating is an EoD effect (it kinda would become one by default now anyway)
> * Joining the pack stays an immediate effect

Solves every issue
Unless a wolf is outed and CF CCs them to get put in pack contact

**Comment by McTsts** [comment]
> > > I think the problems with CF currently are
> > > If the CF check is immediate then it can't then switch to a pack wolf if necessary
> > > If the wolf knows who the CF checked then they know they're not CF so could blindly kill them, especially current version which gives WP the role too
> > > Once CF finds a wolf there is no reason for it to join the pack until every other wolf dies
> > 
> > 
> > So this should solve it, right?
> > 
> > * The CF doesn't learn the role, only the wolfpack does
> > * Investigating is an EoD effect (it kinda would become one by default now anyway)
> > * Joining the pack stays an immediate effect
> 
> Solves every issue
> Unless a wolf is outed and CF CCs them to get put in pack contact

That's fine - the same can happen for Lone Wolfs and Disguised Fox as well. It just shouldn't be _too_ easy.
