### ISSUE TITLE
Pack tanner kill

### ISSUE THREAD

**Issue by Shepherdwhen** [McTsts/Werewolves-Roles#157]
Since the pack tanner is a non lycan should it be involved in the pack kill or not since in the case of a priest Vs last wolf the priest would lose if it's pack tanner or at and huntsman having conflicting info on it, this seems like a valid downside to having certain immunity whilst being in the pack

**Comment by McTsts** [comment]
Lone Warlock (pack) has the same situation

**Comment by Shepherdwhen** [comment]
NGL I genuinely thought LWa became a wolf for some reason

**Comment by McTsts** [comment]
I think non-lycans being involved in the kill is probably fine
