### ISSUE TITLE
"currently chef is a little bit boring as a role i think"

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#160]
"i think if the chef kill was end night, there'd be more inventive to poison food, because people wouldn't know chef had betrayed them" 
"as it is, poisoning food can actively sabotage chef's chances"
- @cryptidjayden

**Comment by Shepherdwhen** [comment]
That makes sense since the only other thing it could be would be devil

**Comment by McTsts** [comment]
> That makes sense since the only other thing it could be would be devil

Chef is the only possible EoD kill that is unrelated to the Lynch.

**Comment by Shepherdwhen** [comment]
I'm sure a devil soul kill can also be done at EoD by delayed action, as in Os6c on the final day

> > That makes sense since the only other thing it could be would be devil
> 
> Chef is the only possible EoD kill that is unrelated to the Lynch.

**Comment by McTsts** [comment]
> I'm sure a devil soul kill can also be done at EoD by delayed action, as in Os6c on the final day
> 
> > > That makes sense since the only other thing it could be would be devil
> > 
> > 
> > Chef is the only possible EoD kill that is unrelated to the Lynch.

delayed actions can't be EoD

**Comment by McTsts** [comment]
> Delaying Immediate Abilities is not possible. One exception is that an immediate ability can be chosen one phase before it has to be executed (e.g. a Fortune Teller choosing a target during the day). If this is the case, the Game Masters will execute the immediate ability at an arbitrary time during its phase (the time can not be chosen).

**Comment by Mjnstag** [comment]
we probably should test this one

**Comment by McTsts** [comment]
> we probably should test this one

test what?

**Comment by Shepherdwhen** [comment]
solo focused food, so for each solo team in the game the chef can use a (Powdered, Demonised, Soul-Stealing, Enchanted, Contaminated) bread once or twice per game to maybe help the solo team they are aligned with out more, since poison benefits some of the teams less than others ect

**Comment by McTsts** [comment]
This is an interesting idea, however it does just make it so people would be even less likely to eat the food, I think.

**Comment by bobloy** [comment]
I think chef would just be more fun if they gave out 2 food at a time

**Comment by Shepherdwhen** [comment]
> I think chef would just be more fun if they gave out 2 food at a time

That's an issue due to the 1 restaurant and technically the LA => Chef Join edgecase poll, also it means chef can't protect waiters as it would out one waiter to another waiter. 

People need more reason to eat the bread, maybe it should protect them from the next attack on them, because you don't eat because you don't know if you will be attacked the night after you have been served, however if you eat food and it lasts until you are next attacked maybe it means more people will eat early in the game

**Comment by venomousbirds** [comment]
There could just be 2 restaurant channels. But more food isn't neccesary and would probably throw the role off-balance

**Comment by bobloy** [comment]
Maybe the chef doesn't know who it's waiters are at the beginning of the game, and they only figure it out when they successfully give food to a waiter.

**Comment by McTsts** [comment]
> Maybe the chef doesn't know who it's waiters are at the beginning of the game, and they only figure it out when they successfully give food to a waiter.

I think that wouldn't make it very fun to be Chef. It would take a long time to figure out your waiters (assuming you can figure them out at all)

**Comment by McTsts** [comment]
Nobody marked this issue, so I guess it isn't relevant anymore?

**Comment by Shepherdwhen** [comment]
This issue seems to have been solved with the changes to other roles

The issue was chef is outed as the only end day kill

Now due to changes wisp, delayed soul kill, delayed barber kill are/can be end day

This means an end day kill is not necessarily chef if one of these role exists

**Comment by McTsts** [comment]
delayed soul kill and delayed barber kills are _not_ end day

**Comment by Shepherdwhen** [comment]
> delayed soul kill and delayed barber kills are _not_ end day

I thought with the rule changes you can delay immediate actions to the end of a phase?

**Comment by McTsts** [comment]
No, it delays it to just before the end of the phase

**Comment by Shepherdwhen** [comment]
> No, it delays it to just before the end of the phase

Ok that makes more sense I guess

So maybe we need a couple more end day kills to make chef easier to do poison
