### ISSUE TITLE
LA Waiter Copy

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#161]
"clarify that lookalike does NOT copy anything to do with being waiter" - @cryptidjayden

**Comment by McTsts** [comment]
Technically I think it's supposed to copy it right now 
![hepi](https://user-images.githubusercontent.com/24660095/115413055-28e3a880-a1f5-11eb-86cd-d792877331dd.png)

**Comment by Shepherdwhen** [comment]
Look Alike copies all data but does that count as data or a condition of the chef, since waiter is not an aspect of the role or kill and instead is an aspect of the chef's wincon

**Comment by Shepherdwhen** [comment]
Though Maybe clarification on thief targeting waiter could help the situation too

**Comment by venomousbirds** [comment]
Look Alike copies all data so I think it should copy waiter, but should chef be informed then?

**Comment by McTsts** [comment]
> Look Alike copies all data so I think it should copy waiter, but should chef be informed then?

This doesn't answer the question, but similarly what happens when a LA copies a Fletcher's Customer? Same problem as what you said. Is the Fletcher informed in that case?

**Comment by McTsts** [comment]
wait wait wait wait what happens when a Devil's Wager Recipient is copied??

**Comment by Shepherdwhen** [comment]
what if psychopath target is copied too? that's a similar condition to being waiter

**Comment by McTsts** [comment]
> what if psychopath target is copied too? that's a similar condition to being waiter

This is not a definite answer but I usually consider Chef's Waiter, Cupid's Lover, Fletcher's Customer and Mad Scientist's Targets as pseudo-roles (hence also #146) whereas for Psychopath Target I don't (and instead I'd just consider it a list the psychopath has)

**Comment by McTsts** [comment]
Though arguably Chef's Waiter is the same thing as Psychopath's target and maybe both should *not* be considered pseudo roles

**Comment by venomousbirds** [comment]
psychopath target could be copied, because look alike copies all data
devil's wager recipient would also be copied according to the lookalike description (it is data similar to enchanted)

**Comment by Shepherdwhen** [comment]
Ok I feel thought that psychopath has the list to kill as part of it's wincon similar how the list of waiters is part of chef wincon

**Comment by McTsts** [comment]
My argument is that psychopath's target is data on the psychopath, not the player (hence if LA copies a Psycho it copies the target) and same for Chef's Waiter actually

**Comment by McTsts** [comment]
actually same for MS's Target

**Comment by venomousbirds** [comment]
those two make sense, yes. they're psycho/chef specific

**Comment by McTsts** [comment]
But Fletcher's Customer and Cupid's Lover are both things that are definitely data *on you* since they change your abilities/win con - the others don't do that

**Comment by Shepherdwhen** [comment]
also theose two are decided by a player not the hosts

**Comment by McTsts** [comment]
oh yeah

**Comment by McTsts** [comment]
Well either way I think we should consider waiter/ms target/psycho target as "lists" that are part of those roles and lover/customer as data on the player itself... not sure if there's a good way to clarify that

**Comment by McTsts** [comment]
honestly LA basically needs a list of every role and then the special behavior for each role

**Comment by Shepherdwhen** [comment]
You also have to think copying waiter or psychopath target makes the unaligned role's wincon easier or harder than it should be by default

Because if LA copies town waiter of course chef will now side with town if LA also is waiter, and now psychopath has to get an extra person killed that it didn't have to before

**Comment by McTsts** [comment]
Yeah I think its definitely better if those aren't copied

**Comment by Shepherdwhen** [comment]
> Because if LA copies town waiter of course chef will now side with town if LA also is waiter

Also forgot to mention chef has 4 lifelines not 3 or 5 lifelines not 4 ect

**Comment by McTsts** [comment]
> Well either way I think we should consider waiter/ms target/psycho target as "lists" that are part of those roles and lover/customer as data on the player itself... not sure if there's a good way to clarify that

This.
