### ISSUE TITLE
Mayor/Guardian Ability

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#163]
Are these abilities end or immediate effects?

**Comment by MrTurtleJr** [comment]
Shouldn't they be end-night effects? If they were to be killed midnight, their choice shouldn't be able go through.

**Comment by McTsts** [comment]
> Shouldn't they be end-night effects? If they were to be killed midnight, their choice shouldn't be able go through.

that's why I'm asking

**Comment by McTsts** [comment]
> Shouldn't they be end-night effects? If they were to be killed midnight, their choice shouldn't be able go through.

Actually I somehow thought end night kills would stop it, but of course they don't. Is this really relevant then? I feel like Mayor/Guardian make more sense as immediate abilities from the way they work (especially Guardian though)
