### ISSUE TITLE
Wolfpack Saint/Demon

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#164]
If the last remaining member of the wolfpack is a Saint/Demon, is the pack disbanded?

**Comment by Shepherdwhen** [comment]
I would assume so, It's disbanded if the last member is vampire, so is the cult if the last member is vampire

**Comment by MrTurtleJr** [comment]
I assume you mean Undead when you say Vampire? But yeah, if all remaining members of the wolfpack are not Wolves anymore (such as done with Undead), the pack should be disbanded.

**Comment by Shepherdwhen** [comment]
Oh yeah I meant vampire team but it's called crypt team. But yeah it should just disband if there are no wolves/www/gww in the pack

**Comment by McTsts** [comment]
> I would assume so, It's disbanded if the last member is vampire, so is the cult if the last member is vampire

but the cult isn't disbanded if the last member is a wolf see #4

**Comment by Shepherdwhen** [comment]
> > I would assume so, It's disbanded if the last member is vampire, so is the cult if the last member is vampire
> 
> but the cult isn't disbanded if the last member is a wolf see #4

I guess wolves should disband since wolves who lose their role can't vote on the kill poll but apparently cult who do lose their role can

**Comment by McTsts** [comment]
> > > I would assume so, It's disbanded if the last member is vampire, so is the cult if the last member is vampire
> > 
> > 
> > but the cult isn't disbanded if the last member is a wolf see #4
> 
> I guess wolves should disband since wolves who lose their role can't vote on the kill poll but apparently cult who do lose their role can

only Undead can't vote on polls. If you lose your vote in another way you can still vote.

**Comment by Shepherdwhen** [comment]
> > > > I would assume so, It's disbanded if the last member is vampire, so is the cult if the last member is vampire
> > > 
> > > 
> > > but the cult isn't disbanded if the last member is a wolf see #4
> > 
> > 
> > I guess wolves should disband since wolves who lose their role can't vote on the kill poll but apparently cult who do lose their role can
> 
> only Undead can't vote on polls. If you lose your vote in another way you can still vote.

Maybe it should disband for balance reasons as otherwise the devil/archa team have a directly useable kill now
