### ISSUE TITLE
Solo Power's and Unaligned Misc

### ISSUE THREAD

**Issue by Shepherdwhen** [McTsts/Werewolves-Roles#169]
Do Unaligned Miscellaneous need to be targeted by a Solo Power in order for that solo to win, e.g be enchanted/herded or be undead for Flute Players or Shepherd or Vampires to win. If they don't then that may warrant clarification on the wincons of said roles

**Comment by MrTurtleJr** [comment]
I think that all Unaligned need to be targeted. The FP win-con specifies:
> If all living players are either enchanted or Flute team members, the Flute team wins

This doesn't mean that Unaligned can't win with them, though. (E.g. in a game with FP and Chef, the Chef needs to be enchanted for FP to win, but can still win assuming one or more of their waiters (and themselves) are alive when FP enchants everyone.

**Comment by McTsts** [comment]
Unaligned roles are not meant to block any win conditions

**Comment by MrTurtleJr** [comment]
> Unaligned roles are not meant to block any win conditions

So you're saying that UM needn't be targeted by solo or opposite?

**Comment by Shepherdwhen** [comment]
> Unaligned roles are not meant to block any win conditions

So they don't need to be enchanted or do need to be for an FP to win as an example, that's the issue since you'd assume because SK don't need to kill them then SP don't need to target them, however wincons don't specify this

**Comment by McTsts** [comment]
> > Unaligned roles are not meant to block any win conditions
> 
> So you're saying that UM needn't be targeted by solo or opposite?

This is how I'd currently run the game. But I don't think there's anything that actually confirms that. I don't think this has a clear answer right now.

**Comment by Shepherdwhen** [comment]
> > > Unaligned roles are not meant to block any win conditions
> > 
> > 
> > So you're saying that UM needn't be targeted by solo or opposite?
> 
> This is how I'd currently run the game. But I don't think there's anything that actually confirms that. I don't think this has a clear answer right now.

If this becomes the case it should be clarified in the wincons I guess

**Comment by McTsts** [comment]
I think UA are better off with how I said it:

- against FP it's an advantage if they have to be enchanted as it delays the end of the game
- against a Devil it's probably a disadvantage as they'd be more likely to be killed
- same for Pyro
- same for WWW
- same for Vamp - they'd be more likely to be turned (which would decrease points) or killed

**Comment by Shepherdwhen** [comment]
So any killing form of solo + vampire should win with UM alive since their targeting is best spent elsewhere, but anything else should target them, I was thinking because it's slightly easier for FP and Shepherd if they don't need UM to be targeted if UM win with them when the UM lives to endgame

**Comment by McTsts** [comment]
I think since for most roles it's easier to not have to target Unaligned, we should just have it be a general thing - any team can win with any amount of Unaligned alive in any state

**Comment by Shepherdwhen** [comment]
I agree with that so not much change just a general statement of that

**Comment by MrTurtleJr** [comment]
I don't think there should be a uniform set of rules how UM wins with a solo.

GWW/WWW, Vampire, Devil/Archa & Pyro should win with an UM alive and their regular role (i.e. not Undead). In the case of the Devil it shouldn't matter whether they are Soulless or regular UM.
For IK, FP or Shepherd they need to be targeted, but can win alongside them.

**Comment by McTsts** [comment]
We can discuss this further but I'll do a temporary fix and keep this open.
