### ISSUE TITLE
RH Lone Wolf

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#179]
should RH remove Lone Wolf's kill?

**Comment by MrTurtleJr** [comment]
Yes, I don't see why not. It shouldn't interfere with the wolfpack's attack, as they didn't attack the RH. The only edge case I see is what happens when Lone Wolf joins the wolfpack after having lost their kill to RH. Do they lose their vote on the poll?

**Comment by McTsts** [comment]
> Yes, I don't see why not. It shouldn't interfere with the wolfpack attack, as they didn't attack the RH. The only edge case I see is what happens when Lone Wolf joins the wolfpack after having lost their kill to RH. Do they lose their vote on the poll?

Oooh, didn't even think about that! But, yeah, losing their vote for the night makes sense.

**Comment by Shepherdwhen** [comment]
It makes it less anti-wolf in games that include lone wolves.

**Comment by McTsts** [comment]
> It makes it less anti-wolf in games that include lone wolves.

Not really. The current version has no consequences if a LW kills a RH.

**Comment by Shepherdwhen** [comment]
Oh i thought Wolf pack kill was disabled if a RH was killed by LW currently

**Comment by McTsts** [comment]
> Oh i thought Wolf pack kill was disabled if a RH was killed by LW currently

Nope. Right now RH wins if killed by any lycan, but it only has consequences if killed via the wolfpack kill.
