### ISSUE TITLE
Bartender inconsistency/change?

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#18]
in bot descrioption:
"If the Bartender loses their role, they lose their ability to anonymously talk in the tavern chat." is missing

In rolebook:
"The Bartender can not exist in any game with less than 30 players." is missing

maybe remove the "The Bartender can not exist in any game with less than 30 players." since we use it in games with less than 30 players.

**Comment by McTsts** [comment]
yeah I think we can remove the 30 player thing

**Comment by venomousbirds** [comment]
first thing should definitely be added, but the 30 player thing isn't too relevant and bartender could be used in a game with less than 30 players
