### ISSUE TITLE
Flute Apprentice

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#19]
FPA is listed as a proper role. I'm fine with this but the role book lists it as a limited role.

**Comment by venomousbirds** [comment]
I'm not sure if we've used it in an in-season game, if not it might be best to keep it limited because I'm not sure it's tested well enough yet

**Comment by McTsts** [comment]
There's not really much to test - it doesn't do much

**Comment by venomousbirds** [comment]
Keep it as a limited role for now then, don't think we really need it at the moment?
