### ISSUE TITLE
Devil Should say it can't wager itself

### ISSUE THREAD

**Issue by Shepherdwhen** [McTsts/Werewolves-Roles#191]
Currently the DM doesn't say this as brought up by Ts in a mini wolves game, It should say the devil is soulless or can't wager itself

**Comment by voidmist** [comment]
can the devil wager a demon?

**Comment by McTsts** [comment]
> can the devil wager a demon?

The Demon is listed as soulless so the Devil can't wager them. I think we just forgot to put it into the Devil description that it's also soulless.
