### ISSUE TITLE
Pack Tanner nerf

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#194]
[VIP]  pack tanner is probably too strong even with just 1 disguise - possible solution: it can only tan players not in the pack

**Comment by Mjnstag** [comment]
idk if log is on the github but
> pack tanner can be weakened by not allowing one person to be tanned twice in a row

-log

**Comment by Shepherdwhen** [comment]
What about pack tanner can only tan people in the pack as citizen and people outside the pack as whatever they want

**Comment by McTsts** [comment]
> idk if log is on the github but
> 
> > pack tanner can be weakened by not allowing one person to be tanned twice in a row
> 
> -log

this is more of a nerf that makes it more luck dependent
