### ISSUE TITLE
Mayor & Child interaction

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#2]
How does a Mayor double lynch affect Child?

**Comment by venomousbirds** [comment]
Yes, according to the current description it does
"instead of an extra vote the Mayor chooses each day whether the top one or the top two players being voted on will be lynched."
The top one or top two, regardless of the amount of lynches

**Comment by McTsts** [comment]
Let's rephrase this issue as *is that intentional?* then

**Comment by venomousbirds** [comment]
Yeah, it's fitting and very interesting. I think we should keep it
