### ISSUE TITLE
"immediately narrated"

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#20]
maybe somewhere (or in every role?) add that it means that "as soon as hosts see it"

e.a. when something happens to a bard

**Comment by McTsts** [comment]
hm is that necessary?

**Comment by Mjnstag** [comment]
probably not tbh

**Comment by venomousbirds** [comment]
Yeah not really neccesary, we can always just say it if someone asks about it

**Comment by McTsts** [comment]
yeah I think it's not worth mentioning it, closing this
