### ISSUE TITLE
Child rolebook/bot inconsistency

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#21]
• (Details) "This is useful in scenarios where the werewolves want to lynch an Executioner, who can avoid one lynch. " not in rolebook
• (details): "If the Child loses their role, there will be two lynches once the original Child dies, not when they lose their role." not in bot description

**Comment by McTsts** [comment]
Do we want that?
> "If the Child loses their role, there will be two lynches once the original Child dies, not when they lose their role."

**Comment by venomousbirds** [comment]
Leave out the executioner details, doesn't seem too relevant.

 I don't think Child should be like Wolf's Cub, seems a bit harsh on town. But double lynches never go as planned so we could maybe host a game with and a game without it to see what works best

**Comment by McTsts** [comment]
I don't think this is something we should do. Child is a limited role and properly testing this detail probably isn't really worth it.

**Comment by venomousbirds** [comment]
Child is limited? I completely forgot

**Comment by McTsts** [comment]
Just checked, turns out it isn't?

**Comment by McTsts** [comment]
Child (originally Town Cub) and Acrobat were just mini wolf roles, didn't know Child had actually been accepted. Either way I think specifically testing for this difference doesn't really work. The game is too volatile to get useful results in a reasonable amount of games.

**Comment by venomousbirds** [comment]
Child has been used in a few in-season games already. It's fine as is so adding the Wolf's Cub-like thing isn't necceary

**Comment by McTsts** [comment]
Alright! Since that's already what we have I'm closing this.
