### ISSUE TITLE
Wager Redirection

### ISSUE THREAD

**Issue by Shepherdwhen** [McTsts/Werewolves-Roles#224]
If the wager of an enchanted devil is redirected onto a member of the hell team or even ex wager recipient who sold a soul, what happens? because wager can't be sent to soulless so what would happen?

**Comment by McTsts** [comment]
Maybe the roles that use Whispers should be immune to redirection. (so Devil, Grandma, Stalker, Shepherd) - This would help redirectors with staying hidden

**Comment by MrTurtleJr** [comment]
I like the idea that Whispers shouldn't be affected by the FPA's redirect ability.
