### ISSUE TITLE
Claimspace Name

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#230]
Since it's a role in the book it should probably get a real name (like town cub)

**Comment by Shepherdwhen** [comment]
What does the role actually do?

**Comment by McTsts** [comment]
> What does the role actually do?

Adds a fake role to the role list that only the claimspace knows

**Comment by Shepherdwhen** [comment]
What about Undeployed Townsfolk? It lost it's job sort of I guess

**Comment by McTsts** [comment]
This is one of the most unpopular roles, so I'll add this to #325 instead.
