### ISSUE TITLE
Crowd Seeker Checks

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#231]
Can they check the same player several times? Very unclear now

**Comment by Shepherdwhen** [comment]
It says up to 3, this I guess originally meant that it could only do one guess if it wanted, but could mean for example

Ts => Wolf Cub
Ts => Alpha wolf
Vera => Pyromancer
Is allowed which I see little issue with

**Comment by McTsts** [comment]
> It says up to 3, this I guess originally meant that it could only do one guess if it wanted, but could mean for example
> 
> Ts => Wolf Cub
> Ts => Alpha wolf
> Vera => Pyromancer
> Is allowed which I see little issue with

Imo it should be allowed but rn its just very unclear

**Comment by Shepherdwhen** [comment]
So we agree it should be allowed, depends on others though

**Comment by Mjnstag** [comment]
yea i think the same, as long as hosts tell the results at the same time for all of them
