### ISSUE TITLE
Bartender encryption 

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#239]
The bartender is technically not banned from using asymmetric encryption (and technically other whisper roles can also use it)

**Comment by Mjnstag** [comment]
we could argue that this is against our rule of talking English so gm's can follow the flows of information. In that case it wouldnt be allowed

**Comment by McTsts** [comment]
> we could argue that this is against our rule of talking English so gm's/hosts can follow the flows of information. In that case it wouldnt be allowed

Is that rule actually mentioned anywhere?

**Comment by McTsts** [comment]
Might be something we should add to #rules

**Comment by Mjnstag** [comment]
yea, good idea. 
https://discord.com/channels/584765921332297775/584794229247574016/620948014223065111
example of marhjo asking people to only to speak english

**Comment by venomousbirds** [comment]
I thought it was mentioned in #rules but apparently not, weird

**Comment by Mjnstag** [comment]
yea, i thouhgt it was mentioned there but apparently not

**Comment by venomousbirds** [comment]
Yes, grandma and stalker are also whispers roles

**Comment by venomousbirds** [comment]
i think we might want to re-do rules because rn it's a bunch of text that's a bit hard to read (for me at least)

**Comment by McTsts** [comment]
> would this influence #275 as that one technically isnt english as well?

it technically _is_ english

**Comment by McTsts** [comment]
> i think we might want to re-do rules because rn it's a bunch of text that's a bit hard to read (for me at least)

Yeah, that's probably a good idea. I'll close this one as it should be covered by your #305
