### ISSUE TITLE
Macho: lots of differences

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#24]
both the rolebook and in the bot have sentences that are not in the other

**Comment by McTsts** [comment]
Seems like only "If the Macho is attacked during the day, they will survive until the end of that day." is missing from here

**Comment by Mjnstag** [comment]
", and will be able to attempt to spread the word about their killer." not in rolebook
"If the Macho is lynched, they will die as usual. " not in bot
" Only the Macho is informed who attacked them, but they can share this information." not in bot desccripition
might be more but i found these so far

**Comment by McTsts** [comment]
missing sentences from role book dont really matter now
"If the Macho is lynched, they will die as usual." is the last sentence for bot
"The Macho will know who attacked them, and it is up to them to decide whether they want to share this information or not." (bot) is close enough

**Comment by Mjnstag** [comment]
👍
