### ISSUE TITLE
Executioner x Ranger

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#245]
The executioners lynches another player. Technically that's a "direct Lynch" (it isn't meant to be)

**Comment by Shepherdwhen** [comment]
I thought executioner killed their target and survived the lynch? Maybe that solves it's issues

**Comment by McTsts** [comment]
> I thought executioner killed their target and survived the lynch? Maybe that solves it's issues

The executioner lynches (not "attacks") their target
