### ISSUE TITLE
Suggestion: Trickster x Infected Wolf

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#251]
An infected trickster turns into a trickster wolf instead

**Comment by Mjnstag** [comment]
would trickster wolf have negative votes on both public/private polls?

**Comment by McTsts** [comment]
> would trickster wolf have negative votes on both public/private polls?

Probably

**Comment by Mjnstag** [comment]
So that would mean that if the trickster wolf cannot kill anymore using the wolfpack poll if they are the last one alive?

**Comment by Shepherdwhen** [comment]
Why would it ever vote on wolfpack poll except in WWW situations where it is wolf + TW + WWW and pack want to kill WWW

**Comment by Shepherdwhen** [comment]
If it has -1 private

**Comment by McTsts** [comment]
> So that would mean that if the trickster wolf cannot kill anymore using the wolfpack poll if they are the last one alive?

Seems fair for balancing.

**Comment by McTsts** [comment]
> Why would it ever vote on wolfpack poll except in WWW situations where it is wolf + TW + WWW and pack want to kill WWW

last minute changes, same as current AW really

**Comment by Mjnstag** [comment]
thats a good point for when members are asleep during phase change

**Comment by Shepherdwhen** [comment]
I think it works, do we do this with executioner and stalker too?

**Comment by McTsts** [comment]
No, I just suggested it as I thought it'd fit the "Trickster" role. Also both Stalker/Executioner Wolf would be a definite advantage. Trickster Wolf is not necessarily.
