### ISSUE TITLE
Executioner x Guardian

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#253]
What happens if an Executioner lynches somebody protected by the Guardian (those players can't be lynched). Probably they don't die? Does the Executioner just not lynch anyone then?

**Comment by Mjnstag** [comment]
ig it will fail since they cannot be lynched. Would the exe be revealed in that case?  Since other roles wont be revealed when an attack fails

**Comment by McTsts** [comment]
> ig it will fail since they cannot be lynched. Would the exe be revealed in that case? Since other roles wont be revealed when an attack fails

I think it should probably one of these two:
- Executioner is lynched
- Executioner is revealed, but doesn't lynch anyone

Because having the power be partially successful without reveal seems a bit weird to me

**Comment by Mjnstag** [comment]
probably one of those yea
