### ISSUE TITLE
Suggestion: Alpha Wolf

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#254]
new or additional power for it: Overwrite the wolfpack's kill target once in the game

**Comment by Shepherdwhen** [comment]
So like how RK Or RW/CW works except it chooses a different target instead of cancelling?

Maybe it can choose to reveal itself to the pack

I see it as more useful in a WWW situation if it is it's only power
Useful in a GWW situation if it is additional

Useful in any scenario when last minute info is found and the pack is not online to change but AW is

**Comment by McTsts** [comment]
Yeah, I think it's overall better both for the last minute and for the WWW situation. I think it could work well as the AW's only power. It keeps the idea of the role but makes it better. The reveal thing seems like an interesting option, possibly could be handelled the same way as RK (optional). Additionally, it adds a bit of a layer of strategy to the claim as the WWW will probably prioritize stronger wolf roles so you might not want to immediately claim it.

**Comment by Shepherdwhen** [comment]
> I think it could work well as the AW's only power. It keeps the idea of the role but makes it better.

If we changed it would we have something reuse the alpha wolf's power as it is a confirmable wolf role and it works as a less powerful version of the new alpha

> Additionally, it adds a bit of a layer of strategy to the claim as the WWW will probably prioritize stronger wolf roles so you might not want to immediately claim it.

That is 100% something a WWW would kill first it doesn't want to be in a 1 v 1 with it

**Comment by McTsts** [comment]
> > I think it could work well as the AW's only power. It keeps the idea of the role but makes it better.
> 
> If we changed it would we have something reuse the alpha wolf's power as it is a confirmable wolf role and it works as a less powerful version of the new alpha
> 
> > Additionally, it adds a bit of a layer of strategy to the claim as the WWW will probably prioritize stronger wolf roles so you might not want to immediately claim it.
> 
> That is 100% something a WWW would kill first it doesn't want to be in a 1 v 1 with it

The thing is I just really don't think the current Alpha Wolf is worth keeping.

**Comment by Shepherdwhen** [comment]
> > > I think it could work well as the AW's only power. It keeps the idea of the role but makes it better.
> > 
> > 
> > If we changed it would we have something reuse the alpha wolf's power as it is a confirmable wolf role and it works as a less powerful version of the new alpha
> > > Additionally, it adds a bit of a layer of strategy to the claim as the WWW will probably prioritize stronger wolf roles so you might not want to immediately claim it.
> > 
> > 
> > That is 100% something a WWW would kill first it doesn't want to be in a 1 v 1 with it
> 
> The thing is I just really don't think the current Alpha Wolf is worth keeping.

Fair it is kinda useless but works as a good joke role

**Comment by McTsts** [comment]
> > > > I think it could work well as the AW's only power. It keeps the idea of the role but makes it better.
> > > 
> > > 
> > > If we changed it would we have something reuse the alpha wolf's power as it is a confirmable wolf role and it works as a less powerful version of the new alpha
> > > > Additionally, it adds a bit of a layer of strategy to the claim as the WWW will probably prioritize stronger wolf roles so you might not want to immediately claim it.
> > > 
> > > 
> > > That is 100% something a WWW would kill first it doesn't want to be in a 1 v 1 with it
> > 
> > 
> > The thing is I just really don't think the current Alpha Wolf is worth keeping.
> 
> Fair it is kinda useless but works as a good joke role

We can just add a wolf internal wolf mayor election instead 
![image](https://user-images.githubusercontent.com/24660095/117214423-15435f00-adfd-11eb-9e07-6f112db91252.png)

**Comment by McTsts** [comment]
thats a weird joy emoji but ok

**Comment by Shepherdwhen** [comment]
> We can just add a wolf internal wolf mayor election instead

Internal wolfpack reporter for finding what wolfpack roles died and internal wolfpack guardian to protect a wolfpack member form wolfpack kill

**Comment by McTsts** [comment]
> > We can just add a wolf internal wolf mayor election instead
> 
> Internal wolfpack reporter for finding what wolfpack roles died and internal wolfpack guardian to protect a wolfpack member form wolfpack kill

Internal wolfpack bartender that gets the @Wolf Bartender role and can anonymously talk in #wolf_tavern

**Comment by Shepherdwhen** [comment]
> > > We can just add a wolf internal wolf mayor election instead
> > 
> > 
> > Internal wolfpack reporter for finding what wolfpack roles died and internal wolfpack guardian to protect a wolfpack member form wolfpack kill
> 
> Internal wolfpack bartender that gets the @wolf Bartender role and can anonymously talk in #wolf_tavern

Internal Wolf elected Dog role that can become wolf mayor, wolf reporter or wolf guardian

**Comment by McTsts** [comment]
10/10 idea
