### ISSUE TITLE
Suggestion: Acrobat escapes

### ISSUE THREAD

**Issue by Shepherdwhen** [McTsts/Werewolves-Roles#261]
Someone else brought up the idea once during a minis  game that acrobat should escape one non wolfpack kill (Lone wolf, TK, SK) or escape two wolfpack kills, So I am bringing it up as an issue now.

**Comment by venomousbirds** [comment]
I don't think that would work well, just keep it at 2 wolfpack kills

**Comment by McTsts** [comment]
I think the suggestion was that Acrobat can escape wolf attacks twice (like currently), with the additional option to escape any non-wolf attack (Devil, Assassin, etc) once (if neither of the wolf escapes have been used)

**Comment by Shepherdwhen** [comment]
> I think the suggestion was that Acrobat can escape wolf attacks twice (like currently), with the additional option to escape any non-wolf attack (Devil, Assassin, etc) once (if neither of the wolf escapes have been used)

Yeah it is that 😂

**Comment by McTsts** [comment]
omg it somehow didn't occur to me that I can just use unicode emojis here 😂

**Comment by Shepherdwhen** [comment]
> omg it somehow didn't occur to me that I can just use unicode emojis here 😂

Amazing lol

**Comment by McTsts** [comment]
I think we're probably better off with having Idiot cover this functionality.
