### ISSUE TITLE
Devil x Macho

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#262]
If a Devil's Wager Recipient uses the Devil's Wager Attack to kill a Macho the Devil's identity is revealed. Is this intentional?

**Comment by venomousbirds** [comment]
Probably accidental, but I think for consistency it should stay that way?

**Comment by McTsts** [comment]
> Probably accidental, but I think for consistency it should stay that way?

It's kinda problematic, but I think it _probably_ should stay like this, yeah. Don't think there's anything we can do about this really.
