### ISSUE TITLE
CC x Lone Warlock / Pack Tanner

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#264]
If a Lone Warlock or Pack Tanner is chosen as the attacker of a wolfpack attack a Cursed Civilian wouldn't turn into a wolf.

**Comment by venomousbirds** [comment]
I think LW should turn into a regular wolf once they join the pack. Maybe make pack tanner an exception because it'd be weird if CC didn't turn into a wolf

**Comment by McTsts** [comment]
> I think LW should turn into a regular wolf once they join the pack. Maybe make pack tanner an exception because it'd be weird if CC didn't turn into a wolf

The easiest solution would probably to just say that CC turns if attacked by a lycan or a werewolf.
