### ISSUE TITLE
FA Reveal

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#265]
Why is FA promotion revealed? Wouldn't it be better for claimspace to not reveal it?

**Comment by venomousbirds** [comment]
I don't understand why it's revealed either, it might be better to not reveal it

**Comment by McTsts** [comment]
I definitely think I'd be more likely to use this role without the announcement, just because then it's more claimable. (Right now it hasn't been used in 35 games so I guess the current version isn't very popular)
It's already town-sided enough anyway I think. I'm gonna make a PR to change it
