### ISSUE TITLE
Stalker/Grandma Code

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#275]
Can Stalker/Grandma create a code that a target learns, and can then use to communicate with the stalker via public channels?

**Comment by Shepherdwhen** [comment]
Would it be necessary?

Because everything in the chats is deleted anyway right

**Comment by venomousbirds** [comment]
Who would come up with that? I've never seen people talk about it. I guess It's not allowed but I don't think anyone will ever use it anyways

**Comment by McTsts** [comment]
Coming up with a code is not particularly difficult. You could just assign a number to each player (but not in the order of $list) and then the person that knows the code can say "7 claims Runner" in town square

**Comment by cryptidjayden** [comment]
i don't see people using it.
