### ISSUE TITLE
[Reaper] Pyro Ignite

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#285]
Can the Reaper choose to pyro ignite and if yes what happens?

**Comment by McTsts** [comment]
Maybe all abilities involving effects in any way are replaced with sleepless? So Reaper would choose between turning somebody sleepless or attacking everyone that's sleepless.

**Comment by venomousbirds** [comment]
I think that should be possible, either killing all powdered or turning all powdered sleepless?

**Comment by Shepherdwhen** [comment]
But then flute players basically turns a player sleepless

**Comment by McTsts** [comment]
In the current version if the Reaper gains the FP power they just directly turn people sleepless.
