### ISSUE TITLE
[Reaper] Oracle

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#287]
The Oracle (also Exorcist, possibly others) has the special limitation of only using the ability once _per player_, similarly Pack Tanner will _probably_ have a limitation of not the same player in a row. Maybe figure out a phrasing so that these limits are irrelevant for the Reaper?

**Comment by venomousbirds** [comment]
Have it fail if they target a player that the pack tanner has tanned the night before/the oracle/exorcist has checked before in the game? A slightly nerf on the Reaper side but with this few roles it should be all right

**Comment by McTsts** [comment]
Alright, I'll think about how I can rephrase the limitation thing
