### ISSUE TITLE
[Reaper] Cult Leader

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#288]
This one seems extra problematic. Relates to #286

**Comment by venomousbirds** [comment]
The cult has been disbanded at that point, so a kill shouldn't be possible

**Comment by Shepherdwhen** [comment]
> The cult has been disbanded at that point, so a kill shouldn't be possible

Just mentioned this on #286

**Comment by McTsts** [comment]
> The cult has been disbanded at that point, so a kill shouldn't be possible

You're right. Also resolved by your fix for groups anyway.
