### ISSUE TITLE
[Reaper] Mad Scientist

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#289]
idk. Relates to #286

**Comment by venomousbirds** [comment]
What do you mean?

**Comment by McTsts** [comment]
Does anything happen? Are they told the targets and can pick one? I guess MS would be classified as a group role as well?

**Comment by venomousbirds** [comment]
Choosing between one of the targets seems like a good solution

**Comment by McTsts** [comment]
Actually, that'd be how it currently is
