### ISSUE TITLE
Grandma: different sentence in basics

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#29]
Rolebook: "The next day, these selected players have a public voting value of 0, and the Grandma will get the same amount of votes as people they selected."

Bot: "The next day, these selected players can’t vote. That day, Grandma will get the same amount of votes as people they selected."

**Comment by venomousbirds** [comment]
Public voting value seems more accurate, because they can still vote

**Comment by McTsts** [comment]
While the role book one seems better this is Basics not Details. Details clarifies that they can still vote but it wont be counted. I'v made a small change to it over at #79 to clarify the Mayor vote cant be stolen, but I dont think we should change basics.
