### ISSUE TITLE
[Reaper] Grandma, Stalker

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#293]
I think these should have consequences on the next day, this conflicts with my suggestion for #290

**Comment by venomousbirds** [comment]
These are specifically mentioned anyways

**Comment by McTsts** [comment]
Maybe the next day consequences only happen if the reaper lives (which they wouldn't be the case for #290)

**Comment by venomousbirds** [comment]
I don't understand what you mean

**Comment by McTsts** [comment]
So basically if an action has consequences on the next day (Stalker, Child, Grandma) they _only_ happen if the Reaper is still alive - The Reaper can't be alive for Child consequences so they will never happen, but those like Stalker/Grandma _can_ happen.
