### ISSUE TITLE
[Reaper] Medium

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#294]
another one with a delayed consequence

**Comment by Shepherdwhen** [comment]
The reaper maybe just can see the result of the last question asked by the medium

**Comment by venomousbirds** [comment]
Probably the same as #290

**Comment by McTsts** [comment]
> The reaper maybe just can see the result of the last question asked by the medium

I kinda want general solutions not things like that.

**Comment by MrTurtleJr** [comment]
Oh, I just read the new Reaper suggestion and my comment is no longer relevant.

**Comment by McTsts** [comment]
With the current way it's formulated the Reaper would be able to ask a question. I don't think this is particularly useful, but I think it's probably fine.
