### ISSUE TITLE
[Reaper] Psychopath?

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#297]
nothing?

**Comment by venomousbirds** [comment]
Nothing

**Comment by McTsts** [comment]
Maybe we should put something then that the Reaper wont gain any info the dead people had (groups, lists, etc)

**Comment by McTsts** [comment]
not sure if it's necessary

**Comment by venomousbirds** [comment]
Oh the psychopath does have a disguise, so that should be applied. Other than that, nothing
