### ISSUE TITLE
[Reaper] Sneaking Wolf, White Werewolf

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#298]
Does the Reaper gain the disguise if a role has one? Maybe they could choose between all the disguises they have "collected"? idk

**Comment by venomousbirds** [comment]
Gain the disguise

**Comment by McTsts** [comment]
> Gain the disguise

The thing is if we don't do my suggestion it'd be bad for the Reaper

**Comment by venomousbirds** [comment]
What do you mean with "collected" disguises?

**Comment by McTsts** [comment]
Basically every time the Reaper gains a disguise it's added to a collection of disguises and the Reaper can choose any of them at any time.

**Comment by McTsts** [comment]
But I think it's probably preferable to just have no effect with Sneaking Wolf & WWW tbh

**Comment by venomousbirds** [comment]
WWW could be useful if reaper wants wolves to find them

**Comment by McTsts** [comment]
Possible idea:
- if Reaper uses a power to change role it applies a strong disguise (so with Dog they could choose between Citizen/CC/Wolf strong disguise)
- if somebody with a disguise dies the Reaper gets it as a weak disguise for the night

(that way in the rare situation that they somehow get a role changing power it would not be overwritten)
