### ISSUE TITLE
Infected Wolf redirections

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#302]
Should the infected wolf's power be able to be redirected and if they are redirected onto a wolfpack member are they turned into a wolf?

**Comment by Mjnstag** [comment]
maybe the redirecting should work, but not the turning a wolfpack member into a wolf since that might be hard to balance for that case?

**Comment by Shepherdwhen** [comment]
It could significantly weaken the wolf team if it hit an important role, equally it could strengthen the wolf team if it hit www. This is probably too unpredictable of outcomes and could unbalance a balanced setup
