### ISSUE TITLE
Vampire x (Undead x Cupid) x Exorcist

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#303]
If an Exorcist exorcises an Undead that is a Cupid's lover, a Vampire would be able to demonize the Undead again which could be used to identify traitors. This is unintentional.

**Comment by Shepherdwhen** [comment]
Does an undead with a Cupid have a separate wincon than other undead?

**Comment by Shepherdwhen** [comment]
What I meant is, that wincon of solo why does that make them not undead, their role is still undead just not their wincon

**Comment by McTsts** [comment]
> Does an undead with a Cupid have a separate wincon than other undead?

Undead x Cupid win condition is to kill everyone, however usually an Undead with a lover would admit it to the Vampire and would try to get the Cupid demonized. If the Cupid becomes Undead the Cupid's win conditions changes from Townsfolk to Underworld, resulting in the couples win condition also being Underworld.
