### ISSUE TITLE
Barber: different word choices/punctuation

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#31]
• (details) "After Day 1, " in bot vs "After the first day, " in rolebook
• (details) "The Barber also receives the choice" in bot vs "The Barber also chooses" in rolebook
• (details) "is announced, otherwise neither is." in bot vs "announced; otherwise, neither is." in rolebook

**Comment by venomousbirds** [comment]
Should be after Day 1, because "after the first day" can easily be misinterpreted as "after day 0"

chooses is probably better because it sounds more straight-to-the-point

i think it's ; but i'm not that good at english

**Comment by McTsts** [comment]
"First day" is equal to "Day 1" according to https://github.com/McTsts/Werewolves-Roles/blob/main/_rules/first%20day/basics but changing it to Day 1 makes sense. 

Pretty sure it's "," - the second sentence isn't really a sentence that makes sense on its own

**Comment by venomousbirds** [comment]
Commenting on the First day/Day 1 discussion directly because I have unfortunaly been the victim of being barberkilled d1 and I think it should be more clear

**Comment by McTsts** [comment]
Yes making it more clear is good. But getting Barber killed D1 is a GM mistake.
