### ISSUE TITLE
Lone Wolf suggestion

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#313]
[RD]
> i thought lone wolf was limited to one kill outside of wolf pack btw
> was that changed or not
> if not should be cuz lone wolf not joining wolves mean they're winning
> so with unlimited kill it snowballs

- 3let

**Comment by McTsts** [comment]
I don't think this should be done.

**Comment by venomousbirds** [comment]
Lone wolf has always been like this and I don't think it should change to only 1 kill. Lone wolf has to be careful already, they won't kill randomly because they feel like it. Limiting it to 1 kill is a bad decision

**Comment by McTsts** [comment]
It also kind of forces town to lynch D1, which I think is good.
