### ISSUE TITLE
Role Idea: Cat

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#314]
[RD]

> Cat | Unaligned Align
> Basics
> During day one, the Cat will immediately become the opposite role Dog choses for the rest of the game. If the Dog chooses Town Crier,  Cat will turn into Wolf; Cursed Civilian will turn Cat into Psychopath with Dog's in the list; and Wolf will turn Cat into Town Crier.
> 
> Details
> Being chosen a role is an immediate ability. If the Dog hasn’t chosen a role before the night ends or there is no Dog  in the game, the Cat will be given the role of Survivor. A Cat can't be in the same game with more than 1 Dog.

- steil

**Comment by venomousbirds** [comment]
I think it's interesting, more UA isn't a bad thing (we currently don't have a lot to choose from) and this mechanic is cool. I don't think Cat should be a survivor because survivor was removed, but idk what else it could turn into

**Comment by McTsts** [comment]
I think the Survivor thing is fine, it should most likely never/only very rarely happen

**Comment by Shepherdwhen** [comment]
Could turn into a lone wolf if the dog fails to pick in time

**Comment by McTsts** [comment]
This could be interesting because you can't claim Dog turned Cursed Civ if the Cat is the opposite of you and you actually chose Wolf.
