### ISSUE TITLE
Suggestion: Despot angel-like vote thing

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#318]
[S6G5]
Make it so that the Despot starts out with -1 vote like the Angel?

**Comment by McTsts** [comment]
This could also be somewhat bad, in S6G5B this Angel thing was used to confirm an Angel. I'm not sure if it's a good idea to make both Angel and Despot confirmable. Clever players could organize a thing where everyone votes for themselves on Mayor to figure out the Despot and Angel.

**Comment by venomousbirds** [comment]
Despot can win very easily now, so something to make it harder for them would be nice. Maybe not a vote change, because it'd be similar to Angel, but something else? Can't think of anything right now

**Comment by McTsts** [comment]
The thing is the angel thing makes angel confirmable which I don't think is great.

**Comment by Shepherdwhen** [comment]
Suggestion, instead of removing votes from those who gave despot mayor the despot just makes it so there will be no mayor poll the next day

This makes it harder due to the fact that town would have to go two days without mayor to give a despot the win which means two days they could have had reporter are gone, and it's not conformable as it happens after despot ascends

**Comment by kruthers** [comment]
> Suggestion, instead of removing votes from those who gave despot mayor the despot just makes it so there will be no mayor poll the next day
> 
> This makes it harder due to the fact that town would have to go two days without mayor to give a despot the win which means two days they could have had reporter are gone, and it's not conformable as it happens after despot ascends

I agree with doing this to make it so it cant get confirmed, we should also keep it so that anyone who votes on them still loses there public votes though.

**Comment by Shepherdwhen** [comment]
> > Suggestion, instead of removing votes from those who gave despot mayor the despot just makes it so there will be no mayor poll the next day
> > This makes it harder due to the fact that town would have to go two days without mayor to give a despot the win which means two days they could have had reporter are gone, and it's not conformable as it happens after despot ascends
> 
> I agree with doing this to make it so it cant get confirmed, we should also keep it so that anyone who votes on them still loses there public votes though.

That seems fair, a punishment for being the one to give despot the win alongside a general punishment for despot winning

**Comment by Mjnstag** [comment]
> Suggestion, instead of removing votes from those who gave despot mayor the despot just makes it so there will be no mayor poll the next day

maybe better if it affect all election polls and not only mayor?

**Comment by Shepherdwhen** [comment]
> > Suggestion, instead of removing votes from those who gave despot mayor the despot just makes it so there will be no mayor poll the next day
> 
> maybe better if it affect all election polls and not only mayor?

as in all polls for the rest of the game? without mayor you can't have reporter poll or guardian poll and when despot ascends you need to elect a new mayor. so idk what you mean by this, if it affected the next days poll it would be affecting the mayor poll

**Comment by Mjnstag** [comment]
wait nvm am stupid

**Comment by McTsts** [comment]
> Suggestion, instead of removing votes from those who gave despot mayor the despot just makes it so there will be no mayor poll the next day
> 
> This makes it harder due to the fact that town would have to go two days without mayor to give a despot the win which means two days they could have had reporter are gone, and it's not conformable as it happens after despot ascends

Yeah, that could work.

**Comment by venomousbirds** [comment]
> Suggestion, instead of removing votes from those who gave despot mayor the despot just makes it so there will be no mayor poll the next day
> 
> This makes it harder due to the fact that town would have to go two days without mayor to give a despot the win which means two days they could have had reporter are gone, and it's not conformable as it happens after despot ascends

Definitely a very interesting suggestion, and it could work. It also doesn't confirm Despot, so that's a plus
