### ISSUE TITLE
Disguised fox: missing sentence in bot

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#32]
• (details) "Choosing a disguise is an end-day ability." not in bot description

**Comment by McTsts** [comment]
Why would it be an end-day ability?

**Comment by venomousbirds** [comment]
Disguising is generally immediate so DF should have an immediate disguise

**Comment by McTsts** [comment]
Actually, all these fox things should be end effects even if it's a bit odd
