### ISSUE TITLE
Executioner targetting

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#320]
[S6G5]
Can the Executioner still target players once they've used their power? This is relevant in combination with Bards or Reaper.

**Comment by venomousbirds** [comment]
They can't, they've used their powers already and lost their ability to target because it's not neccesary anymore

**Comment by McTsts** [comment]
> They can't, they've used their powers already and lost their ability to target because it's not neccesary anymore

It is necessary for Bard and Reaper

**Comment by venomousbirds** [comment]
well, it lost its target, so it cant target anymore. so targetting bard is impossible and reaper can't do anything with exe anymore

**Comment by McTsts** [comment]
According to Stein in V2G4 this is still allowed.
