### ISSUE TITLE
Reaper buff

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#321]
[S6G5]
Make it so that turning people sleepless is a separate power, unrelated to using the powers of the dead.

**Comment by venomousbirds** [comment]
Turning 1 person sleepless at night as a standard will definitely help the role. Also putting it in role lists where most deaths give powers will help the role but that's not relevant to this issue

**Comment by McTsts** [comment]
> Turning 1 person sleepless at night as a standard will definitely help the role. Also putting it in role lists where most deaths give powers will help the role but that's not relevant to this issue

The current Reaper _could_ work, but it'd be very difficult to make a role list where it actually works, so I think with this change it could work a lot more easily in role lists.
