### ISSUE TITLE
Suggestion: New Role Idea [Golem]

### ISSUE THREAD

**Issue by 12Metatron** [McTsts/Werewolves-Roles#324]
How it works is basically just despot but for guardian.

Despot is not a very fun role to play because they win too fast and are knocked out of the game very early. And if they miss their first chance then they have to wait a long time for another one, during which there's not much for them to do. In this role they would have more things to do, more ways to manipulate the game and be involved, and get to stay in the game longer. #

Ideas for consequence: for it to be a worthwhile consequence late into the game, i guess it could be that it uses guardian powers on a random voter or a chosen voter like angel (could be either, flexible on that part)

**Comment by Shepherdwhen** [comment]
issue is there have been games which have never even reached the guardian stage as wolves never want reporter unless they are protected or a wolf then they never survive long enough to reach guardian election

**Comment by 12Metatron** [comment]
yeah so thats where the strategy comes in, they have to be involved in the game in order to achieve it

**Comment by McTsts** [comment]
Sorry, I don't think is something we want to add.

**Comment by ThomasRubycrust** [comment]
Hm, actually, couldn't this be interesting if buffed? Give the Golem the power to protect one player each night, which makes it so it has a real chance of getting the game to reach the Guardian stage and it would also then be a more town-sided role (unless the wolves immediately get Mayor D1, but that's fair imo). It could be good for games that don't have roles like Runner/Macho/Hooker.

Something additional to balance it could be that it learns if their defense was used and if so, they can't defend in the next night.

**Comment by ThomasRubycrust** [comment]
@12Metatron I created a role prototype based on your idea.
