### ISSUE TITLE
FA x Undead TI

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#335]
If a TI turns undead/wolf and then dies can the FA take their place?

edge case sheet:
> The Apprentice changes to FT if the FT turns Undead

(sheet would suggest FA changes on role change which shouldn't be done)

**Comment by Shepherdwhen** [comment]
I believe the role was changed to fix this but sheet wan't updated so it's a simple sheet update job

**Comment by McTsts** [comment]
> I believe the role was changed to fix this but sheet wan't updated so it's a simple sheet update job

The sheet isn't use any more. I was just looking if it had any things we don't have here.

**Comment by kruthers** [comment]
The FA should only accend to the role if they die while still being a TI, so if they turn undead the FA does not get it or if they die while being undead
