### ISSUE TITLE
Vampire x Lone Wolf | Priest

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#354]
It's unclear how Vampire works with Priest/LW when they miss. I guess they don't turn undead as they aren't attacked?
Maybe clarify that it only happens when a player is killed as the result of an attack?

**Comment by kruthers** [comment]
I think we should allow them to turn undead if they are demonised as they are dying indirectly because of the attack and it will make others who know there roles second guess if they hit a role they should not have
