### ISSUE TITLE
Some issues with Role related rules of rolebook

### ISSUE THREAD

**Issue by Shepherdwhen** [McTsts/Werewolves-Roles#357]
IQ and AA still mentioned in disguises
PB and AA/saint still mentioned in role losses
(Removed roles mentioned but not in rolebook any more)

Cursed Civilian not listed in role loss section even tho it loses it's role

IW on devil is still mentioned as being demon not imp in role losses section

**Comment by McTsts** [comment]
Thank you! I'll take care of them tomorrow or something.
