### ISSUE TITLE
Suggestion: Make WWW imitate most common WM.

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#358]
We've previously changed WWW disguise to a Wolf's Cub disguise iirc, we could do this without a rule change, by just having WWW disguise as the most common WM, additionally, WWW could also copy the powers of that WM so the deaths of the other WM's of that type won't expose the WWW.

**Comment by Shepherdwhen** [comment]
What if we decided to do a 50% HH pack, would WWW become HH and then we have a wolf butcher 🤔
