### ISSUE TITLE
Suggestion: New claimable TP idea

### ISSUE THREAD

**Issue by Shepherdwhen** [McTsts/Werewolves-Roles#360]
I don't have a name or any full details yet but what about a town power who silently copies one players role onto another player, the only way to prove it would to have it copy a TI onto another player, because the TP doesn't get the feedback but the original role does.

**Comment by Shepherdwhen** [comment]
also a lot of roles won't do anything just roles with active powers, like TK, TI, Hooker, Stalker, Grandma, Wolf Powers like infected wolf and sab wolf, and solos

**Comment by McTsts** [comment]
That sounds mostly confirmable and pretty weird.

**Comment by cryptidjayden** [comment]
it could maybe work as solo power rather than town, but i'm not sure i like it either way
