### ISSUE TITLE
Suggestion: FA shouldn't join TI SC

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#362]
Maybe FA shouldn't join the SC of the dead TI, because that makes it too confirmable (when the point of the last change was to make it not confirmable)

**Comment by Shepherdwhen** [comment]
what with the pin a code to a TI's sc so fa can be confirmed idea?
Yeah that basically turns all TI into a Journalist each game wit FA and makes FA hard to fakeclaim

**Comment by venomousbirds** [comment]
So if FA doesn't join channel, how do we list the TI checks, as FA is intended to know those checks

**Comment by McTsts** [comment]
Two options, I guess.
a) FA no longer has that info (does it really need it?)
b) They are informed what the checks were in their SC

**Comment by venomousbirds** [comment]
FA knowing checks would just confirm it to town that knew the previous TI, so maybe leaving FA in the dark could be an interesting option. It'd make FA easier to fakeclaim too

**Comment by McTsts** [comment]
I'd definitely prefer option a) to make FA fully claimable.

**Comment by venomousbirds** [comment]
Yeah, option a) sounds better
