### ISSUE TITLE
What is "alignment"?

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#366]

**Comment by MrTurtleJr** [comment]
I'm not sure I follow? The alignments are either Townsfolk, Werewolf or the Solo teams (every Solo team having their own alignment, e.g. Flute team).

**Comment by McTsts** [comment]
but a Wolf that is Cupid's Lover is a WM role that is solo aligned, a Cupid with a Citizen lover is townsfolk aligned but not part of the townsfolk team, etc.

**Comment by venomousbirds** [comment]
Interesting question. I think cupid has the most problems with this, and we added cupid variants. are there any other roles affected by this?

**Comment by McTsts** [comment]
Hags also have a special alignment.

**Comment by McTsts** [comment]
IMO team and alignment both describe a win condition, however somebody with an alignment but without a team is not considered in the win condition of the teams.

**Comment by McTsts** [comment]
(so alignment is just the pure win condition)

**Comment by Shepherdwhen** [comment]
IMO Alignment is the current win condition assigned to a player aka the goal that the player must achieve to win the game however with cupids this is sort of weird since the goal of the cupid + lover if not the same alignment can be seen as one of two things
1) Kill everyone else and live to the end - same alignment for both
or
2) Achieve the town and Wolf/Solo win condition and live to the end
The way to be consistent would be 1) as in as soon as a a couple of differing alignments exists their wincon becomes to eliminate anyone not in the couple except UAM, however if the couple ever do end up on the same team, aka undead/undead or undead/vamp or wolf/cupid wolf, then the couple alignment changes to the couples matched wincon

**Comment by McTsts** [comment]
I'd say Cupid and Cupid's Lover have the same alignment and team, and Cupid's Lover is no longer part of their original team.

**Comment by Shepherdwhen** [comment]
> I'd say Cupid and Cupid's Lover have the same alignment and team, and Cupid's Lover is no longer part of their original team.

That would mean cupid/vamp => undead cupid/vamp makes the vamp still against the rest of the underworld

**Comment by McTsts** [comment]
oh no

**Comment by venomousbirds** [comment]
There's a bunch of different meanings for alignment that we use, so maybe renaming some would make sense
For general purposes, alignments are "Townsfolk, Werewolves, Solo, Unaligned"
There's also role alignment, "Cupid is UA but town-aligned"
There's probably a lot more, please add to the list so we can figure out if we can rename things

**Comment by McTsts** [comment]
I don't think "Unaligned" should be considered an Alignment

**Comment by McTsts** [comment]
And probably neither should "Solo". Townsfolk, Werewolves, Solo, Unaligned (and Elected, I guess) are the role types IMO, not the alignments.

**Comment by venomousbirds** [comment]
![image](https://user-images.githubusercontent.com/80123992/166121253-48f272cc-9afd-454e-a74e-4bd6ddc097b7.png)
We've used the role categories as alignments for a long time, is it worth changing?

**Comment by McTsts** [comment]
IMO Alignments are basically equivalent to the teams.

Townsfolk roles are town-aligned, Werewolf roles are wolf-aligned, etc.

Roles like Look-Alike and Dog start out completely Unaligned (don't have a team), same for roles like Angel and Despot they are unaligned so they do not have an alignment. 

Cupid's Wolf lover would not longer be wolf-aligned, and would now be cupid-aligned.

**Comment by McTsts** [comment]
> ![image](https://user-images.githubusercontent.com/80123992/166121253-48f272cc-9afd-454e-a74e-4bd6ddc097b7.png) We've used the role categories as alignments for a long time, is it worth changing?

This doesn't really have to be wrong. Solo would simply be a group of alignments, and Unaligned can still be listed as an Alignment even when it isn't one (it makes sense to list that some players do not have an alignment under alignments)

**Comment by McTsts** [comment]
Whatever is listed on the role can be considered the starting alignment, but doesn't have to stay the same throughout the game.

**Comment by McTsts** [comment]
I think some of the confusion stems from Cupid and Hags not being Unaligned but being considered such. In my definition Cupid is *always* Cupid-aligned (as well as their lover) and Hags would always be Hag-aligned. This is clearly different from other Unaligned roles.

**Comment by venomousbirds** [comment]
I do think it'd make sense to make the teams be the alignments (Teams as in Townsfolk, Werewolves, Solo-Pyro etc). Unaligned is just the group name and it does make sense to list it as a general alignment
