### ISSUE TITLE
Role Idea: Bee

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#368]
![image](https://user-images.githubusercontent.com/24660095/120817162-c1d64500-c551-11eb-91bf-fc8b6d7e3aec.png)

**Comment by cryptidjayden** [comment]
i forgot about the fucking bee role lol

**Comment by venomousbirds** [comment]
Roleblocker... I'd rather not see that in werewolves

**Comment by McTsts** [comment]
Same
