### ISSUE TITLE
Suggestion: Items

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#369]
![image](https://user-images.githubusercontent.com/24660095/120817223-d31f5180-c551-11eb-9d46-78d3bf9bc57f.png)

**Comment by McTsts** [comment]
No

**Comment by Shepherdwhen** [comment]
I feel like some of it could work as separate roles

**Comment by MrTurtleJr** [comment]
Some games work with items, but I wouldn't say items should be a part of the base flavor.

**Comment by bobloy** [comment]
Here is an example of how I imagine items could work. This could easily be tied to a role that initially hands them out.

**Cursed Totem/Blessed Totem**
Item

You are now holding a totem. While holding a cursed totem, you are strongly disguised as a a wolf. While holding a blessed totem, you will survive one attack during the night. 

During the night, pick another player to pass the totem to. The totem will be passed at the start of the next day.
If you get passed a totem you've already had, the totem will have no effect on you.

**Comment by venomousbirds** [comment]
Let's just delete this idea to be honest
