### ISSUE TITLE
Role Idea: Cryptographer

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#371]
![image](https://user-images.githubusercontent.com/24660095/120818257-b899a800-c552-11eb-962b-9f7ae92451d6.png)

**Comment by McTsts** [comment]
Alternative version 
![image](https://user-images.githubusercontent.com/24660095/120818537-00203400-c553-11eb-849c-eb426036aebd.png)

**Comment by McTsts** [comment]
A Solo that can kill a lot but reveals themself a bit every time they do could work, but the way that happens would need to be changed. The second variant seems pretty bad however.

**Comment by venomousbirds** [comment]
I really dislike this idea. Using names is just very inconsistent and I don't think it fits into werewolves gameplay. Arch suggested using discord IDs but it still doesn't make much sense to me. I don't think this role will work
