### ISSUE TITLE
Role Idea: Red Riding Hood

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#374]
![image](https://user-images.githubusercontent.com/24660095/120819419-da475f00-c553-11eb-8af6-14d5c7fe1d76.png)

**Comment by MrTurtleJr** [comment]
Don't we have Riding Hood as a role?

The concept seems interesting, though.

**Comment by McTsts** [comment]
Yeah, the name is already used, so it would have to be changed.

**Comment by McTsts** [comment]
Closing this suggestion due to lack of development on it. Feel free to reopen this (now or at any point in the future) if you want to further discuss/develop this idea.
