### ISSUE TITLE
Suggestion: Log Votes

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#376]
![image](https://user-images.githubusercontent.com/24660095/120819784-31e5ca80-c554-11eb-9757-678806285395.png)

**Comment by MrTurtleJr** [comment]
I think something like this would be nice as:

a) it would make sniping more pronounced and obvious,
b) it would give time stamps on votes,
c) and it would require players to think a bit before placing a vote.

**Comment by Shepherdwhen** [comment]
> I think something like this would be nice as:
> 
> a) it would make sniping more pronounced and obvious,
> b) it would give time stamps on votes,
> c) and it would require players to think a bit before placing a vote.

Also people could spam change votes and flood the channel which could block out an attempt at a snipe ect which would ruin the point I think, also spam flood 😔

**Comment by MrTurtleJr** [comment]
Just ban the spam flood? Just like people who would spam thousands of messages in #town_square would probably get muted? Or how people who abuse Mayor posting perms are mod-killed.

**Comment by venomousbirds** [comment]
I don't think we need this in werewolves. I could only see it as being annoying (and it feels very mafia-like to me, which i dislike)
