### ISSUE TITLE
Role Idea: Berserk Wolf

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#377]
![image](https://user-images.githubusercontent.com/24660095/120820876-365eb300-c555-11eb-9dd2-ed3ed29035ae.png)

**Comment by Shepherdwhen** [comment]
Maybe make it non pack then becomes pack once it has killed
also could make it non-lycan and call it seamstress

**Comment by McTsts** [comment]
That's an oddly specific suggestion

**Comment by Shepherdwhen** [comment]
> That's an oddly specific suggestion

Idk what you mean 👀 

Nah I had thought of a wolf barber analogue, it popped in my head like tanner or warlock but kills once and joins pack after, kills in day and is immediate kill, allows for possibility of killing wolves and also cc conversion during the day maybe

**Comment by McTsts** [comment]
I still question why we would need this?

**Comment by venomousbirds** [comment]
I don't think we need wolf-aligned day killing

**Comment by McTsts** [comment]
Closing this suggestion due to lack of development on it. Feel free to reopen this (now or at any point in the future) if you want to further discuss/develop this idea.
