### ISSUE TITLE
Role Idea: Gunsmith

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#378]
![image](https://user-images.githubusercontent.com/24660095/120821055-6ad26f00-c555-11eb-8360-5a9c763a3532.png)
![image](https://user-images.githubusercontent.com/24660095/120821082-6f972300-c555-11eb-8351-c56d8b575eb0.png)

**Comment by MrTurtleJr** [comment]
The role needs to be renamed to something less mafia-esque before everyone goes bonkers.

**Comment by McTsts** [comment]
yeah Gunsmith wouldn't fit the theme we have. We seem to have some sort of magical fantasy medieval setting.

**Comment by 12Metatron** [comment]
it would need to have a more limited amount of guns I think. one gun per day is really a lot, especially for a town

**Comment by McTsts** [comment]
I feel like the making gun thing seems a bit redundant because most of the time the Gunsmith would probably just switch between making a gun and giving somebody a gun.

**Comment by venomousbirds** [comment]
This role might be a little too similar to fletcher if we limit the guns. Maybe make it not do anything n1? Or only on even nights
