### ISSUE TITLE
Role Idea: Furrier

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#379]
![image](https://user-images.githubusercontent.com/24660095/120821464-c56bcb00-c555-11eb-8e0a-0d14ef55b1f9.png)

**Comment by MrTurtleJr** [comment]
To clarify, this is a role I envision being used more for balancing purposes. It's somewhat similar to the role Cursed Civilian, in that while being town it can work as a disadvantage to the Townsfolk. It also works as claimspace _as well as_ giving a "seen Wolf" a chance at a comeback - something which requires great skill.

It's the opposite of the Sneaking Wolf.

**Comment by McTsts** [comment]
This doesn't really seem like it'd be very fun to play, but it works for balance purposes. I would however suggest using a different name. Also, the Huntsman/Oracle would be immune to this as it'd probably be a strong disguise.

**Comment by MrTurtleJr** [comment]
Yeah, I get that people may not like to play this role, so it should probably be used sparsely. 

Personally, I like playing as these types of roles (Cursed Civilian and the sorts).

**Comment by MrTurtleJr** [comment]
> This doesn't really seem like it'd be very fun to play, but it works for balance purposes. I would however suggest using a different name. Also, the Huntsman/Oracle would be immune to this as it'd probably be a strong disguise.

Also, yeah, this role wouldn't work in role lists with Huntsman/Oracle (and possibly AT?).

**Comment by McTsts** [comment]
If it's a strong disguise AT will be affected.

**Comment by McTsts** [comment]
But what is interesting about this is that it'd also fool the wolves.

**Comment by venomousbirds** [comment]
I don't think it'd be fun to play either. It does seem very interesting for balancing purposes. A different name is definitely needed, but I think this role could work quite well.

**Comment by Shepherdwhen** [comment]
Wouldn't it also confuse Wa and Lwa which means if the furier plays along with it they could get valuable info

**Comment by McTsts** [comment]
This role should probably receive a PR so it could be added in v13

**Comment by McTsts** [comment]
Closing this suggestion due to lack of development on it. Feel free to reopen this (now or at any point in the future) if you want to further discuss/develop this idea.
