### ISSUE TITLE
Chef: different sentences

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#38]
• (details) "is allowed to eat the food" in rolebook vs " is given the opportunity to eat the food. " in bot description
• (details) "are unable to win, this usually happens" in bot description vs "are unable to win; this usually happens" in rolebook (, vs ;)

**Comment by venomousbirds** [comment]
" is given the opportunity to eat the food. " sounds better
assign the second one to someone who is better in english
