### ISSUE TITLE
Duplicate solos addition

### ISSUE THREAD

**Issue by Shepherdwhen** [McTsts/Werewolves-Roles#382]
![image](https://user-images.githubusercontent.com/82595414/120872324-49de3e00-c596-11eb-9347-2be68c6644e2.png)

This was a suggestion made on minis so it slipped through the gaps, I think it could work, if some roles were buffed (Flock misc) or some better Seconday roles were added to cover this (Vamp).

**Comment by Shepherdwhen** [comment]
If it was changed the one we would struggle with is Pyro team, however maybe new firebug could help, as firebug is weaker than Pyro and not as strong as wisp even if it knows Pyros

**Comment by Shepherdwhen** [comment]
Also For vampire team I was thinking a role that if attacked by a demonised player the attack fails and the demonised player is turned

**Comment by 12Metatron** [comment]
Weaker reaper is currently called wraith. Wisp might actually be stronger than pyromancer here because LA would know who a pyro is. Evil scientist already has one called lab assistant I think, though evil scientist might be weak enough to allow 2 of them.

**Comment by Shepherdwhen** [comment]
> Weaker reaper is currently called wraith. Wisp might actually be stronger than pyromancer here because LA would know who a pyro is. Evil scientist already has one called lab assistant I think, though evil scientist might be weak enough to allow 2 of them.

This message on discord was made before the changes, also current LA edgecase is ES + LA => Lab Assistant to buff disease team not make it weaker

I did suggest possibly new firebug as it's still a weak pyro if it knows 1 pyromancer, especially if the pyromancer doesn't trust the claim

**Comment by 12Metatron** [comment]
> 
> This message on discord was made before the changes, also current LA edgecase is ES + LA => Lab Assistant to buff disease team not make it weaker

yeah, I see. I guess lab assistant might need a buff, like maybe starting out contagious
> I did suggest possibly new firebug as it's still a weak pyro if it knows 1 pyromancer, especially if the pyromancer doesn't trust the claim
that would work nice if firebug gets approved. but if it had to be between pyromancer and wisp, pyromancer is the better choice

**Comment by McTsts** [comment]
The current system for copying is intended to work so that roles where we might put multiple of in a role list can be copied (Vampire, Pyromancer) and roles where we only put one of into a game can't be copied (Devil)
