### ISSUE TITLE
Rename Evil Scientist

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#391]
Rename ES to avoid confusion with MS and maybe make it a more fitting word (e.g. Alchemist)

**Comment by 12Metatron** [comment]
ideas i had: 
epidemiologist, toxicologist, virologist

those are just types of scientists related to poison/disease

**Comment by Shepherdwhen** [comment]
Rat Catcher could also work as the rats spread the plague

**Comment by McTsts** [comment]
> ideas i had:
> epidemiologist, toxicologist, virologist
> 
> those are just types of scientists related to poison/disease

I think all of those fit less than Evil Scientist to be honest

**Comment by bobloy** [comment]
Warlock, Poisoner, Plague Doctor, Plague Bearer, Plague Engineer

**Comment by Shepherdwhen** [comment]
> Warlock, Poisoner, Plague Doctor, Plague Bearer, Plague Engineer

Warlock is already a role lmao, also Plague Bearer is the name of the similar role in ToS

**Comment by McTsts** [comment]
Poisoner is my favorite but I don't think it makes sense (it's not infectious?) and until recently we did have Plaguebearer so it might be best not to reuse that name

**Comment by McTsts** [comment]
I don't think those types of poisoning are what people think of when they hear "Poisoner"

**Comment by McTsts** [comment]
Resolved by #269
