### ISSUE TITLE
Role Idea: Joker

### ISSUE THREAD

**Issue by Shepherdwhen** [McTsts/Werewolves-Roles#396]
![image](https://user-images.githubusercontent.com/82595414/121600842-06278080-ca3d-11eb-9fed-35b49ebf10d2.png)

I like it as it's not a hard win, but also not always a given win, it almost feels as if devil was an unaligned

**Comment by McTsts** [comment]
the risk is already not really worth it with Chef usually

and Chef has a pseudo alignment at least

**Comment by venomousbirds** [comment]
Lynch and Election votes can currently not be given seperately. I also don't think people have much reason to accept the cards, just like people generlaly dont eat chef food

**Comment by McTsts** [comment]
This is basically another variant of Chef and #326. I don't think those really work.
