### ISSUE TITLE
Disbanding Groups

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#4]
Groups should be disbanded when no "real" members of it are left(?) Clarify this.

**Comment by venomousbirds** [comment]
Where did you get this from?

**Comment by McTsts** [comment]
Back when I was more active this was a thing

**Comment by venomousbirds** [comment]
I mean, where did you get the "real" members part from? Is it in the role book?

**Comment by McTsts** [comment]
No, I put a (?) because idk if this a thing that's written anywhere. It just was a thing that was done. (so e.g. Werewolves are disbanded if only Undead are left)

**Comment by venomousbirds** [comment]
I feel like in some cases that wouldn't make sense, but I don't exactly know which cases

**Comment by McTsts** [comment]
it can only really happen when only undead are left

**Comment by McTsts** [comment]
well or Undead *and* Zombies

**Comment by venomousbirds** [comment]
With cult, the cult could consist of an undead, a zombie and a wolf at the time, and they wouldn't know it
In that case, disbanding wouldn't make sense because they wouldn't neccesarily know that the other isn't cult anymore.
In case of wolves, it would make sense because only undead/zombie could be possible

**Comment by McTsts** [comment]
the wolf is a member of the cult

**Comment by McTsts** [comment]
(they can vote)

**Comment by venomousbirds** [comment]
That doesn't make sense to me, they've changed role, and shouldn't actually be able to vote

**Comment by McTsts** [comment]
Thats just how it is for all role changes except Undead

**Comment by McTsts** [comment]
This is not actually an issue. "If all members of a group are dead or turned, the group is disbanded." - already in the role description of Undead
