### ISSUE TITLE
Lone Wolf => Wolf & Lone Warlock => ??

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#412]
This was previously discussed but not resolved. 
It was previously suggested that the Lone Wolf turns into a Wolf if they join the pack and that the Lone Warlock turns it a plain non-lycan wolf ("coyote"?)

**Comment by McTsts** [comment]
Everyone has a different opinion on this so we have failed to resolve this issue for v13.

**Comment by ThomasRubycrust** [comment]
I think no option really makes sense for Lone Warlock, because Lone Warlock itself doesn't make any sense. Lone Wolf is a Wolf that's alone and basically becomes a Wolf later on. Lone Warlock is *not* a Warlock that's alone, it's actually exactly the same as Warlock until it joins the pack (so arguably it's *less* lonely than normal Warlock), however the Lone prefix is probably still better to keep than not, because it means LW and LWa have a shared part of their name for their shared ability. I don't think any change of LWa into another role except for Warlock would really seem logical, and changing to Warlock obviously makes no sense. When Lone Wolf changes into Wolf it doesn't really change what the Lone Wolf is (they're still a wolf, just not lonely anymore). Changing the Warlock part of the name doesn't really make much sense either: When the Lone Wolf becomes a Wolf they don't really lose their killing ability - they just share it with the other wolves now, the same can't be said for the Lone Warlock. Even if Lone Warlock was renamed to Lone Something and then turned into a Something when they join the pack, it now wouldn't make any sense for them to lose their ability. Conclusion: none

**Comment by Shepherdwhen** [comment]
> I think no option really makes sense for Lone Warlock, because Lone Warlock itself doesn't make any sense. Lone Wolf is a Wolf that's alone and basically becomes a Wolf later on. Lone Warlock is _not_ a Warlock that's alone, it's actually exactly the same as Warlock until it joins the pack (so arguably it's _less_ lonely than normal Warlock), however the Lone prefix is probably still better to keep than not, because it means LW and LWa have a shared part of their name for their shared ability. I don't think any change of LWa into another role except for Warlock would really seem logical, and changing to Warlock obviously makes no sense. When Lone Wolf changes into Wolf it doesn't really change what the Lone Wolf is (they're still a wolf, just not lonely anymore). Changing the Warlock part of the name doesn't really make much sense either: When the Lone Wolf becomes a Wolf they don't really lose their killing ability - they just share it with the other wolves now, the same can't be said for the Lone Warlock. Even if Lone Warlock was renamed to Lone Something and then turned into a Something when they join the pack, it now wouldn't make any sense for them to lose their ability. Conclusion: none
> 
> Edit: I guess my actual conclusion is that while LW=>Wolf would make sense, adding that would mean we should also have LWa=>sth for consistency, but there's nothing that would make sense there, so unless someone has a great idea we should probably do neither

W could rename Warlock to something like "Palm Reader" or "Astrologist" since it is an evil Fortune Teller then that opens up La => Warlock

**Comment by ThomasRubycrust** [comment]
This doesnt solve the argument that the LW doesnt truly lose his killing power. Wolves in the wolfpack kill by deciding together, the Lone Wolf is alone so he decides alone. When they join the pack they still kill, just in combination with the wolfpack. (Also I think renaming Warlock is a bad idea)

**Comment by Shepherdwhen** [comment]
> This doesnt solve the argument that the LW doesnt truly lose his killing power. Wolves in the wolfpack kill by deciding together, the Lone Wolf is alone so he decides alone. When they join the pack they still kill, just in combination with the wolfpack. (Also I think renaming Warlock is a bad idea)

Ok that makes sense, the only solution I can think of is that the lwa joins the pack as a wolf if it is attacked by the pack, kind of like how cc works except its only a role change not an alignment change

**Comment by venomousbirds** [comment]
> 

Well it's not the Lone part that needs changing, the Lone just means that it joins pack after the first pack member dies

**Comment by ThomasRubycrust** [comment]
> Lone Warlock -> Psy Wolf?

I guess that would make sense? Unsure if we want to do that though.

**Comment by ThomasRubycrust** [comment]
> > This doesnt solve the argument that the LW doesnt truly lose his killing power. Wolves in the wolfpack kill by deciding together, the Lone Wolf is alone so he decides alone. When they join the pack they still kill, just in combination with the wolfpack. (Also I think renaming Warlock is a bad idea)
> 
> Ok that makes sense, the only solution I can think of is that the lwa joins the pack as a wolf if it is attacked by the pack, kind of like how cc works except its only a role change not an alignment change

The problem this issue is trying to resolve is that Lone Wolf & Lone Warlock (and possibly also foxes) should change role when joining the pack (without any other changes to mechanics). The actual problem is that for Lone Warlock the role change doesn't make much sense.

**Comment by venomousbirds** [comment]
It's currently what makes the most sense, but it's also weird because Warlock and Psy Wolf check in different ways. 
It's however not consistent with what Lone does (Lone Wolf doesn't get their own personal kill once they join the pack, why would Warlock still be able to check?)
That's probably what the thought process behind LWa => Wolf was

**Comment by venomousbirds** [comment]
Making a mid-game role named Pack Warlock would be an interesting solution
It'd be similar to Pack tanner in that it's not a lycan but is still in the pack

**Comment by venomousbirds** [comment]
I would make a PR but idk how to add roles

**Comment by ThomasRubycrust** [comment]
You navigate to the folder you want to add it in (I guess Limited) and click "Add file" (top right)

**Comment by ThomasRubycrust** [comment]
probably doesnt make much sense as limited, since LWa isn't limited either

**Comment by venomousbirds** [comment]
definitely transformation, you can only obtain it midgame, i dont intend for it to be an in-pack invest (could be changed later if people really want to)

**Comment by ThomasRubycrust** [comment]
yeah I think that makes sense. the new LWa would already be powerful as is, no need to have it in the pack immediately

**Comment by ThomasRubycrust** [comment]
Maybe some permissions are wrong, but try this:

- Go here: https://github.com/McTsts/Werewolves-Roles/tree/main/werewolves/transformation

- Click "add file", then "create new file"
![image](https://user-images.githubusercontent.com/96175908/166709045-946f0e01-4819-4d54-864b-878c4fbae036.png)

1) name the file "pack warlock"
2) put the description
3) select create new branch
4) name the branch (e.g. "add pack warlock")
5) click the green button
![image](https://user-images.githubusercontent.com/96175908/166709257-4377ff1f-aee2-4844-8c72-00887035a52c.png)

**Comment by venomousbirds** [comment]
thats why i oopsed

**Comment by ThomasRubycrust** [comment]
there's no easy undo, you can delete the file manually and try again

**Comment by cryptidjayden** [comment]
I understand the whole 'why would a warlock turn into a wolf lol' jig, but I think the role is fine as it is, to be honest. It's a really easy way to give wolves a balanced investigative especially in smaller games where pack might suffer from thinner ranks. The proposed Pack Warlock change would make it much more powerful and would remove what I believe to be a key role for smaller games. There is some current overlap with CF, but CF is imo quite a bit stronger, and so if LW was changed in this, there'd still be that gap. PsyW is meanwhile much weaker.

Ultimately, names are just names - do they really have to make sense down to the tiniest detail?

**Comment by McTsts** [comment]
I think LWa just changing to Wolf would also be fine

**Comment by McTsts** [comment]
Or we can preserve the old LWa behavior in a different way

**Comment by venomousbirds** [comment]
added future version to this so we can maybe discuss it later

**Comment by ThomasRubycrust** [comment]
Lone Wolf => Retired Wolf
Lone Warlock => Retired Warlock

:)

**Comment by ThomasRubycrust** [comment]
to be more logical Retired Wolf maybe couldnt attack :)
