### ISSUE TITLE
Rename Mad Scientist

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#413]
This was previously discussed but not resolved.

**Comment by McTsts** [comment]
There were no previous name suggestions.

**Comment by McTsts** [comment]
Maybe we can think of something that's better than Dungeoner at some point=

**Comment by venomousbirds** [comment]
Inventor maybe? Not sure how it could apply to the role but crazy Inventor is a fun concept

**Comment by McTsts** [comment]
I'm not really sure if this word fits the theme or role. It seems like a fitting replacement for Mad Scientist but I don't think MS is a particularly well-fitting name in the first place.

**Comment by venomousbirds** [comment]
In that case we could accept it as Dungeoner and ask around for people to think of a better fitting name (Maybe do the same for amnesiac)

**Comment by McTsts** [comment]
I think, if we plan to rename it again I don't think there's any point in renaming it

**Comment by McTsts** [comment]
If anyone has any popular ideas for Amnesiac we can rename it though, we did the same thing for Royal Wolf and Coward

**Comment by Shepherdwhen** [comment]
What about torturer, since the MS can get info out of it's two targets before eventually killing one

**Comment by venomousbirds** [comment]
might be a bit too close in name to executioner, but i do like the idea

**Comment by McTsts** [comment]
![image](https://user-images.githubusercontent.com/24660095/123789102-1369b980-d8dd-11eb-8a44-0ed1d77354aa.png)

**Comment by McTsts** [comment]
Don't think this is worth it
