### ISSUE TITLE
Evil scientist: he/they, vial(s)

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#43]
Evil scientist
• in bot "he" is used, but in the rolebook "they" is used
• (details) "vial(s)", maybe remove (s) since they always start with more than 1

• (The Disease) "End Day / End Night" has a - instead of a space in rolebook

**Comment by venomousbirds** [comment]
using gender neutral terms for roles should be the default
 end day/night is another issue

**Comment by McTsts** [comment]
Was connected to #49 but is only partially fixed by it. Should still remain open for the other two issues mentioned.

**Comment by Mjnstag** [comment]
Fixed the vial(s)
