### ISSUE TITLE
plaguebearer/vampire: cannot target each other

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#44]
• (details) "The Plaguebearer can't be demonized or tainted." not in bot description (plaguebearer)

maybe also add the opposite in the vampire description

**Comment by venomousbirds** [comment]
Plaguebearer is a limited role and shouldn't be found in a game at the same time as vampire unless it's offseason. For offseason we can clarify it in the rule changes section in the game announcement and gamelog start

**Comment by McTsts** [comment]
Yeah it shouldn't be added to the Vampire one, but Plaguebearer should have it.

**Comment by Mjnstag** [comment]
good?
