### ISSUE TITLE
Cursed Civ fix?

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#448]
Here's another attempt to fix the CC role. I haven't thought about this very much so it may be super flawed.

CC becomes an UA role, that wins with town. If the CC is attacked by a wolf, they turn into a sickly wolf or something like that. A day or so after that happens they die. The advantage over the old CC is that as an UA this CC could always plan to betray town without gamethrowing, and to limit this they only get a limited amount of time as a wolf so they wouldn't do it immediately.

**Comment by Shepherdwhen** [comment]
I think a problem is that cc then wouldn't want to be turned as after you turn you only have a couple more days to play, one of the biggest things about social deduction is that people dislike not being able to play because of how their role works, cc will probably be one of those roles that is ia a lot if this is the change

**Comment by ThomasRubycrust** [comment]
> I think a problem is that cc then wouldn't want to be turned as after you turn you only have a couple more days to play

This is already the case now. 

> one of the biggest things about social deduction is that people dislike not being able to play because of how their role works, cc will probably be one of those roles that is ia a lot if this is the change

I dont think I understand how that relates to this suggestion

**Comment by Shepherdwhen** [comment]
> > I think a problem is that cc then wouldn't want to be turned as after you turn you only have a couple more days to play
> 
> This is already the case now (the wouldnt want to be turned part)
> 
> > one of the biggest things about social deduction is that people dislike not being able to play because of how their role works, cc will probably be one of those roles that is ia a lot if this is the change
> 
> I dont think I understand how that relates to this suggestion

The role feels more defeatist than it is already since the sickly wolf part makes it so if you turn you will be guaranteed to die in a few days, however the current cc only dies when town catches on that it's changed to a wolf.

It's kinda like, if I'm going to die unstoppably in a few days why play the game

**Comment by Shepherdwhen** [comment]
A suggestion I would make that is similar is
The CC starts as an Unaligned Align that can only win with town or solo serving basically as an extra vote for either that it decides to align with, however if the cc is attacked by a wolf they become a lost wolf, who instead can only win with wolves or solo.

Being a UAA the cc should be prepared to switch alignment at any point, and by being unaligned the cc isn't gamethrowing by betraying the town and switching.

For reference the lost wolf is still uaa and isn't part of the pack, but can still win with solo

**Comment by Shepherdwhen** [comment]
the other mechanic I would add possibly is that the cc can also change into a lost wolf at will, but that power only works within x amount of days to prevent endgame switching just to gain a free win

**Comment by ThomasRubycrust** [comment]
> A suggestion I would make that is similar is The CC starts as an Unaligned Align that can only win with town or solo serving basically as an extra vote for either that it decides to align with, however if the cc is attacked by a wolf they become a lost wolf, who instead can only win with wolves or solo.

Ooh, I think this could be fairly interesting. Giving the CC the ability to work with the solos as well I think could be quite interesting, and the CC an also be sure that if it does choose to work with solos it wont ever have to betray them. It also still means the wolves couldnt trust it fully since it could still work with the solos.

> Being a UAA the cc should be prepared to switch alignment at any point, and by being unaligned the cc isn't gamethrowing by betraying the town and switching.

Yeah, that was also the idea behind my suggestion, but I think yours seems better,

> For reference the lost wolf is still uaa and isn't part of the pack, but can still win with solo

This is kind of like Packless Wolf which isn't great, but with this role it may work?


> the other mechanic I would add possibly is that the cc can also change into a lost wolf at will, but that power only works within x amount of days to prevent endgame switching just to gain a free win

I think this would basically just allow the role to act like Dog, which I dont think we should do.

**Comment by ThomasRubycrust** [comment]
This might be too powerful, but maybe if CC is attacked by a lycan it becomes LostW and if LostW is attacked by town it becomes CC?

**Comment by Shepherdwhen** [comment]
The problem with cc switching is it can easily just out at least one wolf to town if it switches back, plus with the fact that town doesn't have many unlimited kills at it's disposal and converting cc wouldn't be as useful, if it can switch back, as killing a wolf or solo it'd be a mechanic that exists but is hardly used

**Comment by ThomasRubycrust** [comment]
> The problem with cc switching is it can easily just out at least one wolf to town if it switches back, plus with the fact that town doesn't have many unlimited kills at it's disposal and converting cc wouldn't be as useful, if it can switch back, as killing a wolf or solo it'd be a mechanic that exists but is hardly used

Yeah, it could out one wolf, but a) thats be point, b) it could just as well be a townie that they're trying to get killed

**Comment by Shepherdwhen** [comment]
Hmmmm true, as for the buff possibly something that would be useful to the CC/LostW as well as the alignment it is helping is that it could check a players alignment each night, sort of like cautious hag

**Comment by ThomasRubycrust** [comment]
I dont think that would fit the role.

**Comment by cryptidjayden** [comment]
i kinda hate this ngl

**Comment by cryptidjayden** [comment]
just to be clear i am not aiming to be constructive in any way i just like sharing my opinions

**Comment by McTsts** [comment]
The version in the first comment, or the version at the end of the discussion?

**Comment by ThomasRubycrust** [comment]
oh well, I'll just close it. Probably not one of the better ideas.

**Comment by McTsts** [comment]
I said I'll close it, and did in fact not close it
