### ISSUE TITLE
Suggestion: slight www buff

### ISSUE THREAD

**Issue by 12Metatron** [McTsts/Werewolves-Roles#452]
Suggestion # 1:
suggestion that www autowin when in final 3 and the other players are all town or wolf alignment

**Comment by McTsts** [comment]
This seems like a strange type of buff

**Comment by McTsts** [comment]
Based on OS7B I think a solid argument can be made that WWW isn't particularly strong, but if we buff WWW I would like a different type of buff.

**Comment by McTsts** [comment]
Suggestion # 1:
- At the start of the game the WWW may choose between odd or even numbered kills

Suggestion # 2:
- The WWW gets a kill during every odd numbered night, but may choose not to kill and instead kill during the next even numbered night

**Comment by McTsts** [comment]
Suggestion # 3:
- Same as # 2 but switched. The WWW gets a kill during every even numbered night (N2 first one), but may choose not to kill and instead kill during the next odd numbered night. This moves the first possible WWW kill to the same night as the current first WWW kill

**Comment by McTsts** [comment]
I'm against # 1, I favor # 3 / # 4 but am undecided which one would be better. # 2 is a solid alternative, with less of a mechanic change, but a much smaller buff

**Comment by McTsts** [comment]
Suggestion # 5:
- A slightly stronger version # 2. During any night the WWW may choose once to attack. Following this the WWW can attack again every other night. For example the WWW may choose during N1 and immediately kill, then kill again N3, they may also choose during N2 then immediately kill, then again N4. Of course they can also skip both of the first nights (and thereby their first kill) and only choose during N3 or N4. This is the same as # 2, but the WWW doesn't have to immediately commit to odd or even at the start of the game.

Suggestion # 6:
- Same as # 5, but N2 would be the first possible attack.

**Comment by McTsts** [comment]
Out of the # 5 / # 6 / # 2 type of buff I'd favor # 5 over # 6 and # 2

5, 6 & 2 preserve the "every other night" aspect. Whereas 3 and 4 would allow two kills in a row. This could be considered to be too powerful.

**Comment by McTsts** [comment]
Suggestion # 7:
- This resolves the problem brought up in my previous comment. The WWW may attack in N1 (or N2). If the WWW chooses not to attack they may instead attack the next day. Once the WWW attacks they cannot attack the next night, but can once again attack in the night after. Here the WWW can delay their attack if they want to (also allowing them to change odd and even numbered attacks if they wanted to), but the "every other night" aspect is still preserved

**Comment by McTsts** [comment]
Summary:
- WWW autowins when in final 3 & other players are all town or wolf
- WWW can choose between odd & even cycle
- WWW can launch their attack in any night starting with the first **X** night, once they do so again exactly every other day
- WWW gets a kill every **X** night, but can delay it to the following **Y** night. They'd still get their next kill in the next **X** night
- WWW gets their first kill during the first **X** night, but may choose to not use it (also several times in a row). Once they use it they'll get a kill again after one night of no kill.

for suggestions using **X** and **Y**, X can be odd and Y even or vice versa (both variants are valid suggestions)

**Comment by 12Metatron** [comment]
i think those are all really good ideas

**Comment by Shepherdwhen** [comment]
A combination of all the odd/even night suggestions, simply

The WWW cannot kill on consecutive nights

This means the www can start killing whenever it wants and as long as the current night is not the night after a www kill has taken place the www can kill

An example would be

N1 Kill, N2 no kill, N3 no kill, N4 kill, N5 no kill, N6 kill

**Comment by McTsts** [comment]
this is the same as # 7 but formulated more clearly

**Comment by venomousbirds** [comment]
> WWW gets their first kill during the first X night, but may choose to not use it (also several times in a row). Once they use it they'll get a kill again after one night of no kill.
Probably the best one out of all, it's still a kill every other night but more flexible.
I do prefer the killing being able to only start after N1, to not stray too far from the original WWW even night kill
