### ISSUE TITLE
White Werewolf isnt listed as a member of the wolfpack

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#467]

**Comment by venomousbirds** [comment]
> The White Werewolf is not part of the werewolf team, but is still considered a lycan and is part of the wolfpack.
last line in the description

**Comment by venomousbirds** [comment]
i didnt even know that was a command

**Comment by McTsts** [comment]
In some v12 version I added commands for pretty much all groups, teams, categories and similiar (there's also things like bakers, butchers, pyro team, list of all teams, list of categories in werewolf team, etc) They're all in the categories folder (no underscore)
