### ISSUE TITLE
How To Play Update

### ISSUE THREAD

**Issue by venomousbirds** [McTsts/Werewolves-Roles#471]
**Please copy paste whole message with changes you wanna make**

--------------
__**How to play Werewolves Revamped**__

Werewolves Revamped is based on the card game 'Werewolves of Miller's Hollow', with influences from forum mafia and other online roleplaying games. The goal is to win with your alignment.

**Alignments**
Alignments are a big part of Werewolves Revamped. They decide your win condition (the way for you to win), and they decide who you can or can't cooperate with.

:house: Townsfolk
> This aligment makes up about 50% of the players. They have the most players, but with the disadvantage that they do not know eachother from the start. Their goal is to kill everyone who doesn't have the same win condition as them.

:wolf: Werewolves
> Werewolves make up about 30% of the players. While they are in a small group, everyone in the wolfpack knows eachother. Their goal is to work together and kill everyone who doesn't have the same win condition as them.

:fire: Solo
> The solos make up about 10% of the players. Most of the time, they work completely alone. Their goal is to win alone, and outplay everyone who doesn't have the same win condition as them.

:question: Unaligned
> The unaligned are truly unique. They make up about 10% of the players. Their goal is to fullfill their win condition. With that, they might even change alignment. The ones that don't change alignment ascend when they win, leaving the game dead, but with a win in their pocket. As they have no alignment, they are free to work with whatever alignment they want.

**The day/nighttime cycle**
Werewolves Revamped is played in a real-time day/night cycle. That means that a day and a night added up in Werewolves Revamped always total 24 hours.

:sunny: Daytime
> In daytime, players can vote on a lynch poll and an election poll. At the end of the day, the lynch poll kills the top voted player. At the same time, the top voted player in the election poll gets a special public role on top of their current role. The elected roles are Mayor, Reporter and Guardian.
_ _
:crescent_moon: Nighttime
> In nighttime, most roles perform their role-specific actions, which can have effect on the other roles and players in the game. Effects can be immediate or end night. 

**Conspiracy Channels**
Werewolves Revamped is unique in their usage of Conspiracy Channels, mostly referred to as "cc's".
> Conspiracy Channels are player-made channels, and give an opportunity to have a private channel with one or more players of their choosing. These channels can be used to talk privately, without other players being able to read what's being said.

**Comment by McTsts** [comment]
__**How to play Werewolves Revamped**__

Werewolves Revamped is based on the card game 'Werewolves of Miller's Hollow', with influences from forum mafia and other online roleplaying games. The goal is to win with your alignment.

**Alignments**
Alignments are a big part of Werewolves Revamped. They decide your win condition (the way for you to win), and they decide who you can or can't cooperate with.
Each role has its base alignment listed next to the role name and generally, this is the same as the player's actual alignment. When a role like Cupid is in play it's possible for the base alignment of players to differ from their actual alignment.

:house: Townsfolk
> This alignment makes up about 50% of the players. They have the most players, but with the disadvantage that they do not know each other from the start. 
Their goal is to kill everyone who doesn't have the same win condition as them.

:wolf: Werewolves
> Werewolves make up about 30% of the players. While they are in a small group, everyone in the wolfpack knows each other. 
Their goal is to work together and kill everyone who doesn't have the same win condition as them.

:fire: Solo
> Solo is a group of various smaller alignments. The solos make up about 10% of the players. Most of the time, they either work completely alone or they are a very small team. Their goal is to win by outplaying everyone who doesn't have the same win condition as them. There can be several separate solo alignments in one game and under some circumstances, new ones can be created during the game.

:question: Unaligned
> The unaligned are truly unique, they aren't part of any alignment. They make up about 10% of the players. Their goal is to fulfill their win condition. With that, they might even join an alignment. 
The ones that don't change alignment ascend when they win, leaving the game dead, but with a win in their pocket. As they have no alignment, they are free to work with whatever alignment they want.
Unaligned players are exempt from other teams' win conditions. For example, this means that the Werewolves can win with Unaligned players left alive, even though they are supposed to kill all other players. This does not apply for Unaligned players that join an alignment.

**The day/nighttime cycle**
Werewolves Revamped is played in a real-time day/night cycle. That means that a day and a night added up in Werewolves Revamped always total 24 hours.

:sunny: Daytime
> In daytime, players can vote on a lynch poll and an election poll. At the end of the day, the lynch poll kills the top voted player. At the same time, the top voted player in the election poll gets a special public role on top of their current role. The elected roles are Mayor, Reporter and Guardian.
_ _
:crescent_moon: Nighttime
> In nighttime, most roles perform their role-specific actions, which can have effect on the other roles and players in the game. Effects can be immediate or end night. 

**Conspiracy Channels**
Werewolves Revamped is unique in their usage of Conspiracy Channels, mostly referred to as "cc's".
> Conspiracy Channels are player-made channels, and give an opportunity to have a private channel with one or more players of their choosing. These channels can be used to talk privately, without other players being able to read what's being said.

**Comment by McTsts** [comment]
Only the first message requires updating btw

**Comment by venomousbirds** [comment]
I saw some other stuff so I'm leaving it here for others to review

**Comment by McTsts** [comment]
we have this thing duplicated unfortunately, so any change we make to it we also need to make to the split version that goes into the role book and vice versa

**Comment by venomousbirds** [comment]
wdym

**Comment by McTsts** [comment]
This message is the same as 

https://github.com/McTsts/Werewolves-Roles/blob/main/_categories/how%20to%20play
https://github.com/McTsts/Werewolves-Roles/blob/main/_categories/alignments
https://github.com/McTsts/Werewolves-Roles/blob/main/_rules/alignments/1%20townsfolk
https://github.com/McTsts/Werewolves-Roles/blob/main/_rules/alignments/2%20werewolves

https://github.com/McTsts/Werewolves-Roles/blob/main/_categories/the%20day%20and%20nighttime%20cycle
https://github.com/McTsts/Werewolves-Roles/tree/main/_rules/the%20day%20and%20nighttime%20cycle
https://github.com/McTsts/Werewolves-Roles/blob/main/_categories/conspiracy%20channels
https://github.com/McTsts/Werewolves-Roles/tree/main/_rules/conspiracy%20channels

**Comment by venomousbirds** [comment]
ah, i didn't know, i'll make some PRs on those then and close the issue

**Comment by venomousbirds** [comment]
I can later combine them for the final how to play message

**Comment by McTsts** [comment]
Ah, I thought you knew, but just didn't want to have to combine them when you first made the issue

**Comment by McTsts** [comment]
How to Play got added as the first section of the rule book at some point, and every single text from the rule book is in here. Optimally we could also just generate the how to play message automatically, I can maybe look into it, but it isn't trivial.

https://docs.google.com/document/d/1WeoM3uYWlOb_G8uhJTSeW116m86XwZeJ1zjfES6Jbyw/edit

**Comment by venomousbirds** [comment]
Might be nice to also make a How To Play message command so if anything somehow becomes incorrect again (such as the alignment changes) we can change it more easily

**Comment by McTsts** [comment]
hmm, it could be a good idea, but it might also be less reliable. I was thinking of just making a google doc that generates it like the role book

**Comment by venomousbirds** [comment]
works too
