### ISSUE TITLE
Psychopath Role Loss + Disguise

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#484]
The Psychopath can give itself a permanent disguise. Should this be lost if they lose their role. #12 implies it should probably lose the disguise.

**Comment by ThomasRubycrust** [comment]
I think only Devil, Psychopath and WWW can apply permanent disguises. Devil cannot lose their role and #13 put it into WWW's description that they lose the disguise on role loss.

**Comment by Shepherdwhen** [comment]
I believe shepherd as a limited role can too

**Comment by ThomasRubycrust** [comment]
Sneaking Wolf has it clarified: https://github.com/McTsts/Werewolves-Roles/blob/14148e3c3e1e4762e1dd63b801cbe23aebb0376f/werewolves/miscellaneous/sneaking%20wolf#L6

**Comment by ThomasRubycrust** [comment]
> I believe shepherd as a limited role can too

Oh yeah, you're right.

https://github.com/McTsts/Werewolves-Roles/blob/14148e3c3e1e4762e1dd63b801cbe23aebb0376f/limited/shepherd#L10
