### ISSUE TITLE
Infected Wolf x Reaper x Wraith

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#485]
The reaper cannot turn the wraith sleepless. If an Infecting Wolf hits a Wraith, turning it into a wolf, can the Reaper now use this to figure out that the Wraith has lost their role?

**Comment by Shepherdwhen** [comment]
Similar applies to shepherd and herding dog/sheepdog

**Comment by ThomasRubycrust** [comment]
Actually not, Shepherd has better phrasing there:
https://github.com/McTsts/Werewolves-Roles/blob/14148e3c3e1e4762e1dd63b801cbe23aebb0376f/limited/shepherd#L7

An infected herding dog is still a member of the flock

**Comment by ThomasRubycrust** [comment]
This leads to something that probably deserves another issue. An infected herding dog (wolf) would live lose against Shepherd:
https://github.com/McTsts/Werewolves-Roles/blob/14148e3c3e1e4762e1dd63b801cbe23aebb0376f/limited/shepherd#L3
