### ISSUE TITLE
Cupid x Bitter Hag

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#486]
Is a Bitter Hag that is in love with the cupid a traitor to the hags?

**Comment by ThomasRubycrust** [comment]
This implies hags cant betray each other:
> The Hags do not know each other, but always have the same win condition and alignment.

**Comment by Shepherdwhen** [comment]
Have a Cupid edgecase to make a bitter Cupid maybe?

**Comment by ThomasRubycrust** [comment]
epic, more cupids
