### ISSUE TITLE
Cupid x FP

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#489]
How is a cupid FP couple supposed to work if there's other cupids? I guess the two FP's would need to kill each other, and neither could win even if everyone is enchanted?
https://github.com/McTsts/Werewolves-Roles/blob/14148e3c3e1e4762e1dd63b801cbe23aebb0376f/other/flute/flute%20player#L4

**Comment by ThomasRubycrust** [comment]
The win conditions of a Cupid x FP couple would be the following:

- Townsfolk Base Alignment: Everyone is Townsfolk or Unaligned (Town v UA)
- Flute Player Base Alignment: Everyone is enchanted, unaligned or flute team (Ench v UA v Flute)

Combined: Everyone is Townsfolk or Unaligned and Enchanted, Unaligned or Flute Team; or Cupid Couple (((Town v UA)^(Ench v UA v Flute)) v Cupid Couple)

(((Town v UA)^(Ench v UA v Flute)) v Cupid Couple)
≡ ((TvU)^(EvUvF))vC [Substitution]
≡ (T^E)v(T^U)v(T^F)v(U^E)v(U^U)v(U^F)vC [Distribution]

∀r ∈ Roles . ¬(T ^ U)
∀r ∈ Roles . ¬(T ^ F)
∀r ∈ Roles . ¬(U ^ F)

≡ (T^E)v(false)v(false)v(U^E)v(U^U)v(false)vC
≡ (T^E)v(U^E)v(U^U)vC
≡ (T^E)v(U^E)vUvC

∀r ∈ Roles . (U^E) => U

≡ (T^E)vUvC

All remaining players must be townsfolk and enchanted, unaligned or cupid couple. So, yes the Cupid couple would need to kill the normal FP. 

The normal FP win con means that they'd need to kill or enchant the lover FP, however that brings up an issue with the FP role. Can it enchant the lover FP?
