### ISSUE TITLE
Shepherd x Trickster

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#492]
This specifies that the Shepherd cant steal negative votes. Does this mean the full action (unherding + stealing) fails, or just the stealing?

https://github.com/McTsts/Werewolves-Roles/blob/14148e3c3e1e4762e1dd63b801cbe23aebb0376f/limited/shepherd#L8

**Comment by ThomasRubycrust** [comment]
@Shepherdwhen

**Comment by Shepherdwhen** [comment]
> This specifies that the Shepherd cant steal negative votes. Does this mean the full action (unherding + stealing) fails, or just the stealing?
> 
> https://github.com/McTsts/Werewolves-Roles/blob/14148e3c3e1e4762e1dd63b801cbe23aebb0376f/limited/shepherd#L8

Just the stealing, iirc we talked about it and shepherd gets no extra vote when stealing 0 or less votes but the person stolen gets a free get out of jail card
