### ISSUE TITLE
Vampire Demonization x Plague Death

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#493]
The plague kills so defenses and such are ignored, but the vampire's demonization happens on death, so I'd assume it triggers. (death wasnt avoided, it happened and was the trigger for turning undead?)
https://github.com/McTsts/Werewolves-Roles/blob/14148e3c3e1e4762e1dd63b801cbe23aebb0376f/limited/undead#L3

However, if it does trigger does the plague keep the plague? lose it? 

Are there any other roles that "kill" directly instead of attacking? I can only think of Chef which kills during the day so it wouldn't apply here.

**Comment by ThomasRubycrust** [comment]
This is partially fixed by ad1d478, however I'm unsure how it works with the plague.
