### ISSUE TITLE
Hell 100% Trust

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#5]
It seems like the demonization immunity of Hell (which is required for a 100% trust group) is lost (old edge case sheet)

**Comment by venomousbirds** [comment]
Just finish the edge case sheet and add it back :)

**Comment by McTsts** [comment]
I think it's worth adding to the role description. At least that Demon & Devil cant change role I guess

**Comment by venomousbirds** [comment]
If it's only hell team and we keep it at only hell team, definitely add it to the description of both devil and demon

**Comment by McTsts** [comment]
Yeah, right now I think only Hell team is supposed to have unbreakable trust

**Comment by venomousbirds** [comment]
In that case add it as a last line to the description. 
"Because the Hell team is a trust team, the <Devil/Demon> can't change role throughout the game" or something similar
(assuming we're not keeping thief in mind)
