### ISSUE TITLE
Wolves in Cult

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#50]
Wolves in the Cult cant vote but that's not even possible with the bot (either you cant vote at all or you can everywhere)

**Comment by venomousbirds** [comment]
Is there a chance you could add it to the bot or is that's just very inconvenient? Maybe make private polls private so only gms can see the outcome? (I don't like that solution but it's just a suggestion)

**Comment by McTsts** [comment]
imo wolves should just be able to vote in the cult :)

**Comment by Mjnstag** [comment]
if we do that, maybe we should clarify that in the cult member/leader description

**Comment by McTsts** [comment]
yeah I think we should do that

**Comment by venomousbirds** [comment]
I don't think wolves voting in cult makes sense, but if it can't be changed in the bot there's not really a different option, putting it in the cult descriptions would be good in that case
