### ISSUE TITLE
Add Lone Hell Hound

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#519]
@Shepherdwhen:
> I had a WM idea for a packless wolf like ranger that reveals it's targets role to the pack on death
> We can also always add lbb and lhh

@McTsts:
> I think lbb is kinda stupid
> lhh is a bit more interesting, but incredibly specific

**Comment by MrTurtleJr** [comment]
When would Lone Hell Hound be used?

**Comment by McTsts** [comment]
It specifically only has any value against a WWW.

**Comment by MrTurtleJr** [comment]
A Lone Hell Hound would require two actual Hell Hounds to be in the wolf-pack and would then join the wolf-pack when one of the Hell Hounds were to die?

**Comment by McTsts** [comment]
This was the description of the LHH on MW:

`Lone Hellhound | Werewolf Miscellaneous | Unofficial
Basics
The Lone Hellhound is a normal hellhound except that they aren't part of the wolfpack. When the first member of the wolfpack dies, the Lone Hellhound joins the wolfpack.
Details
There is always more than one hellhound. All the hellhounds have a secret channel where they can communicate with the other hellhounds securely. 
The hellhounds are the werewolf version of bakers.
These werewolves know each other, and they can use and share this information in their battle against the white werewolf.
If a Lone Hellhound betrays the group in any way (by changing alignment or role) the hellhounds are immediately disbanded.`

I don't think it would require 2 HH in the pack. That version joined if any wolf died, but joining the wolfpack when a HH dies would also potentially make sense.

**Comment by cryptidjayden** [comment]
LHH seems like a non-role, to be honest. LW/LWa are already trustworthy when they join the pack. Maybe I'm blind, but I see quite literally no use to it.

**Comment by McTsts** [comment]
It's _barely_ useful. Its use is that the WWW can't attack it.

**Comment by Shepherdwhen** [comment]
It's an Anti WWW thing

**Comment by Shepherdwhen** [comment]
A known wolf that www can't target until it joins

**Comment by cryptidjayden** [comment]
yeah well it still sucks imo

**Comment by McTsts** [comment]
yea its kinda useless

**Comment by ThomasRubycrust** [comment]
I don't think anyone really wants this.
