### ISSUE TITLE
Packless WM

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#520]
@Shepherdwhen:
> More WM packless

@McTsts:
> also I just had an idea for a packless WM. I have a couple of ideas stolen from other games on my mini wolves sheet and one of them was "hollow husk", a wolf without abilities that becomes the first wolf who dies. I never made a role out of it because it wasn't convincing enough, but maybe it could work as a packless wm if we really want one. Basically it'd be a non-lycan non-pack member, that would join the pack when the first pack member dies and become their role, or something like that.

**Comment by cryptidjayden** [comment]
it's fine, but i'm not sure how necessary it is? kinda seems like a niche we'd rarely, if ever, use.

**Comment by McTsts** [comment]
Unsure, but it has a use beyond being used (sounds stupid, but is true) and that is that it isnt immediately known that WM on a partial role list means a pack member.

**Comment by cryptidjayden** [comment]
figured that myself, but i'm not sure it's worth getting that benefit by adding a pretty bland role. i'd want it to have something a little more convincing or memorable than that, something that would make it actually worth using.

**Comment by McTsts** [comment]
consider this an issue to discuss Packless WM ideas in general, not just that one

**Comment by cryptidjayden** [comment]
mhm mhm

**Comment by cryptidjayden** [comment]
had an idea: packless WM that is notified when it is selected as a target/has a non-kill power used on it, and if it's targeted/has a power used on it by a pack member is given that wolf's identity. needs work.

**Comment by ThomasRubycrust** [comment]
Interesting. Does it learn which power?

**Comment by cryptidjayden** [comment]
> Interesting. Does it learn which power?

i'd say yes, helps trustability if it finds wolves i think



> (and it probably can also learn about killing powers - which could happen if it was protected)

maybe a wolf kill would fail on it and it'd learn the attacker, but not a town kill?

**Comment by Shepherdwhen** [comment]
But maybe only pack kills, meaning LWo can still kill it

**Comment by ThomasRubycrust** [comment]
wait a minute, we have never added a packless wolf other than packless wolf or foxes. Fascinating

**Comment by ThomasRubycrust** [comment]
we can use... coyote :)

**Comment by cryptidjayden** [comment]
coyote works, but it might be nice to have a name more in the style of warlock and tanner, to sort of 'complete the set'. not that i can think of any right now

**Comment by ThomasRubycrust** [comment]
I would've suggested something like `Alert Coyote` to leave room for future non-lycan non-pack roles

**Comment by Shepherdwhen** [comment]
It's like a wolf version of Macho so maybe Strongman?

**Comment by ThomasRubycrust** [comment]
That really doesnt sound like a wolf role at all.

**Comment by Shepherdwhen** [comment]
Also I do like the idea of adding Hollow Husk as a Packless wolf

**Comment by cryptidjayden** [comment]
not sure i'm keen on `Alert Coyote`, to be honest. `Strongman` is even worse. (it's also way more like assistant than macho, but assistant is/was a shit name.)

**Comment by ThomasRubycrust** [comment]
`Alert Coyote`  was just meant as an example for `<sth> Coyote`

**Comment by Shepherdwhen** [comment]
Question is if we want it to be Lycan or not, because we could always reuse Packless wolf

**Comment by ThomasRubycrust** [comment]
Packless Wolf is a dumb name and doesn't describe this well. Also packless works well as a general term for non-pack wolves, so I'd rather keep that.

**Comment by ThomasRubycrust** [comment]
I don't see anything wrong with creating a new naming convention which we can use in the future, especially for new roles it will make it clearer for the players. The `lone` and `fox` naming conventions also didn't exist initially.

**Comment by ThomasRubycrust** [comment]
> the problem i have with it is that we then either have to rename warlock and tanner (which i am very against, they're good names and they've been around for absolutely forever), or have them not fit the convention, which would arguably be more confusing than keeping the loose convention we have now.

I dont think they should be renamed. I guess I can kinda see how it would be confusing? But not doing it isn't any less confusing either. The alternative is just to have it be a lycan after all (which barely makes a difference), then it'd be a new type of role and we can introduce the new naming convention.

**Comment by cryptidjayden** [comment]
my only issue would be that it's now vulnerable to aura teller, which i specifically do not want.

**Comment by ThomasRubycrust** [comment]
> that could probably work, introducing the coyote convention. you suggested alert coyote, which works alright imo, but for now we could just call it coyote until we think of/add another non-pack lycan

I don't think we should do that, I think it'd be much better to just give it a proper name to begin with.

**Comment by ThomasRubycrust** [comment]
> my only issue would be that it's now vulnerable to aura teller, which i specifically do not want.

oh right AT works on lycans

**Comment by cryptidjayden** [comment]
sorcerers can do magic and their magic tells them when someone does something to them 🙂 

in all seriousness i am trying to think of better words

**Comment by venomousbirds** [comment]
Of Incredible Feats by Tricks Abracadabra | Werewolf Miscellaneous | Limited

**Comment by cryptidjayden** [comment]
**Bitch Wolf**

**Comment by venomousbirds** [comment]
also no idea what is actually going on in this issue, there's a lot of different suggestions and names etc idk

**Comment by ThomasRubycrust** [comment]
I think for both of those I'd assume its a town role.

**Comment by venomousbirds** [comment]
yeah they both sound like town roles
anything that can be from a minecraft village sounds like a town role

**Comment by ThomasRubycrust** [comment]
I've never complained about Tanner or Warlock before, because Warlock sounds fitting, I guess, and the word Tanner has no meaning to me besides the WWR role.

**Comment by venomousbirds** [comment]
or instead of them being all the same naming convention, its a bit broader
they don't all have to be <whatever> coyote (or whichever convention we use)
instead we could just use wild animals? so coyote, raccoon, any other animal that's wild and isn't fox
so it doesn't feel weird with tanner and warlock being the only ones who don't fit in the naming convention

**Comment by Shepherdwhen** [comment]
Will we stick with canine/carnivores or just wild animals?

**Comment by Shepherdwhen** [comment]
Those are all canidae

**Comment by venomousbirds** [comment]
i like coyote and hyena, they seem fitting
normal raccoons are also carnivores and probably fit better than tanukis

**Comment by ThomasRubycrust** [comment]
Yeah, I think those would both work, though with this I'm unsure what we'd name a lycanless pack member if we want to add one.

**Comment by ThomasRubycrust** [comment]
Are there any wild animal wolf hybrids or something so we could have something like <animal> Wolf

**Comment by ThomasRubycrust** [comment]
Racoonwolf

**Comment by venomousbirds** [comment]
that's not a thing, no

**Comment by venomousbirds** [comment]
i don't think there's recognizable wild animal/wolf hybrids, you'll end up with dog breeds, which don't make sense because we already have Dog

**Comment by ThomasRubycrust** [comment]
Werewolf Man. Its part of the wolfpack but not a lycan (its a man)

**Comment by venomousbirds** [comment]
Manwolf

**Comment by ThomasRubycrust** [comment]
yea exactly, so Werewolf man makes sense, its a man not a werewolf

**Comment by ThomasRubycrust** [comment]
yea Manwolf also works

**Comment by ThomasRubycrust** [comment]
I mean its completely horrible and id veto it

**Comment by ThomasRubycrust** [comment]
its not any better

**Comment by ThomasRubycrust** [comment]
Unemployed Pack Warlock. Its a warlock in the pack without an ability.

**Comment by venomousbirds** [comment]
it's not an actual wolf, it's a human disguised as a wolf

**Comment by venomousbirds** [comment]
Pack Packless Non-Wolf Wolf

**Comment by venomousbirds** [comment]
is there a name for someone who hangs out with wolves

**Comment by ThomasRubycrust** [comment]
Wolf Friend

**Comment by ThomasRubycrust** [comment]
Retired Pack Warlock

**Comment by ThomasRubycrust** [comment]
`Retired Wolf` for Lone Wolf and `Retired Warlock` for Lone Warlock :)

**Comment by cryptidjayden** [comment]
> is there a name for someone who hangs out with wolves

zookeeper

**Comment by ThomasRubycrust** [comment]
I don't really think werewolves are zoo animals. Or at least I'd be very concerned if a zoo's animals consistently murder someone every day.

**Comment by cryptidjayden** [comment]
also a tanner is someone who turns cow hides into leather

**Comment by cryptidjayden** [comment]
yes tsts it was a joke :3

**Comment by ThomasRubycrust** [comment]
I know, basically all of the last suggestions were jokes

**Comment by Shepherdwhen** [comment]
`Pack` could become the term for any wolf that is lycanless in pack
e.g is pack tanner, pack warlock, pack coyote

**Comment by venomousbirds** [comment]
> also a tanner is someone who turns cow hides into leather

wdym thats tanner? tanner is a role that can disguise 2 people every day
idk what youre on about

**Comment by ThomasRubycrust** [comment]
yeah, but that doesnt solve the LWa problem (Pack Warlock implies its a Warlock in pack, when it doesnt have the power of a Warlock)

**Comment by cryptidjayden** [comment]
why cant it just turn into a wolf theres nothing wrong with that :sob:

**Comment by Shepherdwhen** [comment]
> > also a tanner is someone who turns cow hides into leather
> 
> wdym thats tanner? tanner is a role that can disguise 2 people every day idk what youre on about

it tans the cow hide into leather then makes a suit out of the leather, then it paints the name of the role onto the suit and forcces the target to wear it at gunpoint

**Comment by cryptidjayden** [comment]
thats terrifying ethan

**Comment by venomousbirds** [comment]
me and the homies giving out free leather suits

**Comment by ThomasRubycrust** [comment]
hence my epic suggestion of `Retired Warlock` who is a powerless warlock who's enjoying their retirement in the pack

**Comment by venomousbirds** [comment]
i dont think retirement means joining a murder gang

**Comment by ThomasRubycrust** [comment]
well no, but it was just lonely

**Comment by Shepherdwhen** [comment]
> i dont think retirement means joining a murder gang

Fuck now all I can think of is a motorcycle gang full of 70+ year olds

**Comment by ThomasRubycrust** [comment]
Nothing to do and no friends, that sounds like a horrible retirment

**Comment by cryptidjayden** [comment]
are we definitely calling this role coyote? i thought the animal naming convention was for non-pack lycans, this is a non-pack non-lycan

**Comment by ThomasRubycrust** [comment]
> are we definitely calling this role coyote? i thought the animal naming convention was for non-pack lycans, this is a non-pack non-lycan

Coyote was originally intended for a lycanless role anyway. Wild animals logically arent lycans

**Comment by venomousbirds** [comment]
![image](https://user-images.githubusercontent.com/80123992/172643820-83e6c442-3423-404d-94f2-e4dd92263434.png)
does this look like a lycan to you?

**Comment by Shepherdwhen** [comment]
call it lawyer cause it objects to wolves targeting it

**Comment by ThomasRubycrust** [comment]
So keeping Coyote as lycanless makes more sense anyway

**Comment by cryptidjayden** [comment]
im not sure i like it

**Comment by ThomasRubycrust** [comment]
So not the foxes, which are well foxes and not the warlock or tanner who are just evil humans

**Comment by cryptidjayden** [comment]
i feel like keeping the evil human convention is just way easier and avoids getting caught up in lycan-animal-wolf-nonwolf semantics

**Comment by ThomasRubycrust** [comment]
> i feel like keeping the evil human convention is just way easier and avoids getting caught up in lycan-animal-wolf-nonwolf semantics

Yes, but that makes it hard to find a new name

**Comment by ThomasRubycrust** [comment]
Both evil humans and wild animals make sense

**Comment by venomousbirds** [comment]
Evil Ts could be a non-pack non-lycan

**Comment by cryptidjayden** [comment]
i still feel like sorcerer could work imo. has connections to magic/magical protection/magical information, etc

**Comment by cryptidjayden** [comment]
evil sorcerer

**Comment by venomousbirds** [comment]
sorcerer sounds like a town role

**Comment by venomousbirds** [comment]
evil sorcerer sounds like a solo role SOMEHOW

**Comment by cryptidjayden** [comment]
traditionally sorcerers are evil so im not sure if thats just a cultural difference

**Comment by venomousbirds** [comment]
it doesn't sound evil

**Comment by ThomasRubycrust** [comment]
> sorcerer sounds like a town role

In fact we've had Sorceress as a town role before

**Comment by cryptidjayden** [comment]
thats subjective lmao

**Comment by venomousbirds** [comment]
probably because we had sorceress as a town role-

**Comment by ThomasRubycrust** [comment]
> evil sorcerer sounds like a solo role SOMEHOW

I agree, sounds more solo than wolf

**Comment by cryptidjayden** [comment]
uhh outlaw/outcast?

**Comment by venomousbirds** [comment]
> politician? since it pays off wolves not to target it maybe

horrible, stop giving modern day names im gonna cry

**Comment by ThomasRubycrust** [comment]
> politician? since it pays off wolves not to target it maybe

Doesn't fit the vibe imo

**Comment by cryptidjayden** [comment]
yeah i dont like politicisonehjfh

**Comment by venomousbirds** [comment]
politicisonehjfh is a good one tho, i like it, we should name it politicisonehjfh

**Comment by ThomasRubycrust** [comment]
I still think a wild animal would make the most sense

**Comment by venomousbirds** [comment]
coyote or raccoon were good suggestions

**Comment by cryptidjayden** [comment]
i dont like the idea of naming it a wild animal still really im sorry

**Comment by venomousbirds** [comment]
uhhh suffer ig

**Comment by ThomasRubycrust** [comment]
> coyote or raccoon were good suggestions

I think Hyena was good too

**Comment by cryptidjayden** [comment]
🔫

**Comment by Shepherdwhen** [comment]
What about Painted Dog that's another kind of carnivorous wolf like animal

**Comment by cryptidjayden** [comment]
ethan

**Comment by Shepherdwhen** [comment]
for the pack wild animal role

**Comment by venomousbirds** [comment]
hows about we just call it coyote cuz thats probably been namedropped the most

**Comment by ThomasRubycrust** [comment]
You are just wrong. Lycans are by definitions only true wolves.

**Comment by ThomasRubycrust** [comment]
If you think it sounds like a lycan you missunderstood what lycans are

**Comment by cryptidjayden** [comment]
i know what a fucking lycan is ts

**Comment by cryptidjayden** [comment]
please dont condescend to me

**Comment by venomousbirds** [comment]
> jackal also falls in that wolf like catagory

thats a bit far fetched i think

**Comment by ThomasRubycrust** [comment]
> i know what a fucking lycan is ts

Then I dont see why you'd consider it a lycan

**Comment by Shepherdwhen** [comment]
![image](https://user-images.githubusercontent.com/82595414/172646419-f4cc3d12-2ea1-4a5e-ac98-c5ac04c02391.png)

https://en.wikipedia.org/wiki/Caninae

**Comment by ThomasRubycrust** [comment]
Seems like that one would also make sense

**Comment by ThomasRubycrust** [comment]
Yeah it's not very recognizable but it would make sense as well

**Comment by venomousbirds** [comment]
i also dont think it really fits with ww, doesn't give off the vibe as much as coyote etc

**Comment by venomousbirds** [comment]
raccoon fsr sound more ua

**Comment by Shepherdwhen** [comment]
![image](https://user-images.githubusercontent.com/82595414/172647679-1bca803d-3846-491d-9f6f-b944b57a660a.png)
Yeah raccoon is near the bottom near red panda and skunk

**Comment by venomousbirds** [comment]
Skunk sounds like a hilarious ua

**Comment by ThomasRubycrust** [comment]
> well according to the image ethan just sent, coyote is closer to wolf

I meant more for that role specifically with its ability

**Comment by venomousbirds** [comment]
do we already have a role here somewhere then

**Comment by Shepherdwhen** [comment]
> had an idea: packless WM that is notified when it is selected as a target/has a non-kill power used on it, and if it's targeted/has a power used on it by a pack member is given that wolf's identity. needs work.

.

**Comment by Shepherdwhen** [comment]
By Jay

**Comment by venomousbirds** [comment]
oh okay
gives more coyote vibes idk why

**Comment by ThomasRubycrust** [comment]
That one and this one have been discussed here so far:

> also I just had an idea for a packless WM. I have a couple of ideas stolen from other games on my mini wolves sheet and one of them was "hollow husk", a wolf without abilities that becomes the first wolf who dies. I never made a role out of it because it wasn't convincing enough, but maybe it could work as a packless wm if we really want one. Basically it'd be a non-lycan non-pack member, that would join the pack when the first pack member dies and become their role, or something like that.

**Comment by ThomasRubycrust** [comment]
idk much about coyotes and hyenas so ill trust your judgement

**Comment by venomousbirds** [comment]
![image](https://user-images.githubusercontent.com/80123992/172648659-62347d23-c0f8-4c77-ab3f-1ad23dcb9332.png)
fuckers look cool, thats for sure

**Comment by Shepherdwhen** [comment]
coyotes are from America and are closely linked to Native Americans

**Comment by Shepherdwhen** [comment]
iirc Jakals are from Eurasia and parts of Africa, Anubis the god of Death was a Jackal

Hyena are African and they Scavenge dead corpses/carrion

**Comment by venomousbirds** [comment]
im not sure what that has to do with the roles

**Comment by venomousbirds** [comment]
i just know coyotes are very packminded but the others might be too

**Comment by Shepherdwhen** [comment]
idk maybe like the vibes of the animals
this name is likely to be the one that avoids wolves so it has to be the sneaky one

**Comment by Shepherdwhen** [comment]
> Jackals may occasionally assemble in small packs, for example, to scavenge a carcass, but they normally hunt either alone or in pairs.

> The spotted hyena, though it also scavenges occasionally, is an active pack hunter of medium to large sized ungulates

>  It is highly flexible in social organization, living either in a family unit or in loosely knit packs of unrelated individuals. (Coyote)

**Comment by venomousbirds** [comment]
coyote sounds good for the one that joins the pack

> Basically it'd be a non-lycan non-pack member, that would join the pack when the first pack member dies and become their role, or something like that.

**Comment by McTsts** [comment]
that one would probably need to be named `Lone Something` though

**Comment by Shepherdwhen** [comment]
Lone Novice/Recruit/Trainee/Rookie

**Comment by venomousbirds** [comment]
i dont think it makes sense
fpa still has Flute in it
the Lone prefix doesn't sound good with any random role name, its gotta be wolf related
the suggestions sound like town or ua and it's too similar to apprentice, which we removed

**Comment by McTsts** [comment]
yeah I agree, while we only use Lone for wolves, thats not enough to make it a wolf sounding name

**Comment by cryptidjayden** [comment]
lone coyote is pretty good for the wolfpprentice i think

**Comment by cryptidjayden** [comment]
i still prefer something more along the lines of warlock/tanner (sorcerer was previously discussed but i think vetoed (sobbing)) for the asswolf but jackal i could accept

**Comment by McTsts** [comment]
I barely know what we're discussing here at this point

**Comment by ThomasRubycrust** [comment]
Split both ideas from this issue into separate issues because this issue is incomprehensible.
