### ISSUE TITLE
Chef Edge Case

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#524]
WWRD 31/0 is not mentioned anywhere (a dead chef can still send out food)

**Comment by McTsts** [comment]
I suggested the Chef food sending happens at "Start Day" a new position in the event order after end night consequences

**Comment by ThomasRubycrust** [comment]
This is actually implied by the role description:
> At the beginning of each day

But then later overwritten by:
> Making food and selecting a customer is an end-night ability.

I suspect we were aware of this edge case, and originally didn't have the latter of the two sentences, but then at some point added it for clarity and didn't realize it caused the edge case.
