### ISSUE TITLE
Change or remove this sentence from the wolf cub description

### ISSUE THREAD

**Issue by MeuhueM** [McTsts/Werewolves-Roles#528]
**"This is useful in scenarios where they want to kill runners or players who may have been demonized."**
I don't think this sentence really adds anything to how the wolf cub works. It just makes the description a bit lengthier.

**Comment by McTsts** [comment]
Yeah, you're probably right. Do you want to make a PR for it so you get the credit for change?

**Comment by MeuhueM** [comment]
You can do it, I have no clue how to, honestly!

**Comment by McTsts** [comment]
If you want to try doing it yourself you should be able to try editing the file, it will then create a fork. You complete the edit and it should then allow you to make a PR afterwards.
