### ISSUE TITLE
Cupid & UA couple

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#541]
What alignment does a Cupid UA couple have? (so e.g. Cupid & Angel could either win with Angel or with town)
Are they town aligned? unaligned? something special?

**Comment by ThomasRubycrust** [comment]
I'm genuinely not sure what to do here, that's a super weird edge case. They have like a dual alignment, one of which is not being aligned.

**Comment by venomousbirds** [comment]
doesnt really make sense for them to town aligned, in mini wolves we generally make them win with ua, so maybe something along those lines?
eg
Cupid+Angel would win with angel ascension

**Comment by ThomasRubycrust** [comment]
The behaivor for this has always (afaik) been that UA/Cupid can either win with Town (cupid's base win con) or with the UA's win con. I think this is noted specifically in the Cupid description and used to be part of the old edge case sheets.

Cupid + Angel either ascend both when Angel is lynched, or win with town

**Comment by ThomasRubycrust** [comment]
I think the conclusion probably is that they _are_ Townsfolk aligned, but just have an additional alternative win condition that doesnt affect their alignment (as that win con is an UA one)

**Comment by venomousbirds** [comment]
I'm always confused why cupid is base townsfolk aligned but sure
> Cupid + Angel either ascend both when Angel is lynched, or win with town
this would work

**Comment by ThomasRubycrust** [comment]
This issue wasn't really about when they win (this is already defined), but instead what we should consider the alignment of such a couple, but I think just Townsfolk is the easiest answer.

Cupid is Townsfolk aligned to guarantee that it's existence is an advantage for the townsfolk team, whereas a role like LA can help any team.
