### ISSUE TITLE
Reaper & Zombie

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#557]
If the Reaper bites an already sleepless player, do they become a Wraith?

**Comment by venomousbirds** [comment]
wouldnt reaper need to bite twice to create a wraith?

**Comment by ThomasRubycrust** [comment]
I actually figured it out. This _is_ defined already. Role changes are replaced by strongly disguising people, so the bitten player would simply be disguises as a Zombie, but that's kinda lame.

I'll make a PR later to allow direct recruiting (Zombie,InfWolf) - it doesnt really affect games other than this, so it should be fine
