### ISSUE TITLE
White Werewolf issue

### ISSUE THREAD

**Issue by Shepherdwhen** [McTsts/Werewolves-Roles#582]
There is currently a line in the WWW that states it appears as a regular wolf, could make players think it appears only as the role Wolf if they skim read the description

[https://github.com/McTsts/Werewolves-Roles/blob/main/other/solo/white%20werewolf](url)
> To the werewolves, the White Werewolf will appear to be a regular wolf. However, it is the White Werewolf’s goal to win the game completely alone; even the other werewolves must die.

**Comment by McTsts** [comment]
oh I see what you mean

**Comment by Shepherdwhen** [comment]
probably change "regular wolf" to "member of the pack"
