### ISSUE TITLE
Coroner should be affected by strong disguises

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#587]
![image](https://user-images.githubusercontent.com/24660095/170082570-3da9029d-7229-47cb-93bd-499762e5951f.png)

Coroner is the only one that doesn't follow the system and I hadn't noticed until now

_Originally posted by @McTsts in https://github.com/McTsts/Werewolves-Roles/pull/585#issuecomment-1136130646_

**Comment by Shepherdwhen** [comment]
> ![image](https://user-images.githubusercontent.com/24660095/170082570-3da9029d-7229-47cb-93bd-499762e5951f.png)
> 
> Coroner is the only one that doesn't follow the system and I hadn't noticed until now
> 
> _Originally posted by @McTsts in [#585 (comment)](https://github.com/McTsts/Werewolves-Roles/pull/585#issuecomment-1136130646)_

Coroner works similar to Devil Wager role reveal

As in the role of the recipient that devil learns when you check a player

**Comment by McTsts** [comment]
That's kind of true. The Devil's Invest could be considered to be similar to that, but I think it's fine where it is because Devil's Wager definitely belongs there, and since the Devil executes the wager action it makes sense that the Devil handles both of the invests in exactly the same way.

**Comment by cryptidjayden** [comment]
i don't understand the diagram, but coroner being affected by disguises adds nothing to the game imo. it's not investigating roles, it's investigating kills. i'm sure your diagram accounts for that, but i still just don't get it.

**Comment by McTsts** [comment]
> i don't understand the diagram, but coroner being affected by disguises adds nothing to the game imo. it's not investigating roles, it's investigating kills. i'm sure your diagram accounts for that, but i still just don't get it.

Good point
