### ISSUE TITLE
Wraith is just... kinda weak

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#595]
**Promotes**
Flute Apprentice
Wisp
Plague Carrier
Corpse
**Has Powers Itself**
Bat
Demon
Herding Dog
**Gains Additional Powers**
Ice Queen

**kinda nothing**
Wraith

_Originally posted by @ThomasRubycrust in https://github.com/McTsts/Werewolves-Roles/issues/594#issuecomment-1137325944_

**Comment by ThomasRubycrust** [comment]
On the other hand Reaper can be OP, but I don't think that's a justification.

**Comment by Shepherdwhen** [comment]
Yeah I don't think it's justification as it can be super weak

reaper balance all depends on the role list and number of roles/players
