### ISSUE TITLE
Buff Stalker

### ISSUE THREAD

**Issue by rupertandrosy** [McTsts/Werewolves-Roles#599]
stalker lowkey fucking sucks balls. it's easy to confirm and communication is good, but incredibly weak outside of that, and as such never gets used - it's kind of like a weaker grandma. either scrap the role or buff it. a name change would also free up stalker to be used for the proposed ? WI role

**Comment by McTsts** [comment]
Stalker is just pretty niche, it aims to make it so a town minority can get a vote majority which is very rare in our games.

**Comment by Shepherdwhen** [comment]
Idt I've ever seen stalker, and even if I have it wasn't memorable

**Comment by Shepherdwhen** [comment]
As Jay said it's just grandma that sucks

**Comment by cryptidjayden** [comment]
yeah, grandma already kinda fills that niche. i personally would never consider using it, clearly ethan wouldn't either. there's no point in it existing right now.

**Comment by McTsts** [comment]
I get your point but im attached to invisible votes :(

**Comment by venomousbirds** [comment]
isn't stalker like a classic role or something? we've used it before and im not sure why we should remove it.

**Comment by McTsts** [comment]
yeah its a really old role, one advantage it has over grandma is that it doesnt as easily reveal who it is, but even thats not a huge issue for Grandma

**Comment by cryptidjayden** [comment]
we should remove it/buff it because it doesn't do anything right now. i can't actually think of a situation in the current server where stalker's "primary" ability, its votes, came in useful. only its ability to whisper has really helped.

**Comment by cryptidjayden** [comment]
i wouldn't have suggested removing it if not for the fact we want to use the name for #585

**Comment by McTsts** [comment]
Yeah I'm fine with removing it for now, but I'd like to bring back a similar role at some point

**Comment by cryptidjayden** [comment]
fine w/ me

**Comment by Shepherdwhen** [comment]
The only one I can think of is the stalker has no whisper and no vote themselves however their target each night will gain one extra vote if the stalker chooses the same option as them on the poll

**Comment by Shepherdwhen** [comment]
I mean the main problems I see with stalker is

It's only real use is when town loses majority

It adds votes to both the lynch and election

Adding both these factors together if wolves know there is a stalker they just have to vote what town vote on the polls but reversed and town is denied an elected role or the town elected role is lynched

**Comment by cryptidjayden** [comment]
what if, instead, each night the stalker chooses a player and can either set their public vote value to 2 or -1?

**Comment by ThomasRubycrust** [comment]
Stalker was more useful in the older style games where votes where often heavily split. Perhaps we could try it in one of those games.

**Comment by ThomasRubycrust** [comment]
Stalker isn't easily fakable, but it might also not want to reveal itself publicly

**Comment by ThomasRubycrust** [comment]
> Stalker was more useful in the older style games where votes where often heavily split. Perhaps we could try it in one of those games.

On a only slightly related note, I do miss the thing from the older games where everyone could really play, whereas now its often that very quickly a small confirmed group of townies form and everyone else just has to listen to them

**Comment by cryptidjayden** [comment]
i agree - my favourite part of traditional mafia is having to rely more on reads (which i am very bad it), rather than having 'solvable' games. mafia achieves this by using much simpler and weaker roles, but having much larger town majorities - could be fun to try bring back in the style of the old games. however, i think our current playerbase quite likes the more complex roles, so we'll have to see if it's popular.

**Comment by ThomasRubycrust** [comment]
Complex roles are fine, what breaks it the most imo is easily confirmable weak roles (e.g. bakers). If they claim they'll know they might die, but that's their only point. If the only confirmable roles are more powerful, it makes it much more difficult.

**Comment by ThomasRubycrust** [comment]
Bakers were weaker in the old games because there were so many wolves that fake claiming Baker was less risky.

**Comment by McTsts** [comment]
I think a relatively small and inoffensive Stalker buff could be making it an immediate day effect, than it has more flexibility

**Comment by venomousbirds** [comment]
idk where this went so uh whats the point of this one again?

**Comment by McTsts** [comment]
According to @cryptidjayden Stalker is underpowered and just a weaker grandma

**Comment by McTsts** [comment]
and its kinda true

**Comment by venomousbirds** [comment]
hm we havent used it in a while, maybe we can host a game with it and see how horrible it actually is? i dont think there's much wrong with it honestly but maybe that'll change after a game?

**Comment by McTsts** [comment]
I don't think there's much wrong with it. It's just a weaker grandma
