### ISSUE TITLE
Oracle should not be affected by disguises

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#6]
"solo" - this is unclear

"disguises" - weak or strong?

**Comment by venomousbirds** [comment]
Oracle already mentions solo roles as not having the same alignment now
I think oracle should be like most other ti, influenced by weak disguises and obstructions

**Comment by McTsts** [comment]
From the S5 role book changelog:

> • Oracle
  ‣ The Oracle is no longer affected by weak disguises
  ‣ This was unintentional and has been fixed
