### ISSUE TITLE
Flock Team Kinda Weak + Needs Fixing

### ISSUE THREAD

**Issue by Shepherdwhen** [McTsts/Werewolves-Roles#600]
We need to decide if Shepherd can gain as many votes as it wants or one a day, the original intention was as many as it wants but that was decided to be too strong, so it was nerfed.

A buff could be that the Herding dog can as an end night ability, herd one tagged player, like how the reaper has a built-in sleepless to guarantee one sleepless a night.

The Shepherd also needs to know who is herded and unherded, for consistency I think the shepherd should learn who is currently herded each phase change/who is newly herded when they get herded.

**Comment by Shepherdwhen** [comment]
Maybe change the Buff to being shepherd just for consistency with other solo teams

**Comment by Shepherdwhen** [comment]
@McTsts or @ThomasRubycrust  you suggested buffs to shepherd, any thoughts?

**Comment by ThomasRubycrust** [comment]
Unsure, but I think I'll need to see it in a more normal game.

**Comment by Shepherdwhen** [comment]
Capped votes make sense
