### ISSUE TITLE
Wraith votes

### ISSUE THREAD

**Issue by venomousbirds** [McTsts/Werewolves-Roles#612]
> wraith recruiting should remove wraith vote

@McTsts

**Comment by ThomasRubycrust** [comment]
I think we should severely limit (but not remove) Reaper recruiting + add a new role instead. 

What I'd suggest is that they only get powers like the vampire demonization when the *last* member of the team dies. That way they can only use it once. There should be an equivalent of Undead (Wraith is more of a Bat equivalent than an Undead one)

**Comment by Shepherdwhen** [comment]
I think all Extra wraiths should die when reaper does too, it adds more of a risk to the reward of new wraiths

**Comment by Shepherdwhen** [comment]
Or whatever they're going to be

**Comment by venomousbirds** [comment]
> I think all Extra wraiths should die when reaper does too, it adds more of a risk to the reward of new wraiths

horrible suggestion, its not neccesary to put so much pressure on reaper for basically no reason. wraith recruiting was only really a thing in a game as os7d and i dont think this will even be relevant if future games arent as insane
