### ISSUE TITLE
Reporter UA?

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#625]
I haven't even seen this role before, but I really like the idea of an ua for every election. Problem is that Guardian doesn't happen much so it's another role that is best put in larger games
The nightly ability definitely does help to make it more interesting

_Originally posted by @venomousbirds in https://github.com/McTsts/Werewolves-Roles/issues/474#issuecomment-1117283010_

**Comment by cryptidjayden** [comment]
having a reporter-ascension UA with an ft-like mechanic could be interesting - if town don't give it reporter, it has incentive to team up with wolves.

**Comment by ThomasRubycrust** [comment]
oh yeah, I guess FT power would make the most sense for a reporter ascension ua

**Comment by cryptidjayden** [comment]
question is what would be its ascension consequences? despot cancels the next election, angel cancels lynch, but having another election cancel is lowkey very boring.

**Comment by cryptidjayden** [comment]
maybe, like, anyone who dies between the ascension and the next election doesn't have their role revealed in the reporter channel

**Comment by cryptidjayden** [comment]
yeah, that's my problem with it too.

**Comment by cryptidjayden** [comment]
> > question is what would be its ascension consequences? despot cancels the next election, angel cancels lynch, but having another election cancel is lowkey very boring.
> 
> I dont think that would do much, I was thinking everyone that voted for them would have their role revealed, but thats probably way too powerful.

like angel's one kill, a ranger-style role reveal of one voter?

**Comment by ThomasRubycrust** [comment]
I think that's too weak. A reveal is much less worse than a kill

**Comment by cryptidjayden** [comment]
i think that kinda works, or just have a set amount (3? 5?) be revealed

**Comment by McTsts** [comment]
I think what I said would probably be better than a set amount.

**Comment by cryptidjayden** [comment]
i agree. i think either 1/4 or 1/5 of (living?) players

**Comment by 12Metatron** [comment]
> maybe, like, anyone who dies between the ascension and the next election doesn't have their role revealed in the reporter channel

This one seems best to me

**Comment by ThomasRubycrust** [comment]
Does anyone have a name suggestion?

**Comment by McTsts** [comment]
Is this necessary?

**Comment by McTsts** [comment]
Closing this for now. If anyone is interested in a Reporter UA please reopen. Personally, I'm not convinced this is necessary.
