### ISSUE TITLE
WWW clarification

### ISSUE THREAD

**Issue by venomousbirds** [McTsts/Werewolves-Roles#630]
What if there are no WM roles? 
Is an arbitrary WM role picked or does the WWW not gain a disguise?

**Comment by cryptidjayden** [comment]
the only problem i can see this having is forcing the www into a claim they almost certainly won't be able to prove. it might be better to give them the ability to choose their disguise D0/N1 like devil

**Comment by McTsts** [comment]
They gain the power of the role they're imitating, so they can always prove it.

**Comment by McTsts** [comment]
> Good question, I dont think this has been considered. Maybe we just extend the WWW imitation power to all wolfpack roles? Generally in a WWW game the most common role is always WM, so this would only allow more possibilities than before I think.

Anyone have an opinion on this?

**Comment by Mjnstag** [comment]
yea i think that would be a good idea
