### ISSUE TITLE
WWW Team

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#633]
Have we ever considered just having WWW be part of the white wolf team or something? RN if a WWW is copied there's two WWWs, which just sucks for everyone, the wolves, the original WWW and the new WWW. We could instead just let them join and have them keep the same amount of kills as a single WWW. Seems way more balanced.

**Comment by ThomasRubycrust** [comment]
The only downside I see is, that then we can't have two WWWs at the same time, which idk if we do that, like ever. And rn its just inconsistent that WWW is the only solo without a team.

**Comment by Shepherdwhen** [comment]
I had an idea for a non pack who can win solo but also wins if www wins

The silver fox

Each day they target a player, if the player is pack they're attacked, if not they're not attacked

The WWW(s) learn who the silver fox is attacking

The silver fox mimics a fox in the game

**Comment by ThomasRubycrust** [comment]
This just seems like a pretty bad suggestion overall:
- If it was a WWW Copy Case that teams with the WWW they'd just inform the WWW (learning all pack members) meaning its just a packless/buffed WWW
- Even without that it still increases the amount of WWW kills (which isnt particularly good), with the limitation being that you hope they don't actually figure out who's in the pack (a pretty bad limitation)
- A packless wolf doesnt really have any hope of distinguishing between a WWW or normal Wolf meaning this just encourages team killing

**Comment by venomousbirds** [comment]
I'm not sure if www needs a team
but the issue that a www can be copied (meaning a new www is created who knows the other www and can easily target that one with its kill)
maybe just straight up let them join the channel but still only give them 1 kill? would just be a lookalike case?

**Comment by ThomasRubycrust** [comment]
> I'm not sure if www needs a team but the issue that a www can be copied (meaning a new www is created who knows the other www and can easily target that one with its kill) maybe just straight up let them join the channel but still only give them 1 kill? would just be a lookalike case?

This is exactly the suggestion. If they join together however they are a team, so we might as well define WWW as having a team (instead of it being the only teamless Solo) to begin with.

**Comment by venomousbirds** [comment]
well its only an edge case, its not supposed to have a teammate at the start of the game (for example, putting 2 wwws would still make it 2 solo teams) 
i do think www being completely solo adds more to the game than _yet another solo team_

**Comment by ThomasRubycrust** [comment]
> well its only an edge case, its not supposed to have a teammate at the start of the game (for example, putting 2 wwws would still make it 2 solo teams) i do think www being completely solo adds more to the game than _yet another solo team_

But do we ever want that though? I'd prefer to have a better solution for the copy edge case, which for me seems like it'd be more "common". There is no other role without a team, so I just find it kinda strange and inconsistent. Whether it's defined as a team or "completely solo" has effectively no impact on the game, so I don't think it adds anything.

**Comment by ThomasRubycrust** [comment]
Here's what I mean. I'm not suggestion to give the WWW a team with other people or roles. Just to define it as a team mainly for consistency

**Comment by venomousbirds** [comment]
its confusing to say youre not giving it a team and also you are giving it a team. It's solo solo
giving www a team (team meaning that everyone on that team wins together and works together, not "the name of a category") makes it sound like it will work together with all other wwws, which doesn't make sense.

**Comment by McTsts** [comment]
But they can work together, you even said so.

**Comment by venomousbirds** [comment]
only when copied, as its a special case. not when you put 2 wwws at the start of the game

**Comment by McTsts** [comment]
Which we have done in which games?

**Comment by venomousbirds** [comment]
copied a www or put 2 wwws in one game?

**Comment by McTsts** [comment]
Put 2 wwws in one game.

**Comment by McTsts** [comment]
I don't remember this ever happening in a proper game, whereas LA/www seems far more common

**Comment by venomousbirds** [comment]
still dont think we need to give www a team, its unneccesary and everything is fine like it is rn, even LA/www barely happens so there being 2 wwws is such a small chance that it can be disregarded. i dont think it needs a solo category (giving it a team will also probably get people to add it to games as a team)

**Comment by McTsts** [comment]
so.. we agree its not very significant, so changing it for consistency shouldn't be an issue?

**Comment by venomousbirds** [comment]
it's not significant so it doesn't need to change is my view on it

**Comment by McTsts** [comment]
It doesn't _need_ changing, but I'd like to change it because it bothers me
