### ISSUE TITLE
New Corrupt Wolf/Fox(?)

### ISSUE THREAD

**Issue by cryptidjayden** [McTsts/Werewolves-Roles#639]
my intention was that it doesn't apply votes to a player, but gives them more (or fewer) votes. now i think about it more, it's a bit too much like grandma for my liking, so probably disregard it anyway. maybe it could make for a fun wolf role though instead of corrupt

_Originally posted by @cryptidjayden in https://github.com/McTsts/Werewolves-Roles/issues/599#issuecomment-1144930142_

can change a player's PubVV to 2 or to -1

**Comment by ThomasRubycrust** [comment]
oooh, that's very interesting. That also means it significantly affects games its _not_ in which is always interesting. Would it have whispers as well?

**Comment by cryptidjayden** [comment]
hadn't considered that, do you think it should?

**Comment by ThomasRubycrust** [comment]
I think a whispers wolf could be nice, a while ago we had Blackmailer (#384) but unfortunately it was bad :(

**Comment by cryptidjayden** [comment]
hell yeah. do we keep the corrupt wolf name? seems like it works

**Comment by ThomasRubycrust** [comment]
I mean we still have #592 open..

**Comment by ThomasRubycrust** [comment]
However the name would fit.

**Comment by cryptidjayden** [comment]
vera has said they'll check through 592 when they're available. if they decide not to delete cw, maybe something to do with bribes?

**Comment by venomousbirds** [comment]
can i get a role description of this before i do something with #592?

**Comment by McTsts** [comment]
This would go well with a change to voting (or basically stalker): make it so people need to have at least one person vote for them, for their votes to show up. Makes it slightly harded to proof Stalker (though this role still couldnt be used to fake it, as that would require 3 votes))

**Comment by cryptidjayden** [comment]
that could work imo

**Comment by venomousbirds** [comment]
maybe not a whisper channel idk, but its a nice change to corrupt wolf

**Comment by cryptidjayden** [comment]
this can be made into a pr now. @McTsts should do that probably

**Comment by venomousbirds** [comment]
i can do it

**Comment by cryptidjayden** [comment]
based vera
