### ISSUE TITLE
Psychopath: disguise

### ISSUE THREAD

**Issue by Mjnstag** [McTsts/Werewolves-Roles#65]
It doesnt say whether the disguising is immediate or not, so we probably should change that

**Comment by McTsts** [comment]
It's definitely immediate, even has the emergency thing, but yeah we somehow forgot to put that it's immediate.

**Comment by venomousbirds** [comment]
if it has the emergency thing it's immediate

**Comment by McTsts** [comment]
Yeah, it's just not explicitly mentioned and we try to do that everywhere

**Comment by venomousbirds** [comment]
i added it
