### ISSUE TITLE
Lone Wolf is bad

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#674]
its badly designed, i will elaborate another time

**Comment by ThomasRubycrust** [comment]
Lone Wolf originally didn't have the thing where it died if it attacked another wolf, however at some point we thought LW to be too overpowered and we didn't like how LW would just attack randomly and risk hitting a wolf. To stop that we added the thing where LW also dies to make the LW not attack, but I don't think that's a good fix. In the last game I figured that the threat of death was only there to make me not attack and that by attacking randomly I'd still have a very high chance of success, so I did it and it was definitely worth it. But all of that just isn't particularly good.
