### ISSUE TITLE
Idiot

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#685]
https://github.com/McTsts/Werewolves-Roles/blob/adf59d2fa98fd2b599b6d8c5d596deb0a0330b46/townsfolk/miscellaneous/idiot#L3

This specifies on death, but this isn't possible according to how Blocks work

**Comment by venomousbirds** [comment]
Do you mean it should be on first attack?

**Comment by McTsts** [comment]
Idiot is intentionally on first death (bc of lynch and such), but blocking death is only allowed using role changes according to the rules

**Comment by venomousbirds** [comment]
Are there any role conflict if we edit the rules to allow blocking death by idiot?

**Comment by ThomasRubycrust** [comment]
Yeah, Runner and Scared Wolf are the same type of block (3)
https://github.com/McTsts/Werewolves-Roles/blob/ccff3adf19e75a31876ccf08f53e82efa5c0269a/_rules/attacks/3%20blocks#L4-L9
