### ISSUE TITLE
Barber Reveal

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#7]
should barber be revealed if the target escapes (is that possible?)

**Comment by venomousbirds** [comment]
I don't think anything can escape day attacks?

**Comment by McTsts** [comment]
I feel like somehow this happened to me before on Mini Wolves but I can't think of what it could've been

**Comment by venomousbirds** [comment]
It has happened on mini wolves but I don't think it should have been the case?

**Comment by McTsts** [comment]
Oh was it a Devil escaping (when it shouldnt be able to)?

**Comment by venomousbirds** [comment]
Might have been that, yeah, but I think we should clarify somewhere that day attacks can't be avoided

**Comment by McTsts** [comment]
Could happen with #78
