### ISSUE TITLE
Role Suggestion: Alcoholic

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#732]
The Alcoholic spends every night at the tavern so they are immune to all attacks (as they arent home), but can still die by other means. At the end of the first night without a living Bartender the Alcoholic dies.

A role to allow a balanced Bartender. With an Alcoholic (or the possibility of one) ingame the Bartender cant immediately reveal and gather claims or risk losing a powerful town role.

**Comment by cryptidjayden** [comment]
makes sense to me

**Comment by McTsts** [comment]
PR was created for this: #737

**Comment by McTsts** [comment]
This is the role description so far:

**Alcoholic** | Townsfolk Miscellaneous
__Basics__
The Alcoholic spends the night drinking at the tavern and is thus absent for any attacks on them.
__Details__
During the night, the Acoholic is fully immune against all attacks targeting them, though they may still be killed by other means.
The Alcoholic cannot exist without a bartender, and loses their power as soon as the bartender dies. The Alcoholic dies at the end of the first night without a living Bartender.

__Simplified__
At night, the Alcoholic is immune against all attacks, but dies when the Bartender dies.
