### ISSUE TITLE
Role Suggestion: Flute Charmer

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#733]
see discord

**Comment by cryptidjayden** [comment]
it's called a sugestion bc the flute team sure do be sugging on their "instruments"

**Comment by cryptidjayden** [comment]
anyway, the original flute charmer is about investigating enchanted people, which i've already proved in #735 isn't actually that useful. how about having charmer choose an enchanted player each day, and adopt their role as a strong disguise during the next night? they wouldn't be able to choose the same person twice, which is why i say strong, bc then fc can still be found by multiple checks very easily - if game controllers feel they can waste that check resource :)

**Comment by McTsts** [comment]
That seems interesting

**Comment by cryptidjayden** [comment]
thanks bestie

**Comment by 12Metatron** [comment]
if its a disguise, then I assume that means they would learn what the disguise is, meaning they learn the role of their target?

**Comment by Shepherdwhen** [comment]
another thing we could do is make the flute charmer have the old FPA power of joining the enchanted chat

**Comment by cryptidjayden** [comment]
> if its a disguise, then I assume that means they would learn what the disguise is, meaning they learn the role of their target?

could go either way, both are interesting

**Comment by 12Metatron** [comment]
> How would we be using this role? As a replacement for FPA or FP or as a third role?

i was thinking a third role or an alternate second role

**Comment by McTsts** [comment]
When using it as a second alternate role we run into the issue that it can be left alone when the main FP dies, which we've been trying to avoid.

**Comment by McTsts** [comment]
Uh well what I mean is that we dont want a role to be leftover with no method of getting closer to their win condition.

**Comment by 12Metatron** [comment]
> Uh well what I mean is that we dont want a role to be leftover with no method of getting closer to their win condition.

no part of the role desc was that it turns into fp when there are no fp left

**Comment by McTsts** [comment]
Oh, I see

**Comment by McTsts** [comment]
I'm not sure how much use they could actually get out of this sort of almost uncontrolled disguise, thinking about it the disguise variant may be less useful than the invest one even

**Comment by 12Metatron** [comment]
maybe a way to make the invest part useful would be... if the person they targeted/charmed that night will silently fail any attempts to attack a member of the flute team until the next night (attack failed message)

**Comment by 12Metatron** [comment]
> maybe a way to make the invest part useful would be... if the person they targeted/charmed that night will silently fail any attempts to attack a member of the flute team until the next night (attack failed message)

maybe this or it could disguise the target as a flute player, like a tanner

**Comment by McTsts** [comment]
Hm thinking about it, disguising others as FP sounds very much like something that fits with how Flute team works

**Comment by McTsts** [comment]
How about: The Flute Charmer may charm one player each night, strongly disguising them as a Flute Player. When a charmed player is enchanted the disguise is removed.

**Comment by McTsts** [comment]
This would I think be a fairly powerful ability that helps the flute team hide from town. Doing anything with disguises on enchanted players would be kinda pointless as they obviously cant be FP anyway

**Comment by McTsts** [comment]
I'm just not sure if the investigation is particularly useful besides for leaking them in #enchanted which I think just would kinda suck

**Comment by McTsts** [comment]
Investigating people with the goal of leaking them to get them killed is just kinda bad? On the other hand flute team can lie as well so idk

**Comment by 12Metatron** [comment]
> Investigating people with the goal of leaking them to get them killed is just kinda bad? On the other hand flute team can lie as well so idk

since in this new version they charm people who aren't enchanted, it at least helps them find TI to enchant. though that could be too strong

**Comment by McTsts** [comment]
Hm good point. You're right I do think investigating non-enchanted players is definitely better than investigating enchanted ones.

**Comment by McTsts** [comment]
I don't think it would be _too_ strong. It'd be pretty strong, but flute team isn't all that powerful as it is, so we should be fine. (Especially since we'd keep FPA as the weaker secondary role anyway)

**Comment by McTsts** [comment]
> **Captain Luffy**: modified role idea:
> 
> * Can investigate (charm) the role player every night (or maybe at day). Instant.
> * Affected by strong disguises.
> * charmed players are diguised as flute player until they become enchanted
> * flute apprentice is always weak disguised as flute player (so they appear as the same role as people they charmed)
> * Becomes flute player when all flute players are dead

So I think this would be worth writing out as a full description. The only thing that we may want to drop is the Flute disguise. I think it would make sense for it not to exist and it may be more balanced without it. For a FlC to exist there must be a FP anyway so the disguise on others is still guaranteed to be useful for the team.

**Comment by McTsts** [comment]
Yeah it should probably be handeled like other solo effects. When the flute team loses all charmed players are no longer disguised.

**Comment by 12Metatron** [comment]
> The only thing that we may want to drop is the Flute disguise.

you're right. they can target themselves to add the disguise anyways. So no need to have it by default

**Comment by McTsts** [comment]
OOH good point I didn't even consider that, but that can be a thing

**Comment by McTsts** [comment]
> OOH good point I didn't even consider that, but that can be a thing

quote test

**Comment by 12Metatron** [comment]
will write a full desc now. just need to figure out if its a day or night ability

**Comment by McTsts** [comment]
Unsure which is better actually. Disguises are usually day actions, but this does feel more like it should be a night action.

**Comment by 12Metatron** [comment]
**Flute Charmer** | Solo Power - Flute Team | Limited
__Basics__
The Flute Charmer is a Flute Player that can’t enchant other players; instead, they have the ability to charm one player each day, learning their role and disguising them as Flute Player. The Flute Charmer becomes a Flute Player if none remain.
__Details__
During the day, the Flute Charmer may charm a player, the charmed player is not informed about this. This action is immediate. 
Successfully charming a player will tell the Flute Charmer their targets role. This result is affected by strong disguises, redirections, and obstructions. Additionally, the charmed player will be weakly disguised as Flute Player.
If a player currently has, or later gains the enchanted status, then the charmed status is removed.
The Flute Charmer can target themself or other members of the flute team.
If no Flute Players remain, the Flute Charmer turns into a Flute Player and loses their current powers.
When the flute team is disbanded, the charmed status is removed from all players.

__Simplified__
The Flute Charmer becomes a Flute Player if none remain.
Additionally, once per day, the Flute Charmer can learn the role of a player and disguise them as Flute Player.

**Comment by McTsts** [comment]
Sounds good, make it a PR by creating a file (via Add file) called flute charmer in the limited folder and creating a new branch when saving it 
![image](https://user-images.githubusercontent.com/24660095/193422959-dad68750-5b11-4f01-b5ab-d3a7d8e48ada.png)
