### ISSUE TITLE
Role Suggestion: Hells Merchant

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#734]
See discord

**Comment by cryptidjayden** [comment]
i like the concept behind the role (encouraging soulselling more) but i only see recipients using the deal if they're sure they can get themselves attacked as a way to kill merchant, which would be really easy for almost anyone past D1 except other solos. thus, i think merchant would either never use/always cancel their contract, or just die immediately

**Comment by McTsts** [comment]
I think this amy depend on the role list. Town can only really do that if they have an Assassin

**Comment by cryptidjayden** [comment]
or a cult, or a witch. still, it's far riskier than, for example, chef sending evil food, which is almost never done. there just doesn't really seem to be an equal payoff for the merchant to take the considerable risk.

**Comment by McTsts** [comment]
Town often cant afford to care about how important their target is, often its just better to attack any guaranteed scum over a potential townie

**Comment by ThomasRubycrust** [comment]
This could work in a game without an active TK power (so no Assassin or Priest). Then town can't use it just to kill the merchant, wolves I think would rather kill a townie than a hell team member and for solos it would probably work anyway. Also would the Merchant be able to use souls?

**Comment by ThomasRubycrust** [comment]
A single kill role like Witch may be a threat, but it may also not be worth it for town. Also that kill might already have been used up somewhat early.

What might be more of an issue is that this just results in deaths by wolves easily. You'd pick the people that think they may be attacked.. however for them its also likely to actually be attacked. Wolves dont really need to think about it all too much. If they want to kill X, but X might be protected its still better to attack X anyway, after all they might _not_ be protected and even if they are it still at least kills an enemy.

**Comment by McTsts** [comment]
I don't really see how this would be particularly useful for the hell team? Also we already have Bat as a solo role that is based on Hooker.

**Comment by McTsts** [comment]
> <img alt="" width="30" src="https://camo.githubusercontent.com/1fa7fe84ecbad52ec5ac17cbb1d23eb2dae1753da63d7fbf7780a1e51e69be20/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f617661746172732f3435383732373734383530343931313838342f36343531386136376535616637616265663265366436346535386664303662362e77656270"> **shapechange**: i still think this role is rather flawed, but I'm not typing out my explanation again

Well I think the thought is that if hell learns who's responsible people might not be so eager too try to get the Merchant killed.

**Comment by McTsts** [comment]
And then of course the Hell team also is guaranteed to have an extra soul if the HM power was used, so they're definitely in a situation where they could afford a revenge kill.

**Comment by McTsts** [comment]
There can be an offer channel without whispers
