### ISSUE TITLE
Flute Player and Flute Apprentice buff suggestions

### ISSUE THREAD

**Issue by 12Metatron** [McTsts/Werewolves-Roles#735]
**Flute Player buff -** when they obstruct an investigative role (or perhaps just when an enchanted investigative role uses its ability), they learn the correct results. Results posted in flute player SC (though posting in flute_team SC is another possible implementation).

**Flute Apprentice buff -** can choose their redirection to come from either themselves or a different flute team member of their choice (would fail if their target isn't flute team, like if a flute player had their role changed into undead for example). Additionally, similarly to assistant, they should learn when their redirection ability was triggered, but not the ability that was redirected. A possible further buff is to learn which player used the redirected power, but less sure on that.

These buffs would add more options and depth into flute team, something which I think they are currently lacking

**Comment by cryptidjayden** [comment]
i highly dislike the FP buff idea. presuming they do not receive the target, only the target's true role, it's almost entirely useless in public lists (only serving to confirm an invest has been enchanted). it has a little more value in partial lists, but fp by and large does not benefit from learning which roles are ingame, imo.

the fpa buff ideas are a little better. the first idea i don't like. the second idea should absolutely be implemented imo. the third idea may be a step too far, but considering how hard it is to win at flutey business anyway, i wouldn't be against adding it too.

**Comment by McTsts** [comment]
When I suggested the FP buff I meant that they get the full check result, so e.g. @cryptidjayden is Citizen

**Comment by cryptidjayden** [comment]
simultaneously under- and overwhelming, i think? it feels like a lot of info to give flutes, which probably isn't going to occur very much (chance of enchanting an invest (game dependant) * 60%), and which they can't really do anything with? it would only be useful for a) finding more invests/avoiding ua, if there are any and b) bargaining with wolves or town for an extra day or two to live, which given the transparency of how close flutes are to their wincon is rarely if ever going to benefit them

**Comment by McTsts** [comment]
yeah fair, probably not very useful

**Comment by cryptidjayden** [comment]
a better fp buff would be giving it the old fpa ability to join enchanted, but this may be too strong

**Comment by cryptidjayden** [comment]
actually i don't think this would be too strong. a major component of fp's severe difficulty is how easy it is to find if it even makes it to late game - this would mitigate that while still giving the game-controlling team the ability to deduce fp identity if they have enough info

**Comment by McTsts** [comment]
> a better fp buff would be giving it the old fpa ability to join enchanted, but this may be too strong

Do you mean giving it to FPA or to FP? Because if you mean FP im against it

**Comment by cryptidjayden** [comment]
i meant fp, i think it wouldn't make sense for fpa. do you think it's too strong?

**Comment by cryptidjayden** [comment]
i don't have any other buff ideas so if you do, may as well just not buff fp

**Comment by McTsts** [comment]
the FP's key mechanic is that they get found out by enchanting

**Comment by cryptidjayden** [comment]
i mean, doesn't that very mechanic practically preclude fp from ever winning? the only situations i can think of is one team handing flutes the win to prevent another from winning, _or_ flutes getting incredibly lucky and not enchanting any ua _plus_ game controllers being stupid.

that all being said, i suppose giving fp a layer of protection and/or a disguise could help a little

**Comment by cryptidjayden** [comment]
but the chances of those three other unenchanted players all being unconfirmed is pretty low, especially if there's TI or WI immune to the obstruction or unenchanted

**Comment by cryptidjayden** [comment]
is it possible? yes, of course, but fp is notably harder than the other unlimited solos, and more boring to boot

**Comment by McTsts** [comment]
FP is just kind of focused on the trying to stay hidden while enchants reveal you further part, hence also the obstruction which slightly counters that. I don't think removing it would be very good.
