### ISSUE TITLE
New Solo roles?

### ISSUE THREAD

**Issue by cryptidjayden** [McTsts/Werewolves-Roles#736]
We need more SP teams for sure - FP is hard (and kinda boring), and the limited SPs Reaper and especially Shepherd are a) limited b) really rather complex. In terms of SK roles, Devil is fun, Pyro can be bland, and WWW (and to an extent PB) work best in larger games, but new SK roles are less of a priority than SP (develop ice royals more?)

Also, the existing Solo _teams_ could maybe use some more team roles, to add a little more spice and enable greater flexibility. (The Hell Merchant suggestion inspired this).

We should come up with ideas for new Hell, Flute, and Pyro roles, and revisit the proposed Ice Royals revamp.

**Comment by cryptidjayden** [comment]
tried to send this last night and it clearly didnt work lol, a few other issues raised since my attempted submission contribute to this

**Comment by McTsts** [comment]
Underworld is a SP with a secondary role in development

**Comment by McTsts** [comment]
I definitely approve of looking at the IR revamp :)

**Comment by cryptidjayden** [comment]
underworld is SR technically; the distinction doesn't really matter except in partial lists, where confusion about the solo role can greatly aid solos. ignoring that barely relevant point i just made, underworld doesn't have a tertiary, which is one of the two solo issues i was addressing

**Comment by McTsts** [comment]
I mean there's technically three roles

**Comment by cryptidjayden** [comment]
undead is like a billionary role. it is shit. it does not count.

**Comment by Shepherdwhen** [comment]
what if we have a true solo that is solo power instead of solo killing, like how crypto and www work where they win alone

**Comment by McTsts** [comment]
We removed true solos, but it doesn't really matter. Having a solo that works properly alone would be nice, but that by itself isnt really much of a suggestion

**Comment by ThomasRubycrust** [comment]
We can bring back four horsemen as a solo power, instead of killing each horseman applies a negative effect of some sort (e.g. an obstruction similiar to FP, a unwanted disguise, a vote manipulation and idk)

**Comment by McTsts** [comment]
Here's an overview on current solo teams and roles:
![image](https://user-images.githubusercontent.com/24660095/193427280-cf7ff211-a99c-4b76-94ab-b391e4cf8931.png)

**Comment by McTsts** [comment]
I'm against role blocking

**Comment by McTsts** [comment]
I think Pyromancer and Flute Player probably need it the most.

**Comment by McTsts** [comment]
We have an open issue/post for it, but I think nobody thought of anything particularly great so far. It should be something that somehow has something to do with powdering or at least relates to the team theme in some way
