### ISSUE TITLE
Lone Coyote

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#745]
lone coyote is pretty good for the wolfpprentice i think

_Originally posted by @cryptidjayden in https://github.com/McTsts/Werewolves-Roles/issues/520#issuecomment-1256487926_
      

I'm splitting this off into its one issue because #520 is a mess.

The suggestion for Lone Coyote is a packless non-lycan who turns into the first pack role that dies.

**Comment by McTsts** [comment]
I'm not sure it's a good idea to use "coyote" for this. For "fox" we have a pretty good category of role, but if we name this one lone coyote we don't really have a proper concept of what "coyote" is and we'll have used up a term that we may want to use for a role category at some point in the future and then we won't have any options. Also additionally I'm not sure how "lone coyote" relates to the actual functionality of the role.

**Comment by McTsts** [comment]
The original idea had the addition that it would only turn into a lynched wolf not one that dies otherwise, which may be interesting.
