### ISSUE TITLE
WM Idea

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#746]
had an idea: packless WM that is notified when it is selected as a target/has a non-kill power used on it, and if it's targeted/has a power used on it by a pack member is given that wolf's identity. needs work.

_Originally posted by @cryptidjayden in https://github.com/McTsts/Werewolves-Roles/issues/520#issuecomment-1144935863_

**Comment by McTsts** [comment]
I thought about it more and at this point I think it probably makes more sense to name new packless lycanless werewolves in the same way as Warlock and Tanner instead of starting a new naming convention. I think the original suggestions for that were Husk and Sorcerer

**Comment by McTsts** [comment]
I think Sorcerer is once again not very fitting for this role because it's fairly passive.
