### ISSUE TITLE
Should Wraith stay as SK?

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#757]
Reaper is considered SP and Wraith is SK even though its killing ability is one that Reaper shares. 

@12Metatron brought up that for solos it makes sense to prioritize abilites that correspond to their win condition. 
 So in this case: Reaper & Wraith _can_ kill, but it's not their goal. They can also both use a _power_ and using their power on everyone is their goal so it makes more sense to have that as the category.

**Comment by McTsts** [comment]
I think it would make most sense if we always classify solo roles as their team (so Imp becomes SK, Undead SR etc) which kinda makes sense but I also kind of don't like that. I guess for Wraith it does have the power to turn sleepless so it sort of makes sense to make it SP just from that, I'd be fine with it but am not fully convinced. I think my prefered option is to keep it as SK but I'm fine with changing it.

**Comment by 12Metatron** [comment]
I think wraith at the very least should be sp, cuz of the sleepless power. By being SK it makes it a threat to AT even though reaper isn't, which is always a bit weird and an unnecessary handicap

**Comment by McTsts** [comment]
Hm, I kind of forgot AT existed. Looking at it from an AT perspective it is weird how it sees Wraith as a threat but not Reaper, when Reaper is definitely the bigger threat (even just from a killing power pov - reaper has the wraith power + the ability to pick up other killing powers).
