### ISSUE TITLE
Regretful Wolf

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#759]
**Rough Role Idea**
The Regretful Wolf is a town aligned packless lycan who feels remorse for killing town. However they must still kill every night.

**Ethan:**
Is [it a] forced kill, what happens if they don't, what if they kill town?

**Ts:**
Unsure, but it cant be a priest clone. It would probably be a lycan which gives it something unique at least

**Comment by McTsts** [comment]
That's somewhat interesting, but I dont think the lycan part would work very well.

**Comment by ThomasRubycrust** [comment]
We should revisit this idea :)

**Comment by ThomasRubycrust** [comment]
It's much better though because you get an ability and if you turn you're responsible yourself.

**Comment by ThomasRubycrust** [comment]
Would it be a forced kill?

**Comment by ThomasRubycrust** [comment]
yeah. Im assuming we'd have it be like Assassin where N1 is skipped though

**Comment by ThomasRubycrust** [comment]
> <img alt="" width="30" src="https://camo.githubusercontent.com/1fa7fe84ecbad52ec5ac17cbb1d23eb2dae1753da63d7fbf7780a1e51e69be20/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f617661746172732f3435383732373734383530343931313838342f36343531386136376535616637616265663265366436346535386664303662362e77656270"> **shapechange**: it's just plain old assassin with unlimited kills and vulnerability to AT

well except for the becoming solo part?

**Comment by ThomasRubycrust** [comment]
If it turns solo it needs to turn into a different role I think. It could be permanently disguised as that one.

**Comment by ThomasRubycrust** [comment]
yeah thats why it gets the forced kill

**Comment by ThomasRubycrust** [comment]
> <img alt="" width="30" src="https://camo.githubusercontent.com/1fa7fe84ecbad52ec5ac17cbb1d23eb2dae1753da63d7fbf7780a1e51e69be20/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f617661746172732f3435383732373734383530343931313838342f36343531386136376535616637616265663265366436346535386664303662362e77656270"> **shapechange**:
> 
> > 💬 **ThomasRubycrust**:
> > If it turns solo it needs to turn into a different role I think. It could be permanently disguised as that one.
> 
> not sure how i feel about that - i think having it appear wolf-like, at least while it's not a solo, should be a major part of the role

true, disguised as Wolf then?

**Comment by ThomasRubycrust** [comment]
ah

**Comment by ThomasRubycrust** [comment]
outout+outcast+outcast+castcast wolf
