### ISSUE TITLE
Necromancer

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#763]
**Rough Role Idea**
lets a dead person put a vote on the public polls, but only one use per player

**Ethan**
Necromancer is broken from the get go. you have a dead confirmed town just vote the most dangerous player then everyone follow. the only way would to be have the necromancer target during the night and then during the day the dead player chooses with an action that pings hosts and hosts add it as an +1 base on the player like stalker

**Ts**
The way I was thinking it would work is we use the stalker invisible vote for the dead person's vote which is the same thing you said. I also was undecided if this would be a wolf or town.

**Comment by Shepherdwhen** [comment]
I think this would be a better town role as there is no point in wolves using this unless they're losing and there is no guarantee it will survive long enough as wolf

**Comment by McTsts** [comment]
Yeah probably. Though this name sounds evil so a less evil sounding name would be needed.

**Comment by McTsts** [comment]
Necromancer sounds like a packless lycanless werewolf honestly

**Comment by McTsts** [comment]
Hm, I don't think that's really good. That's just similar to Medium but not fakable.
