### ISSUE TITLE
Mad Scientist Teams

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#8]
MS considers 'Solo' as one team

**Comment by venomousbirds** [comment]
Change it to include the different solo teams

**Comment by McTsts** [comment]
Yeah that's what this issue is for :) idk how though

**Comment by venomousbirds** [comment]
Name every single Solo team in the description :)

**Comment by McTsts** [comment]
enjoy :)

**Comment by venomousbirds** [comment]
I don't know what you're trying to say but 
![thight](https://user-images.githubusercontent.com/80123992/114476447-832fa880-9bfa-11eb-8675-d19778daf95e.png)

**Comment by McTsts** [comment]
I assigned the issue to you :)

**Comment by venomousbirds** [comment]
I am coming to murder you

**Comment by McTsts** [comment]
After taking care of this issue, I hope

**Comment by venomousbirds** [comment]
You're the issue now

**Comment by McTsts** [comment]
![image](https://user-images.githubusercontent.com/24660095/114476807-3dbfab00-9bfb-11eb-99f6-918de996c901.png)

**Comment by venomousbirds** [comment]
![realmad](https://user-images.githubusercontent.com/80123992/114476921-88d9be00-9bfb-11eb-9863-9fd2d01e336c.png)
