### ISSUE TITLE
v15 Exhaustive Changelog

### ISSUE THREAD

**Issue by ThomasRubycrust** [McTsts/Werewolves-Roles#832]
**Changelog**

*Role Additions*
- Alcoholic: New role to make Bartender work better
- Firebug: Protective Pyro Role
- Horsemen: Full new solo team (7 roles)
- Flute Charmer: Investigative Flute Role
- Amulet Holder: Protective Town Role
- Cerebus: Protective Hell Role
- Detective: Investigative Unaligned Role
- Recluse: Packless Lycanless Werewolf Misc Role
- Cult Acolyte: Child/Apprentice cultist role

*Role Changes*
- Inform entire team on exorcism
- CF: Invest result reveal immediate
- Lone Wolf: Doesnt double kill anymore, instead a wolf priest
- Trickster Wolf: If last wolf, turns into a normal wolf
- Reaper: Revamp to be more managable, Category change to SK
- Bard: Revamp to be much less precise
- Unlimited: Direwolf, Amnesiac, Devout Villager
- Removed: Scared White Werewolf
- Dog/Cat: TC Option -> Journalist
- Saboteur Wolf: Buff; Target is now hidden
- Alpha Wolf: Now has DV power on top of its existing powers
- Jury: Now gets a check every night (except Night 1) regardless of amount of Jurors
- Royal Knight: Can't use their powers Day 1 anymore
- Psychopath Buff: Guaranteed to have a person from each team. May investigate OR disguise a player each day.
- Wolf Cub: Renamed from Wolf's Cub
- Stalker: No more whisper channels, invisible votes arent revealed anymore, threatened player doesnt know, now a day effect
- Look-Alike: Updated LA cases
- Bat Buff: May now haunt anyone
- Zombie Nerf: Now requires bites two nights in a row
- Grandma & Corrupt Wolf: Now affected by redirections
- New Hags: Now wronged by killing, lynching, and recruitment only. Require at least one wronging. Cupid Hag now basically a proper hag.
- Golem: Deleted the role

*Other Changes*
- Additional channel info message (e.g. for Bakers and Couple channels)
- Usages of role icon emojis in channel info messages
- Wolfish: A new term to collectively refer to werewolves, pack members and lycans
- New Werewolf role category: Werewolf Group
- Removed Werewolf Transformation category and changed how Transformation works (its now a status, like limited)

**Comment by ThomasRubycrust** [comment]
+ Jury Buff

**Comment by McTsts** [comment]
- Royal Knight nerf
- Psychopath buff

**Comment by McTsts** [comment]
- Introduce WG

**Comment by McTsts** [comment]
- Introduction of Wolfish
- Changed Golem

**Comment by McTsts** [comment]
- Added Cult Acolyte
- LA Case Changes

**Comment by McTsts** [comment]
- Bat Buff

**Comment by McTsts** [comment]
- Zombie Nerf
- Solo Rewrites
- Removed WT category / change how transformation category works

**Comment by McTsts** [comment]
- Grandma & Corrupt Wolf are now affected by redirections

**Comment by McTsts** [comment]
- Delete Golem
- Add WR category
