### ISSUE TITLE
Disguises don't seem correct

### ISSUE THREAD

**Issue by venomousbirds** [McTsts/Werewolves-Roles#86]
> Current Disguises
• Archangel - permanent, weak
• Devil - permanent, weak
• Disguised Fox - non-permanent, weak
• Ice Queen - depends
• Psychopath - non-permanent, strong
• Sneaking Wolf - permanent, strong
• Tanner - non-permanent, weak
• White Werewolf - permanent, strong

Roles affected by strong disguises can see through the Tanner's disguises, I don't think that's correct.

**Comment by McTsts** [comment]
Roles that are only affected by strong disguises can see through weak disguises such as the tanner one so that seems right?

**Comment by venomousbirds** [comment]
Are there actually any roles that are only affected by strong diguises?

**Comment by McTsts** [comment]
Receptionist, Ranger, Bard

**Comment by McTsts** [comment]
Journalist ![hepi](https://user-images.githubusercontent.com/24660095/114872090-403c2380-9dfa-11eb-9c7d-a5e7512eb16a.png)

**Comment by McTsts** [comment]
> If not explicitly listed otherwise, every investigative role is affected by strong disguises, and not affected by weak ones.
so I guess technically Journalist isn't affected, but neither are Ranger and Bard (which should be)

**Comment by McTsts** [comment]
I'd recommend remove the "investigative" from there, and then clarifying that Journalist isn't affected by strong disguises

**Comment by McTsts** [comment]
AT is also unaffected by weak disguises

**Comment by venomousbirds** [comment]
Ranger has been affected by Tanner in the past, and Bard defintiely should be. Journalist shouldn't be affected by any disguise in my opinion. Receptionist should be affected by all disguises

**Comment by McTsts** [comment]
I disagree entirely with that. Ranger and Bard are definitely not intended to be affected by weak disguises. Receptionist was meant to be unaffected by disguises, but is affected by only strong disguises in accordance to #69

**Comment by McTsts** [comment]
Receptionist being affected by strong disguises is already kinda lame as well.

**Comment by venomousbirds** [comment]
I think it's currently affected, at least I've seen recep checks been influenced by sneaking wolf

**Comment by McTsts** [comment]
Weak Disguises: Meant to _only_ affect roles that target a player and can learn that players role via investigation.
Hence:
> The Fortune Teller gains more information, but is affected by weak disguises and obstructions. 

Strong Disguises: Meant to affect any role that learns the role of another player in any way.

**Comment by McTsts** [comment]
> I think it's currently affected, at least I've seen recep checks been influenced by sneaking wolf

Yes. Sneaking Wolf is strongly disguised. Since Receptionist is affected by strong disguises (#69) this is accurate. (I just don't think this is how it should be)

**Comment by venomousbirds** [comment]
> I'd recommend remove the "investigative" from there, and then clarifying that Journalist isn't affected by strong disguises

Yeah that'd work, we'd have to clarify it with some roles
