### ISSUE TITLE
journalist is affected by strong disguises

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#87]
if #86 is fixed according to what I said this will be an issue

**Comment by venomousbirds** [comment]
I don't think Journalist should be affected by any disguises? Journalist isn't even an investigative role

**Comment by McTsts** [comment]
it definitely shouldnt be

**Comment by venomousbirds** [comment]
The description currently doesn't imply that it's affected

**Comment by McTsts** [comment]
Yes as I said this is only an issue if we do my suggested change in #86
