### ISSUE TITLE
Ice King isn't really good

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#9]
Ice King needs more work

**Comment by venomousbirds** [comment]
Ice King is very neglected and I personally think the role is just really bad. It has potential but it's barely used, so we either have to rework it or just throw it away

**Comment by McTsts** [comment]
Yeah I agree. I really want it to work, but I also still think it shouldn't have been added to the role book in the first place :(

**Comment by venomousbirds** [comment]
It's a great concept but the development of the role went way too fast

**Comment by 12Metatron** [comment]
it needs some ability to not get found out as easily, like maybe the choice to not use its extra votes. It gets found out super easy and it has no defences against wolves, causing to just be almost impossible for it to deal with wolves.

**Comment by McTsts** [comment]
> it needs some ability to not get found out as easily, like maybe the choice to not use its extra votes. It gets found out super easy and it has no defences against wolves, causing to just be almost impossible for it to deal with wolves.

I feel like even that won't be enough. Even with that it can't really do anything against the wolves and it can't really work with town because town are the people it can actually freeze (thereby weakening town)

**Comment by Mjnstag** [comment]
Maybe the ability of the guessed player gets frozen for a certain amount of time?

**Comment by McTsts** [comment]
Currently being frozen is one is not super noticeable, so I'm not sure if that's a good change

**Comment by venomousbirds** [comment]
can this be closed because we moved IK to limited?

**Comment by McTsts** [comment]
> can this be closed because we moved IK to limited/removed it idk what we did?

it's limited now, but it's still an issue (unless we remove it entirely)
