### ISSUE TITLE
Barber <-> FPA

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#93]
If an enchanted Barber targets a FPA, what happens? The FPA's target is killed and it is announced that the Butcher killed them?

**Comment by Mjnstag** [comment]
if we follow the descriptions, i think that is what would happen?

**Comment by McTsts** [comment]
the result of #106 currently is that redirected attacks result in a failure, if a redireced attack results in a failure then Barber shouldn't be revealed.

**Comment by McTsts** [comment]
This is also related to #7

**Comment by Mjnstag** [comment]
> The action still happens (but with the player it was redirected onto and not the original target), but nobody is revealed.

so the barber attack will go through but it wont say who attacked, only "x died"?

**Comment by McTsts** [comment]
Yes

**Comment by Mjnstag** [comment]
aighty 👍
