### ISSUE TITLE
Clairvoyant Fox can check D0

### ISSUE THREAD

**Issue by McTsts** [McTsts/Werewolves-Roles#95]
is this intentional?

**Comment by 12Metatron** [comment]
disguised fox can use powers d0, so should probably be consistent for all foxes

**Comment by venomousbirds** [comment]
I personally don't think a D0 investigation is useful and thus shouldn't be a thing

**Comment by McTsts** [comment]
honestly I'm kinda feeling like a D0 invest makes sense

**Comment by McTsts** [comment]
because otherwise the first info is N2 which is pretty far into the game

**Comment by Shepherdwhen** [comment]
> honestly I'm kinda feeling like a D0 invest makes sense

I actually thought it did this when I first saw the role NGL, It makes sense as if it dies N1 then it's been completely useless and it could have just joined the pack and not been killed by wolves

**Comment by McTsts** [comment]
Definitely think we should allow this now

**Comment by McTsts** [comment]
WAI
